"""
gen_nb14_sector_nlp.py -- Generate notebooks/eda/14_sector_nlp.ipynb

Extends NB13 sector alpha with sector-specific NLP sentiment features.
Compares: macro-only (NB13) vs macro+sector-NLP performance.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '14_sector_nlp.ipynb'


def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


cells = []

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 14 — Sector Alpha with NLP Sentiment\n\n"
    "> *Adding sector-specific news sentiment to the cross-sectional sector rotation model*\n\n"
    "## Hypothesis\n"
    "Sector-specific news sentiment (BANK, ENERGY, ICT, COMMERCE, HEALTH, PROPERTY, FOOD) "
    "carries incremental information about **relative** sector performance beyond macro features.\n\n"
    "## Approach\n"
    "| Step | Detail |\n"
    "|------|--------|\n"
    "| Data | 1,295 sector-tagged articles (Google News RSS + VADER), 2007–2026 |\n"
    "| Coverage | 8–16% historical, **40–95% in 2023–2026** |\n"
    "| Leakage | All NLP features strictly lagged by 1 week |\n"
    "| Handling | XGBoost native NaN → uses NLP when available, ignores when not |\n"
    "| Comparison | Walk-forward IC/Sharpe: macro-only (NB13) vs macro+NLP |\n"
    "| Key test | IC uplift in **NLP coverage era** (2020–2025) |\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "from scipy.stats import spearmanr\n"
    "from sklearn.base import clone\n"
    "from xgboost import XGBRegressor\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.dpi': 110, 'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'font.size': 10, 'axes.titlesize': 11,\n"
    "})\n"
    "\n"
    "TC            = 0.001   # 10 bps per side\n"
    "MIN_TRAIN_W   = 156     # 3 years minimum training\n"
    "FOLD_SIZE_W   = 52      # 1 year per fold\n"
    "LONG_K        = 2\n"
    "SHORT_K       = 2\n"
    "SECTORS       = ['BANK','ENERGY','ICT','COMMERCE','HEALTH','PROPERTY','FOOD']\n"
    "NLP_ERA_START = pd.Timestamp('2020-01-01')\n"
    "\n"
    "print('Setup complete.')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 1 — Load Data"))

cells.append(code(
    "# ── Sector returns ────────────────────────────────────────────────────────\n"
    "sector_df = pd.read_csv(PROC / 'sector_weekly.csv', index_col=0, parse_dates=True)\n"
    "sector_df = sector_df.resample('W-FRI').last()\n"
    "print(f'Sector data:  {sector_df.shape[0]} weeks x {sector_df.shape[1]} sectors')\n"
    "\n"
    "# ── Macro features ────────────────────────────────────────────────────────\n"
    "macro_df = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "macro_df = macro_df.resample('W-FRI').last()\n"
    "\n"
    "MACRO_FEATS = [\n"
    "    'sp500_ret_w','sp500_rvol_4w','sp500_ret_d_lag1',\n"
    "    'eem_ret_d_lag1','oil_ret_w','oil_ret_d_lag1',\n"
    "    'gold_ret_w','gold_rvol_4w','dxy_ret_w','dxy_ret_d_lag1',\n"
    "    'us_10yr_treasury_ret_w','us_2yr_treasury_ret_w',\n"
    "    'vix_z','regime','yield_curve_slope',\n"
    "    'SET_index_ret_w','SET_index_rvol_4w',\n"
    "]\n"
    "MACRO_FEATS = [f for f in MACRO_FEATS if f in macro_df.columns]\n"
    "print(f'Macro feats:  {len(MACRO_FEATS)}')\n"
    "\n"
    "# ── Sector NLP sentiment ──────────────────────────────────────────────────\n"
    "nlp_df = pd.read_csv(PROC / 'sector_sentiment_weekly.csv', index_col=0, parse_dates=True)\n"
    "nlp_df = nlp_df.resample('W-FRI').last()\n"
    "print(f'NLP data:     {nlp_df.shape[0]} weeks x {nlp_df.shape[1]} cols')\n"
    "\n"
    "# Align all to common date range\n"
    "common = sector_df.index.intersection(macro_df.index).intersection(nlp_df.index)\n"
    "sector_df = sector_df.loc[common]\n"
    "macro_df  = macro_df.loc[common]\n"
    "nlp_df    = nlp_df.loc[common]\n"
    "print(f'Common dates: {len(common)} weeks ({common[0].date()} -> {common[-1].date()})')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 2 — NLP Coverage Analysis"))

cells.append(code(
    "sent_cols = [f'{s}_sent' for s in SECTORS]\n"
    "vol_cols  = [f'{s}_vol'  for s in SECTORS]\n"
    "\n"
    "# Weekly coverage heatmap by sector and year\n"
    "cov = nlp_df[sent_cols].copy()\n"
    "cov.columns = SECTORS\n"
    "cov['year'] = cov.index.year\n"
    "yearly_cov = cov.groupby('year')[SECTORS].apply(lambda x: x.notna().mean())\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "\n"
    "# Left: coverage heatmap\n"
    "ax = axes[0]\n"
    "im = ax.imshow(yearly_cov.values.T, aspect='auto', cmap='YlGn', vmin=0, vmax=1)\n"
    "ax.set_xticks(range(len(yearly_cov.index)))\n"
    "ax.set_xticklabels(yearly_cov.index, rotation=90, fontsize=8)\n"
    "ax.set_yticks(range(len(SECTORS)))\n"
    "ax.set_yticklabels(SECTORS)\n"
    "ax.set_title('NLP Coverage (fraction of weeks with news data)')\n"
    "plt.colorbar(im, ax=ax, fraction=0.03, label='Coverage')\n"
    "\n"
    "# Right: total articles per sector over time\n"
    "ax2 = axes[1]\n"
    "cov2 = nlp_df[vol_cols].copy()\n"
    "cov2.columns = SECTORS\n"
    "cov2['year'] = cov2.index.year\n"
    "yearly_vol = cov2.groupby('year')[SECTORS].sum()\n"
    "yearly_vol.plot(kind='bar', stacked=True, ax=ax2, colormap='tab10', legend=True)\n"
    "ax2.set_title('News Volume per Sector per Year')\n"
    "ax2.set_ylabel('Articles')\n"
    "ax2.tick_params(axis='x', rotation=90)\n"
    "ax2.legend(bbox_to_anchor=(1.02, 1), loc='upper left', fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'nlp_coverage.png', dpi=110, bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('NLP coverage summary:')\n"
    "print(f'  NLP era (>=2020): {(nlp_df.index >= NLP_ERA_START).sum()} weeks')\n"
    "for s in SECTORS:\n"
    "    col = f'{s}_sent'\n"
    "    total = nlp_df[col].notna().sum()\n"
    "    era   = nlp_df.loc[nlp_df.index >= NLP_ERA_START, col].notna().sum()\n"
    "    print(f'  {s:12s}: {total:3d} total, {era:3d} in NLP era')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 3 — Feature Engineering: Sector NLP Features"))

cells.append(code(
    "def build_nlp_features(nlp_df, sectors):\n"
    "    \"\"\"Build sector-specific NLP features — all strictly lagged 1 week.\"\"\"\n"
    "    feats = {}\n"
    "\n"
    "    sent_raw = nlp_df[[f'{s}_sent' for s in sectors]].copy()\n"
    "    sent_raw.columns = sectors\n"
    "    vol_raw  = nlp_df[[f'{s}_vol' for s in sectors]].copy()\n"
    "    vol_raw.columns  = sectors\n"
    "    pos_raw  = nlp_df[[f'{s}_pos' for s in sectors]].copy()\n"
    "    pos_raw.columns  = sectors\n"
    "\n"
    "    for s in sectors:\n"
    "        raw = sent_raw[s]\n"
    "        vol = vol_raw[s]\n"
    "\n"
    "        # Lag 1 week (no lookahead)\n"
    "        feats[f'{s}_sent_lag1']    = raw.shift(1)\n"
    "\n"
    "        # 4-week rolling mean (lagged)\n"
    "        feats[f'{s}_sent_4w']      = raw.shift(1).rolling(4, min_periods=1).mean()\n"
    "\n"
    "        # Sentiment surprise: deviation from 4w mean\n"
    "        sent_ma = raw.shift(1).rolling(4, min_periods=1).mean()\n"
    "        feats[f'{s}_sent_surp']    = raw.shift(1) - sent_ma.shift(1)\n"
    "\n"
    "        # News volume lag1 (more news = higher activity)\n"
    "        feats[f'{s}_news_vol']     = vol.shift(1).fillna(0)\n"
    "\n"
    "    # Cross-sectional relative sentiment (sector vs mean of all sectors)\n"
    "    sent_lag = sent_raw.shift(1)\n"
    "    mkt_sent = sent_lag.mean(axis=1)\n"
    "    for s in sectors:\n"
    "        feats[f'{s}_sent_rel']     = sent_lag[s] - mkt_sent\n"
    "\n"
    "    return pd.DataFrame(feats, index=nlp_df.index)\n"
    "\n"
    "\n"
    "nlp_feats = build_nlp_features(nlp_df, SECTORS)\n"
    "print(f'NLP features built: {nlp_feats.shape[1]} columns')\n"
    "print(f'Features: {list(nlp_feats.columns[:8])} ...')\n"
    "\n"
    "# Coverage check\n"
    "lag1_cols = [f'{s}_sent_lag1' for s in SECTORS]\n"
    "era_mask = nlp_feats.index >= NLP_ERA_START\n"
    "era_cov = nlp_feats.loc[era_mask, lag1_cols].notna().mean()\n"
    "print(f'\\nNLP-era (2020+) sent_lag1 coverage:')\n"
    "for c, v in era_cov.items():\n"
    "    print(f'  {c:20s}: {v:.0%}')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 4 — Build Panel (Sector + Macro + NLP)"))

cells.append(code(
    "SECTOR_FEATS = ['mom1','mom4','mom12','mom26','rvol4','rvol12',\n"
    "                'mom1_rank','mom4_rank','mom12_rank','mom1_rel','mom4_rel']\n"
    "\n"
    "NLP_FEATS = [c for c in nlp_feats.columns]\n"
    "\n"
    "def build_panel(sector_df, macro_df, nlp_feats_df):\n"
    "    mom1  = sector_df.shift(1)\n"
    "    mom4  = sector_df.shift(1).rolling(4).mean()\n"
    "    mom12 = sector_df.shift(1).rolling(12).mean()\n"
    "    mom26 = sector_df.shift(1).rolling(26).mean()\n"
    "    rvol4 = sector_df.shift(1).rolling(4).std()\n"
    "    rvol12= sector_df.shift(1).rolling(12).std()\n"
    "    mom1_rank  = mom1.rank(axis=1, pct=True) - 0.5\n"
    "    mom4_rank  = mom4.rank(axis=1, pct=True) - 0.5\n"
    "    mom12_rank = mom12.rank(axis=1, pct=True) - 0.5\n"
    "    mkt_mom1 = mom1.mean(axis=1)\n"
    "    mkt_mom4 = mom4.mean(axis=1)\n"
    "    mom1_rel = mom1.subtract(mkt_mom1, axis=0)\n"
    "    mom4_rel = mom4.subtract(mkt_mom4, axis=0)\n"
    "    fwd_ret  = sector_df.shift(-1)\n"
    "\n"
    "    dates = sector_df.index\n"
    "    rows  = []\n"
    "    for date in dates:\n"
    "        fwd_vals = fwd_ret.loc[date]\n"
    "        if fwd_vals.isna().all():\n"
    "            continue\n"
    "        mkt_fwd = fwd_vals.mean()\n"
    "        for sec in sector_df.columns:\n"
    "            if pd.isna(fwd_vals[sec]):\n"
    "                continue\n"
    "            row = {\n"
    "                'date': date, 'sector': sec,\n"
    "                'fwd_ret': fwd_vals[sec],\n"
    "                'fwd_excess': fwd_vals[sec] - mkt_fwd,\n"
    "                'mom1':       mom1.loc[date, sec],\n"
    "                'mom4':       mom4.loc[date, sec],\n"
    "                'mom12':      mom12.loc[date, sec],\n"
    "                'mom26':      mom26.loc[date, sec],\n"
    "                'rvol4':      rvol4.loc[date, sec],\n"
    "                'rvol12':     rvol12.loc[date, sec],\n"
    "                'mom1_rank':  mom1_rank.loc[date, sec],\n"
    "                'mom4_rank':  mom4_rank.loc[date, sec],\n"
    "                'mom12_rank': mom12_rank.loc[date, sec],\n"
    "                'mom1_rel':   mom1_rel.loc[date, sec],\n"
    "                'mom4_rel':   mom4_rel.loc[date, sec],\n"
    "            }\n"
    "            # Macro features (same for all sectors at this date)\n"
    "            for f in MACRO_FEATS:\n"
    "                row[f] = macro_df.loc[date, f] if date in macro_df.index else np.nan\n"
    "            # NLP features (sector-specific)\n"
    "            for f in NLP_FEATS:\n"
    "                # Each NLP feature col is named SECTOR_...\n"
    "                # Match to the sector: e.g. 'BANK_sent_lag1' -> sec='BANK'\n"
    "                row[f] = nlp_feats_df.loc[date, f] if date in nlp_feats_df.index else np.nan\n"
    "            rows.append(row)\n"
    "\n"
    "    panel = pd.DataFrame(rows)\n"
    "    panel['date'] = pd.to_datetime(panel['date'])\n"
    "    return panel\n"
    "\n"
    "\n"
    "print('Building feature panel (sector + macro + NLP)...')\n"
    "panel_raw = build_panel(sector_df, macro_df, nlp_feats)\n"
    "\n"
    "# Drop rows where target is NaN, keep rows with sector features even if NLP is NaN\n"
    "panel = panel_raw.dropna(subset=['fwd_excess'])\n"
    "n_dates = panel['date'].nunique()\n"
    "print(f'Panel: {len(panel)} rows, {n_dates} dates')\n"
    "\n"
    "ALL_FEATS    = SECTOR_FEATS + MACRO_FEATS + NLP_FEATS\n"
    "ALL_FEATS    = [f for f in ALL_FEATS if f in panel.columns]\n"
    "MACRO_ONLY   = [f for f in SECTOR_FEATS + MACRO_FEATS if f in panel.columns]\n"
    "print(f'Total features: {len(ALL_FEATS)} ({len(MACRO_ONLY)} macro-only, {len(NLP_FEATS)} NLP)')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 5 — Walk-Forward: Macro-Only vs Macro+NLP"))

cells.append(code(
    "def make_xgb():\n"
    "    return XGBRegressor(\n"
    "        n_estimators=100, max_depth=3, learning_rate=0.05,\n"
    "        subsample=0.7, colsample_bytree=0.6,\n"
    "        min_child_weight=10, reg_alpha=0.5, reg_lambda=5.0,\n"
    "        tree_method='hist',\n"
    "        random_state=42, verbosity=0, n_jobs=1,\n"
    "    )\n"
    "\n"
    "\n"
    "def walk_forward_panel(panel, features, target='fwd_excess',\n"
    "                        min_train=156, fold_size=52,\n"
    "                        long_k=2, short_k=2):\n"
    "    dates = sorted(panel['date'].unique())\n"
    "    n = len(dates)\n"
    "    results = []\n"
    "\n"
    "    t = min_train\n"
    "    while t + fold_size <= n:\n"
    "        train_dates = dates[:t]\n"
    "        test_dates  = dates[t:t + fold_size]\n"
    "\n"
    "        train = panel[panel['date'].isin(train_dates)]\n"
    "        test  = panel[panel['date'].isin(test_dates)]\n"
    "\n"
    "        feats = [f for f in features if f in panel.columns]\n"
    "        medians = train[feats].median()\n"
    "\n"
    "        Xtr = train[feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "        Xte = test[feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "        ytr = train[target].values\n"
    "\n"
    "        m = make_xgb()\n"
    "        m.fit(Xtr, ytr)\n"
    "        preds = m.predict(Xte)\n"
    "\n"
    "        test = test.copy()\n"
    "        test['pred'] = preds\n"
    "\n"
    "        # Per-date IC and signal\n"
    "        for dt, grp in test.groupby('date'):\n"
    "            if len(grp) < 3:\n"
    "                continue\n"
    "            ic, _ = spearmanr(grp['pred'], grp['fwd_excess'])\n"
    "            if pd.isna(ic):\n"
    "                ic = 0.\n"
    "\n"
    "            grp_s = grp.sort_values('pred', ascending=False)\n"
    "            long_ret  = grp_s.head(long_k)['fwd_ret'].mean()\n"
    "            short_ret = grp_s.tail(short_k)['fwd_ret'].mean()\n"
    "            port_ret  = (long_ret - short_ret) / 2\n"
    "\n"
    "            results.append({\n"
    "                'date': dt, 'ic': ic,\n"
    "                'gross_ret': port_ret,\n"
    "                'net_ret':   port_ret - 4 * TC,\n"
    "            })\n"
    "\n"
    "        t += fold_size\n"
    "\n"
    "    return pd.DataFrame(results).set_index('date').sort_index()\n"
    "\n"
    "\n"
    "print('Running walk-forward (macro-only)...')\n"
    "res_macro = walk_forward_panel(panel, MACRO_ONLY)\n"
    "print(f'  Macro-only:  {len(res_macro)} weeks')\n"
    "\n"
    "print('Running walk-forward (macro + NLP)...')\n"
    "res_nlp   = walk_forward_panel(panel, ALL_FEATS)\n"
    "print(f'  Macro+NLP:   {len(res_nlp)} weeks')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 6 — IC Comparison: Macro-Only vs Macro+NLP"))

cells.append(code(
    "def ic_stats(res, label):\n"
    "    ics = res['ic'].dropna()\n"
    "    n   = len(ics)\n"
    "    ic_mean = ics.mean()\n"
    "    ic_std  = ics.std()\n"
    "    tstat   = ic_mean / (ic_std / np.sqrt(n)) if ic_std > 0 else 0\n"
    "    pval    = 2 * (1 - __import__('scipy').stats.norm.cdf(abs(tstat)))\n"
    "    ic_pos  = (ics > 0).mean()\n"
    "    return {'label': label, 'n': n, 'ic_mean': ic_mean, 'ic_std': ic_std,\n"
    "            'tstat': tstat, 'pval': pval, 'ic_pos': ic_pos}\n"
    "\n"
    "\n"
    "# Overall IC comparison\n"
    "stats_all = [\n"
    "    ic_stats(res_macro, 'Macro-only (NB13)'),\n"
    "    ic_stats(res_nlp,   'Macro + NLP'),\n"
    "]\n"
    "\n"
    "# NLP-era IC comparison (2020+)\n"
    "era_mask  = res_macro.index >= NLP_ERA_START\n"
    "stats_era = [\n"
    "    ic_stats(res_macro[era_mask], 'Macro-only [NLP era]'),\n"
    "    ic_stats(res_nlp[era_mask],   'Macro+NLP  [NLP era]'),\n"
    "]\n"
    "\n"
    "print('IC Analysis — Full Period')\n"
    "print('=' * 60)\n"
    "print(f'{\"Model\":<28} {\"IC mean\":>8} {\"IC std\":>8} {\"t-stat\":>8} {\"p\":>8} {\"IC+%\":>7}')\n"
    "print('-' * 60)\n"
    "for s in stats_all:\n"
    "    sig = '*' if s['pval'] < 0.05 else ''\n"
    "    print(f\"{s['label']:<28} {s['ic_mean']:>+8.4f} {s['ic_std']:>8.4f} \"\n"
    "          f\"{s['tstat']:>8.3f} {s['pval']:>8.4f}{sig} {s['ic_pos']:>6.1%}\")\n"
    "\n"
    "print()\n"
    "print(f'IC Analysis — NLP Era ({NLP_ERA_START.year}+)')\n"
    "print('=' * 60)\n"
    "print(f'{\"Model\":<28} {\"IC mean\":>8} {\"IC std\":>8} {\"t-stat\":>8} {\"p\":>8} {\"IC+%\":>7}')\n"
    "print('-' * 60)\n"
    "for s in stats_era:\n"
    "    sig = '*' if s['pval'] < 0.05 else ''\n"
    "    print(f\"{s['label']:<28} {s['ic_mean']:>+8.4f} {s['ic_std']:>8.4f} \"\n"
    "          f\"{s['tstat']:>8.3f} {s['pval']:>8.4f}{sig} {s['ic_pos']:>6.1%}\")\n"
    "\n"
    "# Rolling IC plot\n"
    "fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)\n"
    "\n"
    "roll26 = lambda s: s.rolling(26, min_periods=10).mean()\n"
    "\n"
    "ax = axes[0]\n"
    "ax.plot(roll26(res_macro['ic']), lw=1.5, label='Macro-only', color='steelblue')\n"
    "ax.plot(roll26(res_nlp['ic']),   lw=1.5, label='Macro+NLP',  color='darkorange')\n"
    "ax.axhline(0,  ls='--', color='gray', lw=0.8)\n"
    "ax.axhline(0.05, ls=':', color='green', lw=0.8, label='IC=0.05 target')\n"
    "ax.axvline(NLP_ERA_START, ls='--', color='purple', lw=0.8, label='NLP era start')\n"
    "ax.set_title('26-Week Rolling IC — Macro vs Macro+NLP')\n"
    "ax.set_ylabel('Spearman IC')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_ylim(-0.5, 0.5)\n"
    "\n"
    "ax2 = axes[1]\n"
    "ic_diff = res_nlp['ic'] - res_macro['ic']\n"
    "ax2.bar(ic_diff.index, roll26(ic_diff), color=ic_diff.apply(\n"
    "    lambda x: 'darkorange' if x > 0 else 'steelblue'), alpha=0.6, width=7)\n"
    "ax2.axhline(0, ls='--', color='gray', lw=0.8)\n"
    "ax2.axvline(NLP_ERA_START, ls='--', color='purple', lw=0.8)\n"
    "ax2.set_title('IC Uplift from NLP (26w Rolling): +NLP minus macro-only')\n"
    "ax2.set_ylabel('IC Difference')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'nlp_ic_comparison.png', dpi=110, bbox_inches='tight')\n"
    "plt.show()\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 7 — Backtest Comparison"))

cells.append(code(
    "def perf_stats(ret_series, label):\n"
    "    r = ret_series.dropna()\n"
    "    ann_ret = r.mean() * 52\n"
    "    ann_vol = r.std()  * np.sqrt(52)\n"
    "    sharpe  = ann_ret / ann_vol if ann_vol > 0 else 0\n"
    "    cum     = (1 + r).cumprod()\n"
    "    maxdd   = (cum / cum.cummax() - 1).min()\n"
    "    winrate = (r > 0).mean()\n"
    "    return {'label': label, 'ann_ret': ann_ret, 'ann_vol': ann_vol,\n"
    "            'sharpe': sharpe, 'max_dd': maxdd, 'winrate': winrate}\n"
    "\n"
    "\n"
    "# Equal-weight benchmark\n"
    "ew_ret = sector_df.loc[res_macro.index].mean(axis=1)\n"
    "\n"
    "rows = [\n"
    "    perf_stats(res_macro['gross_ret'],  'Macro-only (gross)'),\n"
    "    perf_stats(res_macro['net_ret'],    'Macro-only (net TC)'),\n"
    "    perf_stats(res_nlp['gross_ret'],    'Macro+NLP  (gross)'),\n"
    "    perf_stats(res_nlp['net_ret'],      'Macro+NLP  (net TC)'),\n"
    "    perf_stats(ew_ret,                  'Equal-Weight B&H'),\n"
    "]\n"
    "\n"
    "print(f'{\"Strategy\":<28} {\"AnnRet\":>8} {\"AnnVol\":>8} {\"Sharpe\":>8} {\"MaxDD\":>8} {\"WinRate\":>8}')\n"
    "print('-' * 70)\n"
    "for r in rows:\n"
    "    print(f\"{r['label']:<28} {r['ann_ret']:>7.2%} {r['ann_vol']:>8.2%} \"\n"
    "          f\"{r['sharpe']:>8.2f} {r['max_dd']:>8.2%} {r['winrate']:>8.2%}\")\n"
    "\n"
    "# NLP era comparison\n"
    "print(f'\\nNLP Era ({NLP_ERA_START.year}+) Comparison:')\n"
    "print('-' * 70)\n"
    "era_rows = [\n"
    "    perf_stats(res_macro.loc[era_mask, 'net_ret'], 'Macro-only (net TC) [era]'),\n"
    "    perf_stats(res_nlp.loc[era_mask,   'net_ret'], 'Macro+NLP  (net TC) [era]'),\n"
    "]\n"
    "for r in era_rows:\n"
    "    print(f\"{r['label']:<28} {r['ann_ret']:>7.2%} {r['ann_vol']:>8.2%} \"\n"
    "          f\"{r['sharpe']:>8.2f} {r['max_dd']:>8.2%} {r['winrate']:>8.2%}\")\n"
))

cells.append(code(
    "# Equity curve comparison\n"
    "fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)\n"
    "\n"
    "ax = axes[0]\n"
    "for ret, label, color in [\n"
    "    (res_macro['net_ret'], 'Macro-only (net TC)', 'steelblue'),\n"
    "    (res_nlp['net_ret'],   'Macro+NLP  (net TC)', 'darkorange'),\n"
    "    (ew_ret,               'Equal-Weight B&H',    'gray'),\n"
    "]:\n"
    "    cum = (1 + ret.dropna()).cumprod()\n"
    "    ax.plot(cum, lw=1.5, label=label, color=color)\n"
    "\n"
    "ax.axvline(NLP_ERA_START, ls='--', color='purple', lw=0.8, label='NLP era start')\n"
    "ax.axhline(1, ls='--', color='gray', lw=0.6)\n"
    "ax.set_title('Equity Curve: Macro vs Macro+NLP (net of TC)')\n"
    "ax.set_ylabel('Portfolio Value')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_yscale('log')\n"
    "\n"
    "ax2 = axes[1]\n"
    "diff_net = res_nlp['net_ret'] - res_macro['net_ret']\n"
    "diff_cum = (1 + diff_net.dropna()).cumprod() - 1\n"
    "ax2.fill_between(diff_cum.index, 0, diff_cum,\n"
    "                 where=diff_cum >= 0, alpha=0.5, color='darkorange', label='NLP helps')\n"
    "ax2.fill_between(diff_cum.index, 0, diff_cum,\n"
    "                 where=diff_cum < 0,  alpha=0.5, color='steelblue',  label='NLP hurts')\n"
    "ax2.axhline(0, ls='--', color='gray', lw=0.8)\n"
    "ax2.axvline(NLP_ERA_START, ls='--', color='purple', lw=0.8)\n"
    "ax2.set_title('Cumulative Alpha from Adding NLP (macro+NLP minus macro-only)')\n"
    "ax2.set_ylabel('Cumulative Difference')\n"
    "ax2.legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'nlp_equity.png', dpi=110, bbox_inches='tight')\n"
    "plt.show()\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 8 — NLP Feature Importance"))

cells.append(code(
    "# Permutation IC importance: shuffle one NLP feature at a time\n"
    "# Use the NLP-era test data only (where NLP has meaningful coverage)\n"
    "\n"
    "from sklearn.base import clone\n"
    "\n"
    "def permutation_ic_importance(panel, features, era_start, n_repeats=5,\n"
    "                               min_train=156, fold_size=52):\n"
    "    dates  = sorted(panel['date'].unique())\n"
    "    n      = len(dates)\n"
    "    feats  = [f for f in features if f in panel.columns]\n"
    "    era_dt = pd.Timestamp(era_start)\n"
    "\n"
    "    # Only score the last fold that falls in NLP era\n"
    "    results = {}  # feat -> list of ic_drop\n"
    "\n"
    "    t = min_train\n"
    "    fold_results = []\n"
    "    while t + fold_size <= n:\n"
    "        train_d = dates[:t]\n"
    "        test_d  = dates[t:t + fold_size]\n"
    "        if pd.Timestamp(test_d[0]) < era_dt:\n"
    "            t += fold_size\n"
    "            continue\n"
    "\n"
    "        train = panel[panel['date'].isin(train_d)]\n"
    "        test  = panel[panel['date'].isin(test_d)]\n"
    "        medians = train[feats].median()\n"
    "\n"
    "        Xtr = train[feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "        Xte = test[feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "        ytr = train['fwd_excess'].values\n"
    "        yte = test['fwd_excess'].values\n"
    "\n"
    "        m = make_xgb(); m.fit(Xtr, ytr)\n"
    "        base_pred = m.predict(Xte)\n"
    "        base_ic   = spearmanr(base_pred, yte).statistic\n"
    "\n"
    "        fold_imp = {}\n"
    "        for fi, feat in enumerate(feats):\n"
    "            drops = []\n"
    "            for _ in range(n_repeats):\n"
    "                Xte_perm = Xte.copy()\n"
    "                Xte_perm[:, fi] = np.random.permutation(Xte_perm[:, fi])\n"
    "                perm_ic = spearmanr(m.predict(Xte_perm), yte).statistic\n"
    "                drops.append(base_ic - perm_ic)  # positive = feature helps\n"
    "            fold_imp[feat] = np.mean(drops)\n"
    "\n"
    "        fold_results.append(fold_imp)\n"
    "        t += fold_size\n"
    "\n"
    "    if not fold_results:\n"
    "        return {}\n"
    "    all_imps = pd.DataFrame(fold_results).mean()\n"
    "    return all_imps.sort_values(ascending=False)\n"
    "\n"
    "\n"
    "print('Computing permutation importance on NLP era folds...')\n"
    "importance = permutation_ic_importance(panel, ALL_FEATS, NLP_ERA_START)\n"
    "\n"
    "if isinstance(importance, pd.Series) and len(importance) > 0:\n"
    "    top20 = importance.head(20)\n"
    "    print(f'\\nTop 20 features by IC drop:')\n"
    "    for feat, val in top20.items():\n"
    "        ftype = 'NLP' if any(s+'_' in feat for s in ['BANK','ENERGY','ICT',\n"
    "                             'COMMERCE','HEALTH','PROPERTY','FOOD']) else 'MACRO'\n"
    "        print(f'  {feat:<30} {val:>+.4f}  [{ftype}]')\n"
    "\n"
    "    # Plot top-20\n"
    "    colors = ['darkorange' if any(s+'_' in f for s in ['BANK','ENERGY','ICT',\n"
    "               'COMMERCE','HEALTH','PROPERTY','FOOD']) else 'steelblue'\n"
    "               for f in top20.index]\n"
    "    fig, ax = plt.subplots(figsize=(10, 6))\n"
    "    bars = ax.barh(range(len(top20)), top20.values[::-1], color=colors[::-1])\n"
    "    ax.set_yticks(range(len(top20)))\n"
    "    ax.set_yticklabels(top20.index[::-1], fontsize=9)\n"
    "    ax.axvline(0, color='gray', lw=0.8)\n"
    "    ax.set_xlabel('IC Drop when Permuted (higher = more important)')\n"
    "    ax.set_title('Feature Importance (NLP Era) — Orange=NLP, Blue=Macro/Sector')\n"
    "    from matplotlib.patches import Patch\n"
    "    ax.legend(handles=[\n"
    "        Patch(color='darkorange', label='NLP features'),\n"
    "        Patch(color='steelblue',  label='Macro/Sector features'),\n"
    "    ], loc='lower right', fontsize=9)\n"
    "    plt.tight_layout()\n"
    "    plt.savefig(FIGS / 'nlp_importance.png', dpi=110, bbox_inches='tight')\n"
    "    plt.show()\n"
    "else:\n"
    "    print('No NLP-era folds found — skipping importance analysis.')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 9 — Sector Sentiment Signal Analysis"))

cells.append(code(
    "# IC of raw sector sentiment vs forward excess return (by sector)\n"
    "print('Sector-level sentiment IC vs forward excess return:')\n"
    "print(f'{\"Sector\":<12} {\"Feature\":<22} {\"IC\":>8} {\"p\":>8} {\"N\":>6}')\n"
    "print('-' * 60)\n"
    "\n"
    "for sec in SECTORS:\n"
    "    feat = f'{sec}_sent_lag1'\n"
    "    if feat not in panel.columns:\n"
    "        continue\n"
    "    sub = panel[panel['sector'] == sec][[feat, 'fwd_excess']].dropna()\n"
    "    if len(sub) < 20:\n"
    "        print(f'  {sec:<12} {feat:<22} too few observations ({len(sub)})')\n"
    "        continue\n"
    "    ic, pval = spearmanr(sub[feat], sub['fwd_excess'])\n"
    "    sig = '*' if pval < 0.05 else ''\n"
    "    print(f'  {sec:<12} {feat:<22} {ic:>+8.4f} {pval:>8.4f}{sig} {len(sub):>6}')\n"
    "\n"
    "print()\n"
    "print('Cross-sectional relative sentiment IC vs forward excess:')\n"
    "rel_feats = [f for f in panel.columns if f.endswith('_sent_rel')]\n"
    "if rel_feats:\n"
    "    sub = panel[rel_feats + ['fwd_excess']].dropna()\n"
    "    # Flatten: stack sector relative sentiments\n"
    "    sent_stack = []\n"
    "    for sec in SECTORS:\n"
    "        rf = f'{sec}_sent_rel'\n"
    "        if rf not in panel.columns:\n"
    "            continue\n"
    "        tmp = panel[panel['sector'] == sec][[rf, 'fwd_excess']].dropna()\n"
    "        tmp.columns = ['sent_rel', 'fwd_excess']\n"
    "        sent_stack.append(tmp)\n"
    "    if sent_stack:\n"
    "        stacked = pd.concat(sent_stack)\n"
    "        ic, pval = spearmanr(stacked['sent_rel'], stacked['fwd_excess'])\n"
    "        print(f'  Cross-sectional sent_rel IC: {ic:+.4f}  (p={pval:.4f})')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
cells.append(md("## Section 10 — Final Verdict"))

cells.append(code(
    "import scipy.stats as sps\n"
    "\n"
    "# Full-period and NLP-era stats\n"
    "mac_full  = ic_stats(res_macro,          'Macro-only full')\n"
    "nlp_full  = ic_stats(res_nlp,            'NLP full')\n"
    "mac_era   = ic_stats(res_macro[era_mask],'Macro-only NLP era')\n"
    "nlp_era_s = ic_stats(res_nlp[era_mask],  'NLP NLP era')\n"
    "\n"
    "nlp_perf_gross = perf_stats(res_nlp['gross_ret'], 'NLP gross')\n"
    "nlp_perf_net   = perf_stats(res_nlp['net_ret'],   'NLP net')\n"
    "nlp_era_net    = perf_stats(res_nlp.loc[era_mask,'net_ret'], 'NLP era net')\n"
    "mac_era_net    = perf_stats(res_macro.loc[era_mask,'net_ret'],'Mac era net')\n"
    "\n"
    "ic_uplift = nlp_full['ic_mean'] - mac_full['ic_mean']\n"
    "ic_uplift_era = nlp_era_s['ic_mean'] - mac_era['ic_mean']\n"
    "\n"
    "evidence = [\n"
    "    ('IC mean > 0.05 (NLP)',            nlp_full['ic_mean'],     0.05,   '>', True),\n"
    "    ('NLP IC > Macro IC (full)',         ic_uplift,               0,      '>', True),\n"
    "    ('NLP IC significant (p<0.05)',      nlp_full['pval'],        0.05,   '<', False),\n"
    "    ('NLP IC uplift in NLP era',         ic_uplift_era,           0,      '>', True),\n"
    "    ('Sharpe net TC > 0 (full)',         nlp_perf_net['sharpe'],  0,      '>', True),\n"
    "    ('Sharpe net TC > Macro (NLP era)',  nlp_era_net['sharpe'] - mac_era_net['sharpe'], 0, '>', True),\n"
    "    ('Annual return net > 0%',           nlp_perf_net['ann_ret'], 0,      '>', True),\n"
    "    ('NLP-era ann ret > Macro era',      nlp_era_net['ann_ret'] - mac_era_net['ann_ret'], 0, '>', True),\n"
    "    ('Max DD (net) > -50%',              nlp_perf_net['max_dd'], -0.50,   '>', True),\n"
    "]\n"
    "\n"
    "score = 0\n"
    "print('='*70)\n"
    "print('SECTOR NLP ALPHA VERDICT')\n"
    "print('='*70)\n"
    "print(f'{\"Evidence\":<42} {\"Value\":>12}  {\"Threshold\":>10}')\n"
    "print('-'*70)\n"
    "for desc, val, thr, op, higher_better in evidence:\n"
    "    passed = (val > thr) if op == '>' else (val < thr)\n"
    "    mark   = '[+]' if passed else '[-]'\n"
    "    score += passed\n"
    "    if isinstance(val, float) and abs(val) < 1:\n"
    "        print(f'{mark} {desc:<40} {val:>+12.4f}  {op}{thr:>9.4f}')\n"
    "    else:\n"
    "        print(f'{mark} {desc:<40} {val:>+12.2%}  {op}{thr:>9.2%}')\n"
    "\n"
    "print(f'\\nScore: {score}/{len(evidence)}')\n"
    "print()\n"
    "print('='*70)\n"
    "if score >= 6:\n"
    "    print('VERDICT: NLP ADDS MEANINGFUL SIGNAL')\n"
    "    print('Sector NLP improves IC and/or Sharpe. Worth deploying in production.')\n"
    "elif score >= 4:\n"
    "    print('VERDICT: NLP ADDS MARGINAL SIGNAL')\n"
    "    print('NLP shows some uplift but not consistent. Needs more news coverage.')\n"
    "else:\n"
    "    print('VERDICT: NLP DOES NOT ADD MEANINGFUL SIGNAL')\n"
    "    print('Sector NLP insufficient. TC still dominates. Need denser news history.')\n"
    "print('='*70)\n"
    "\n"
    "print(f'\\nKey metrics summary:')\n"
    "print(f'  Macro IC mean (full):     {mac_full[\"ic_mean\"]:+.4f}')\n"
    "print(f'  NLP IC mean (full):       {nlp_full[\"ic_mean\"]:+.4f}')\n"
    "print(f'  IC Uplift:                {ic_uplift:+.4f}')\n"
    "print(f'  Macro IC mean (NLP era):  {mac_era[\"ic_mean\"]:+.4f}')\n"
    "print(f'  NLP IC mean (NLP era):    {nlp_era_s[\"ic_mean\"]:+.4f}')\n"
    "print(f'  IC Uplift (NLP era):      {ic_uplift_era:+.4f}')\n"
    "print(f'  NLP Sharpe net (full):    {nlp_perf_net[\"sharpe\"]:+.2f}')\n"
    "print(f'  NLP Sharpe net (era):     {nlp_era_net[\"sharpe\"]:+.2f}')\n"
    "print(f'  Macro Sharpe net (era):   {mac_era_net[\"sharpe\"]:+.2f}')\n"
))

# ──────────────────────────────────────────────────────────────────────────────
OUT.parent.mkdir(parents=True, exist_ok=True)
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

with open(OUT, "w") as f:
    json.dump(nb, f, indent=1)

print(f"Generated: {OUT}")
print(f"Cells: {len(cells)}")
