"""
gen_nb15_low_tc_sector.py -- generate notebooks/eda/15_low_tc_sector.ipynb

Tests two fixes for the TC-drag problem found in NB13:
  B1a: Monthly rebalancing (every 4 weeks) — reduces TC from ~21%/yr to ~5%/yr
  B1b: Threshold rebalancing (only trade when positions actually change)
  B2:  Long-only rotation (top-2 sectors, no short) — halves TC, removes short risk
Final section: side-by-side comparison vs NB13 baseline.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '15_low_tc_sector.ipynb'

def md(source): return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

cells = []

# ── Title ─────────────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 15 — Low-TC Sector Rotation\n\n"
    "> *Can reducing transaction costs rescue the sector rotation signal from NB13?*\n\n"
    "**Problem:** NB13 found gross Sharpe = +0.69 but net-of-TC Sharpe = -1.74.  \n"
    "TC drag = 4 positions × 0.1% × 52 rebalances = **~20.8%/yr** — kills everything.\n\n"
    "**Two fixes tested here:**\n\n"
    "| Variant | Description | Expected TC/yr |\n"
    "|---------|-------------|----------------|\n"
    "| **B1a** Monthly rebalance | Rebalance every 4 weeks | ~5.2% |\n"
    "| **B1b** Threshold rebalance | Only trade when top-k changes | ~3–8% |\n"
    "| **B2** Long-only | Long top-2 only (no short) | ~10.4% |\n\n"
    "| Section | Description |\n"
    "|---------|-------------|\n"
    "| 1. Setup | Data + features (same pipeline as NB13) |\n"
    "| 2. Baseline | Reproduce NB13 XGB-Reg weekly L/S |\n"
    "| 3. B1a | Monthly rebalancing |\n"
    "| 4. B1b | Threshold rebalancing |\n"
    "| 5. B2 | Long-only rotation |\n"
    "| 6. Comparison | Side-by-side metrics + equity curves |\n"
    "| 7. Verdict | Is any variant viable? |"
))

# ── Section 1 — Setup & Data ───────────────────────────────────────────────────
cells.append(md("---\n## Section 1 — Setup & Data"))

cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "from scipy.stats import spearmanr, ttest_1samp\n"
    "from xgboost import XGBRegressor\n"
    "warnings.filterwarnings('ignore')\n"
    "np.random.seed(42)\n\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n\n"
    "SECTORS   = ['BANK','ENERGY','ICT','COMMERCE','HEALTH','PROPERTY','FOOD']\n"
    "TC        = 0.001   # 0.1% one-way\n"
    "MIN_TRAIN = 156     # 3 years\n"
    "FOLD_SIZE = 52      # 1 year\n"
    "LONG_K    = 2\n"
    "SHORT_K   = 2\n\n"
    "# Load sector returns\n"
    "sector_raw = pd.read_csv(PROC / 'sector_weekly.csv', index_col=0, parse_dates=True)\n"
    "sector_raw = sector_raw[SECTORS]\n"
    "sector_raw.index = sector_raw.index.normalize()\n\n"
    "# Load macro features\n"
    "macro = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "macro.index = macro.index.normalize()\n\n"
    "MACRO_FEATS = [\n"
    "    'sp500_ret_w', 'sp500_rvol_4w', 'sp500_ret_d_lag1',\n"
    "    'eem_ret_d_lag1', 'oil_ret_w', 'oil_ret_d_lag1',\n"
    "    'gold_ret_w', 'gold_rvol_4w',\n"
    "    'dxy_ret_w', 'dxy_ret_d_lag1',\n"
    "    'us_10yr_treasury_ret_w', 'us_2yr_treasury_ret_w',\n"
    "    'vix_z', 'regime', 'yield_curve_slope',\n"
    "    'SET_index_ret_w', 'SET_index_rvol_4w',\n"
    "]\n"
    "MACRO_FEATS = [f for f in MACRO_FEATS if f in macro.columns]\n\n"
    "macro_feats = macro[MACRO_FEATS].copy()\n"
    "common_dates = sector_raw.index.intersection(macro_feats.index)\n"
    "sector = sector_raw.loc[common_dates]\n"
    "macro_feats = macro_feats.loc[common_dates]\n"
    "print(f'Sector: {sector.shape}, Macro: {macro_feats.shape}')\n"
    "print(f'Date range: {common_dates[0].date()} -> {common_dates[-1].date()}')"
))

# ── Section 1b — Feature Engineering ──────────────────────────────────────────
cells.append(md("### Feature Engineering (Panel)"))

cells.append(code(
    "SECTOR_FEATS = ['mom1','mom4','mom12','mom26','rvol4','rvol12',\n"
    "                'mom1_rank','mom4_rank','mom12_rank','mom1_rel','mom4_rel']\n"
    "ALL_FEATS = SECTOR_FEATS + MACRO_FEATS\n\n"
    "def build_panel(sector_df, macro_df):\n"
    "    mom1   = sector_df.shift(1)\n"
    "    mom4   = sector_df.shift(1).rolling(4).mean()\n"
    "    mom12  = sector_df.shift(1).rolling(12).mean()\n"
    "    mom26  = sector_df.shift(1).rolling(26).mean()\n"
    "    rvol4  = sector_df.shift(1).rolling(4).std()\n"
    "    rvol12 = sector_df.shift(1).rolling(12).std()\n"
    "    mom1_rank  = mom1.rank(axis=1, pct=True) - 0.5\n"
    "    mom4_rank  = mom4.rank(axis=1, pct=True) - 0.5\n"
    "    mom12_rank = mom12.rank(axis=1, pct=True) - 0.5\n"
    "    mom1_rel   = mom1.subtract(mom1.median(axis=1), axis=0)\n"
    "    mom4_rel   = mom4.subtract(mom4.median(axis=1), axis=0)\n"
    "    fwd_ret    = sector_df.shift(-1)\n\n"
    "    records = []\n"
    "    for date in sector_df.index:\n"
    "        if date not in macro_df.index:\n"
    "            continue\n"
    "        macro_row = macro_df.loc[date]\n"
    "        mkt_fwd = fwd_ret.loc[date].mean(skipna=True)\n"
    "        for sec in sector_df.columns:\n"
    "            row = {\n"
    "                'date': date, 'sector': sec,\n"
    "                'fwd_ret':    fwd_ret.loc[date, sec],\n"
    "                'fwd_excess': fwd_ret.loc[date, sec] - mkt_fwd,\n"
    "                'mom1':       mom1.loc[date, sec],\n"
    "                'mom4':       mom4.loc[date, sec],\n"
    "                'mom12':      mom12.loc[date, sec],\n"
    "                'mom26':      mom26.loc[date, sec],\n"
    "                'rvol4':      rvol4.loc[date, sec],\n"
    "                'rvol12':     rvol12.loc[date, sec],\n"
    "                'mom1_rank':  mom1_rank.loc[date, sec],\n"
    "                'mom4_rank':  mom4_rank.loc[date, sec],\n"
    "                'mom12_rank': mom12_rank.loc[date, sec],\n"
    "                'mom1_rel':   mom1_rel.loc[date, sec],\n"
    "                'mom4_rel':   mom4_rel.loc[date, sec],\n"
    "            }\n"
    "            for col in macro_df.columns:\n"
    "                row[col] = macro_row[col] if col in macro_row.index else np.nan\n"
    "            records.append(row)\n"
    "    panel = pd.DataFrame(records)\n"
    "    panel['date'] = pd.to_datetime(panel['date'])\n"
    "    return panel.sort_values(['date','sector']).reset_index(drop=True)\n\n"
    "panel = build_panel(sector, macro_feats)\n"
    "panel_clean = panel.dropna(subset=['fwd_excess']).copy()\n"
    "dates_all = sorted(panel_clean['date'].unique())\n"
    "print(f'Panel: {len(panel_clean)} rows, {len(dates_all)} dates, {len(ALL_FEATS)} features')"
))

# ── Section 2 — Baseline (NB13 weekly L/S) ────────────────────────────────────
cells.append(md("---\n## Section 2 — Baseline: Weekly Rebalancing L/S (NB13)"))

cells.append(code(
    "def make_xgb():\n"
    "    return XGBRegressor(\n"
    "        n_estimators=100, max_depth=3, learning_rate=0.05,\n"
    "        subsample=0.7, colsample_bytree=0.6,\n"
    "        min_child_weight=10, reg_alpha=0.5, reg_lambda=5.0,\n"
    "        random_state=42, verbosity=0, n_jobs=1\n"
    "    )\n\n"
    "def risk_metrics(rets, freq=52):\n"
    "    r = pd.Series(rets).dropna()\n"
    "    if len(r) < 10: return {}\n"
    "    ann_ret = (1+r).prod()**(freq/len(r)) - 1\n"
    "    ann_vol = r.std() * np.sqrt(freq)\n"
    "    sharpe  = ann_ret / ann_vol if ann_vol > 0 else np.nan\n"
    "    cum = (1+r).cumprod()\n"
    "    max_dd = ((cum - cum.cummax()) / cum.cummax()).min()\n"
    "    return {'ann_ret':ann_ret,'ann_vol':ann_vol,'sharpe':sharpe,\n"
    "            'max_dd':max_dd,'win_rate':(r>0).mean(),'n':len(r)}\n\n"
    "def ic_summary(ic_series):\n"
    "    ics = ic_series.dropna()\n"
    "    if len(ics) < 10: return {}\n"
    "    t, p = ttest_1samp(ics, 0)\n"
    "    icir = ics.mean() / ics.std() * np.sqrt(len(ics)) if ics.std() > 0 else np.nan\n"
    "    return {'ic_mean':ics.mean(),'icir':icir,'ic_pos':(ics>0).mean(),'p':p}\n\n"
    "# ── Walk-forward: weekly L/S (baseline) ──\n"
    "def wf_weekly_ls(panel_df, features, long_k=2, short_k=2):\n"
    "    dates = sorted(panel_df['date'].unique())\n"
    "    n = len(dates)\n"
    "    records = []\n"
    "    t = MIN_TRAIN\n"
    "    while t + FOLD_SIZE <= n:\n"
    "        train = panel_df[panel_df['date'].isin(dates[:t])]\n"
    "        test  = panel_df[panel_df['date'].isin(dates[t:t+FOLD_SIZE])]\n"
    "        medians = train[features].median()\n"
    "        Xtr = train[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "        m = make_xgb(); m.fit(Xtr, train['fwd_excess'].values)\n"
    "        for date, grp in test.groupby('date'):\n"
    "            if len(grp) < 3: continue\n"
    "            Xte = grp[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "            grp = grp.copy()\n"
    "            grp['pred'] = m.predict(Xte)\n"
    "            s = grp.sort_values('pred', ascending=False)\n"
    "            long_r  = s.head(long_k)['fwd_ret'].mean()\n"
    "            short_r = s.tail(short_k)['fwd_ret'].mean()\n"
    "            port_r  = (long_r - short_r) / 2\n"
    "            ic = float(spearmanr(grp['pred'], grp['fwd_excess'])[0]) if len(grp)>=4 else np.nan\n"
    "            records.append({'date':date,'gross_ret':port_r,\n"
    "                            'net_ret':port_r - (long_k+short_k)*TC,\n"
    "                            'mkt_ret':grp['fwd_ret'].mean(), 'ic':ic})\n"
    "        t += FOLD_SIZE\n"
    "    return pd.DataFrame(records).set_index('date').sort_index()\n\n"
    "print('Running baseline (weekly L/S)...')\n"
    "res_base = wf_weekly_ls(panel_clean, ALL_FEATS)\n"
    "m_base = risk_metrics(res_base['net_ret'])\n"
    "ic_base = ic_summary(res_base['ic'])\n"
    "print(f'Baseline  gross Sharpe: {risk_metrics(res_base[\"gross_ret\"])[\"sharpe\"]:+.3f}')\n"
    "print(f'Baseline  net   Sharpe: {m_base[\"sharpe\"]:+.3f}  (IC mean={ic_base[\"ic_mean\"]:+.4f}, p={ic_base[\"p\"]:.4f})')"
))

# ── Section 3 — B1a: Monthly Rebalancing ──────────────────────────────────────
cells.append(md(
    "---\n## Section 3 — B1a: Monthly Rebalancing\n\n"
    "Rebalance every **4 weeks** instead of every week.  \n"
    "TC per year: 4 positions × 0.1% × 13 rebalances = **5.2%/yr** (was 20.8%)."
))

cells.append(code(
    "def wf_monthly_ls(panel_df, features, rebal_freq=4, long_k=2, short_k=2):\n"
    "    \"\"\"Walk-forward L/S that only rebalances every rebal_freq weeks.\"\"\"\n"
    "    dates = sorted(panel_df['date'].unique())\n"
    "    n = len(dates)\n"
    "    records = []\n"
    "    t = MIN_TRAIN\n"
    "    while t + FOLD_SIZE <= n:\n"
    "        train = panel_df[panel_df['date'].isin(dates[:t])]\n"
    "        test_dates = dates[t:t+FOLD_SIZE]\n"
    "        test  = panel_df[panel_df['date'].isin(test_dates)]\n"
    "        medians = train[features].median()\n"
    "        Xtr = train[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "        m = make_xgb(); m.fit(Xtr, train['fwd_excess'].values)\n\n"
    "        current_longs  = []\n"
    "        current_shorts = []\n"
    "        for i, date in enumerate(test_dates):\n"
    "            grp = test[test['date'] == date]\n"
    "            if len(grp) < 3: continue\n"
    "            Xte = grp[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "            grp = grp.copy(); grp['pred'] = m.predict(Xte)\n"
    "            s = grp.sort_values('pred', ascending=False)\n\n"
    "            rebalanced = (i % rebal_freq == 0) or (not current_longs)\n"
    "            if rebalanced:\n"
    "                current_longs  = s.head(long_k)['sector'].tolist()\n"
    "                current_shorts = s.tail(short_k)['sector'].tolist()\n"
    "                tc_cost = (long_k + short_k) * TC\n"
    "            else:\n"
    "                tc_cost = 0.0\n\n"
    "            long_r  = grp[grp['sector'].isin(current_longs)]['fwd_ret'].mean()\n"
    "            short_r = grp[grp['sector'].isin(current_shorts)]['fwd_ret'].mean()\n"
    "            port_r  = (long_r - short_r) / 2\n"
    "            ic = float(spearmanr(grp['pred'], grp['fwd_excess'])[0]) if len(grp)>=4 else np.nan\n"
    "            records.append({'date':date,'gross_ret':port_r,\n"
    "                            'net_ret':port_r - tc_cost,\n"
    "                            'mkt_ret':grp['fwd_ret'].mean(),'ic':ic,\n"
    "                            'rebalanced':rebalanced})\n"
    "        t += FOLD_SIZE\n"
    "    return pd.DataFrame(records).set_index('date').sort_index()\n\n"
    "print('Running B1a (monthly rebalancing, every 4w)...')\n"
    "res_b1a = wf_monthly_ls(panel_clean, ALL_FEATS, rebal_freq=4)\n"
    "m_b1a = risk_metrics(res_b1a['net_ret'])\n"
    "ic_b1a = ic_summary(res_b1a['ic'])\n"
    "rebal_freq_b1a = res_b1a['rebalanced'].mean()\n"
    "print(f'B1a rebalance rate: {rebal_freq_b1a:.1%} of weeks')\n"
    "print(f'B1a  gross Sharpe: {risk_metrics(res_b1a[\"gross_ret\"])[\"sharpe\"]:+.3f}')\n"
    "print(f'B1a  net   Sharpe: {m_b1a[\"sharpe\"]:+.3f}  (IC mean={ic_b1a[\"ic_mean\"]:+.4f}, p={ic_b1a[\"p\"]:.4f})')\n\n"
    "# Also test 8-week (bi-monthly) rebalancing\n"
    "print('Running B1a-8w (bi-monthly rebalancing, every 8w)...')\n"
    "res_b1a_8 = wf_monthly_ls(panel_clean, ALL_FEATS, rebal_freq=8)\n"
    "m_b1a_8 = risk_metrics(res_b1a_8['net_ret'])\n"
    "print(f'B1a-8w gross Sharpe: {risk_metrics(res_b1a_8[\"gross_ret\"])[\"sharpe\"]:+.3f}')\n"
    "print(f'B1a-8w net   Sharpe: {m_b1a_8[\"sharpe\"]:+.3f}')"
))

# ── Section 4 — B1b: Threshold Rebalancing ────────────────────────────────────
cells.append(md(
    "---\n## Section 4 — B1b: Threshold Rebalancing\n\n"
    "Only rebalance when the **top-k set actually changes** (at least 1 new sector enters).  \n"
    "This naturally reduces turnover when the model is confident/stable."
))

cells.append(code(
    "def wf_threshold_ls(panel_df, features, long_k=2, short_k=2, min_change=1):\n"
    "    \"\"\"\n"
    "    Walk-forward L/S that only trades when top-k positions change.\n"
    "    min_change: minimum number of sectors that must enter/exit to trigger rebalance.\n"
    "    \"\"\"\n"
    "    dates = sorted(panel_df['date'].unique())\n"
    "    n = len(dates)\n"
    "    records = []\n"
    "    t = MIN_TRAIN\n"
    "    while t + FOLD_SIZE <= n:\n"
    "        train = panel_df[panel_df['date'].isin(dates[:t])]\n"
    "        test_dates = dates[t:t+FOLD_SIZE]\n"
    "        test  = panel_df[panel_df['date'].isin(test_dates)]\n"
    "        medians = train[features].median()\n"
    "        Xtr = train[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "        m = make_xgb(); m.fit(Xtr, train['fwd_excess'].values)\n\n"
    "        current_longs  = set()\n"
    "        current_shorts = set()\n"
    "        for date in test_dates:\n"
    "            grp = test[test['date'] == date]\n"
    "            if len(grp) < 3: continue\n"
    "            Xte = grp[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "            grp = grp.copy(); grp['pred'] = m.predict(Xte)\n"
    "            s = grp.sort_values('pred', ascending=False)\n"
    "            new_longs  = set(s.head(long_k)['sector'].tolist())\n"
    "            new_shorts = set(s.tail(short_k)['sector'].tolist())\n\n"
    "            # Count position changes\n"
    "            long_changes  = len(new_longs  - current_longs)\n"
    "            short_changes = len(new_shorts - current_shorts)\n"
    "            total_changes = long_changes + short_changes\n\n"
    "            rebalanced = (total_changes >= min_change) or (not current_longs)\n"
    "            if rebalanced:\n"
    "                current_longs  = new_longs\n"
    "                current_shorts = new_shorts\n"
    "                tc_cost = (long_changes + short_changes) * TC  # pay TC only on changes\n"
    "            else:\n"
    "                tc_cost = 0.0\n\n"
    "            long_r  = grp[grp['sector'].isin(current_longs)]['fwd_ret'].mean()\n"
    "            short_r = grp[grp['sector'].isin(current_shorts)]['fwd_ret'].mean()\n"
    "            port_r  = (long_r - short_r) / 2\n"
    "            ic = float(spearmanr(grp['pred'], grp['fwd_excess'])[0]) if len(grp)>=4 else np.nan\n"
    "            records.append({'date':date,'gross_ret':port_r,\n"
    "                            'net_ret':port_r - tc_cost,\n"
    "                            'mkt_ret':grp['fwd_ret'].mean(),'ic':ic,\n"
    "                            'rebalanced':rebalanced,\n"
    "                            'tc_cost':tc_cost})\n"
    "        t += FOLD_SIZE\n"
    "    return pd.DataFrame(records).set_index('date').sort_index()\n\n"
    "print('Running B1b (threshold rebalancing)...')\n"
    "res_b1b = wf_threshold_ls(panel_clean, ALL_FEATS, min_change=1)\n"
    "m_b1b = risk_metrics(res_b1b['net_ret'])\n"
    "ic_b1b = ic_summary(res_b1b['ic'])\n"
    "rebal_rate_b1b = res_b1b['rebalanced'].mean()\n"
    "avg_tc_b1b = res_b1b['tc_cost'].mean() * 52  # annualised\n"
    "print(f'B1b rebalance rate: {rebal_rate_b1b:.1%} of weeks')\n"
    "print(f'B1b avg TC/yr:      {avg_tc_b1b:.2%}')\n"
    "print(f'B1b  gross Sharpe: {risk_metrics(res_b1b[\"gross_ret\"])[\"sharpe\"]:+.3f}')\n"
    "print(f'B1b  net   Sharpe: {m_b1b[\"sharpe\"]:+.3f}  (IC mean={ic_b1b[\"ic_mean\"]:+.4f}, p={ic_b1b[\"p\"]:.4f})')"
))

# ── Section 5 — B2: Long-Only Rotation ────────────────────────────────────────
cells.append(md(
    "---\n## Section 5 — B2: Long-Only Sector Rotation\n\n"
    "Hold the **top-2 sectors** (equal weight), no short side.  \n"
    "TC per year: 2 positions × 0.1% × 52 = **10.4%/yr**.  \n"
    "Benchmark: equal-weight all-sector portfolio (SET proxy).\n\n"
    "Two sub-variants:\n"
    "- **B2-weekly**: rebalance top-2 every week\n"
    "- **B2-monthly**: rebalance top-2 every 4 weeks"
))

cells.append(code(
    "def wf_longonly(panel_df, features, long_k=2, rebal_freq=1):\n"
    "    \"\"\"\n"
    "    Walk-forward long-only: hold top-k sectors.\n"
    "    Returns: port_ret (long-only), bench_ret (equal-weight all sectors).\n"
    "    \"\"\"\n"
    "    dates = sorted(panel_df['date'].unique())\n"
    "    n = len(dates)\n"
    "    records = []\n"
    "    t = MIN_TRAIN\n"
    "    while t + FOLD_SIZE <= n:\n"
    "        train = panel_df[panel_df['date'].isin(dates[:t])]\n"
    "        test_dates = dates[t:t+FOLD_SIZE]\n"
    "        test  = panel_df[panel_df['date'].isin(test_dates)]\n"
    "        medians = train[features].median()\n"
    "        Xtr = train[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "        m = make_xgb(); m.fit(Xtr, train['fwd_excess'].values)\n\n"
    "        current_longs = []\n"
    "        prev_longs    = []\n"
    "        for i, date in enumerate(test_dates):\n"
    "            grp = test[test['date'] == date]\n"
    "            if len(grp) < 3: continue\n"
    "            Xte = grp[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "            grp = grp.copy(); grp['pred'] = m.predict(Xte)\n"
    "            s = grp.sort_values('pred', ascending=False)\n\n"
    "            rebalanced = (i % rebal_freq == 0) or (not current_longs)\n"
    "            if rebalanced:\n"
    "                prev_longs    = current_longs[:]\n"
    "                current_longs = s.head(long_k)['sector'].tolist()\n"
    "                # TC: only on sectors that changed\n"
    "                changed = len(set(current_longs) - set(prev_longs)) if prev_longs else long_k\n"
    "                tc_cost = changed * TC\n"
    "            else:\n"
    "                tc_cost = 0.0\n\n"
    "            long_r  = grp[grp['sector'].isin(current_longs)]['fwd_ret'].mean()\n"
    "            bench_r = grp['fwd_ret'].mean()   # equal-weight all sectors\n"
    "            ic = float(spearmanr(grp['pred'], grp['fwd_excess'])[0]) if len(grp)>=4 else np.nan\n"
    "            records.append({'date':date,\n"
    "                            'port_ret':long_r,\n"
    "                            'gross_ret':long_r - bench_r,  # excess vs benchmark\n"
    "                            'net_ret':(long_r - bench_r) - tc_cost,\n"
    "                            'bench_ret':bench_r,'ic':ic,\n"
    "                            'rebalanced':rebalanced,'tc_cost':tc_cost})\n"
    "        t += FOLD_SIZE\n"
    "    return pd.DataFrame(records).set_index('date').sort_index()\n\n"
    "print('Running B2-weekly (long-only, weekly rebalance)...')\n"
    "res_b2w = wf_longonly(panel_clean, ALL_FEATS, long_k=2, rebal_freq=1)\n"
    "m_b2w_port  = risk_metrics(res_b2w['port_ret'])  # absolute return\n"
    "m_b2w_bench = risk_metrics(res_b2w['bench_ret'])\n"
    "m_b2w_net   = risk_metrics(res_b2w['net_ret'])   # excess vs bench net of TC\n"
    "print(f'B2-weekly  port  Sharpe (abs):   {m_b2w_port[\"sharpe\"]:+.3f}')\n"
    "print(f'B2-weekly  bench Sharpe (EW):    {m_b2w_bench[\"sharpe\"]:+.3f}')\n"
    "print(f'B2-weekly  excess Sharpe (net):  {m_b2w_net[\"sharpe\"]:+.3f}')\n\n"
    "print('Running B2-monthly (long-only, monthly rebalance)...')\n"
    "res_b2m = wf_longonly(panel_clean, ALL_FEATS, long_k=2, rebal_freq=4)\n"
    "m_b2m_port = risk_metrics(res_b2m['port_ret'])\n"
    "m_b2m_net  = risk_metrics(res_b2m['net_ret'])\n"
    "avg_tc_b2m = res_b2m['tc_cost'].mean() * 52\n"
    "print(f'B2-monthly port  Sharpe (abs):   {m_b2m_port[\"sharpe\"]:+.3f}')\n"
    "print(f'B2-monthly excess Sharpe (net):  {m_b2m_net[\"sharpe\"]:+.3f}')\n"
    "print(f'B2-monthly avg TC/yr:            {avg_tc_b2m:.2%}')"
))

# ── Section 6 — Comparison ────────────────────────────────────────────────────
cells.append(md(
    "---\n## Section 6 — Comparison: All Variants\n\n"
    "Side-by-side metrics and equity curves for all strategies."
))

cells.append(code(
    "# ── Summary table ──\n"
    "bnh = res_base['mkt_ret']  # equal-weight benchmark\n"
    "m_bnh = risk_metrics(bnh)\n\n"
    "rows = [\n"
    "    ('NB13 Baseline (weekly L/S)',  res_base['gross_ret'],  res_base['net_ret'],  'L/S'),\n"
    "    ('B1a Monthly (4w L/S)',        res_b1a['gross_ret'],   res_b1a['net_ret'],   'L/S'),\n"
    "    ('B1a Bi-monthly (8w L/S)',     res_b1a_8['gross_ret'], res_b1a_8['net_ret'], 'L/S'),\n"
    "    ('B1b Threshold (L/S)',         res_b1b['gross_ret'],   res_b1b['net_ret'],   'L/S'),\n"
    "    ('B2 Long-only weekly',         res_b2w['port_ret'],    res_b2w['port_ret'] - res_b2w['tc_cost'], 'LO'),\n"
    "    ('B2 Long-only monthly',        res_b2m['port_ret'],    res_b2m['port_ret'] - res_b2m['tc_cost'], 'LO'),\n"
    "    ('Equal-Weight B&H',            bnh,                    bnh,                  'BNH'),\n"
    "]\n\n"
    "print(f'{\"Strategy\":<32} {\"Type\":>4} {\"AnnRet(gross)\":>14} {\"AnnRet(net)\":>12} {\"Sharpe(net)\":>12} {\"MaxDD\":>8} {\"WinRate\":>8}')\n"
    "print('-' * 96)\n"
    "for name, gross, net, typ in rows:\n"
    "    mg = risk_metrics(gross)\n"
    "    mn = risk_metrics(net)\n"
    "    if not mn: continue\n"
    "    flag = ' ✓' if mn['sharpe'] > 0.3 else ''\n"
    "    print(f'{name:<32} {typ:>4} {mg[\"ann_ret\"]:>13.2%} {mn[\"ann_ret\"]:>12.2%} '\n"
    "          f'{mn[\"sharpe\"]:>12.2f} {mn[\"max_dd\"]:>8.1%} {mn[\"win_rate\"]:>8.1%}{flag}')"
))

cells.append(code(
    "# ── IC summary table ──\n"
    "ic_rows = [\n"
    "    ('NB13 Baseline',       res_base['ic']),\n"
    "    ('B1a Monthly',         res_b1a['ic']),\n"
    "    ('B1b Threshold',       res_b1b['ic']),\n"
    "    ('B2 Long-only weekly', res_b2w['ic']),\n"
    "    ('B2 Long-only monthly',res_b2m['ic']),\n"
    "]\n"
    "print(f'\\n{\"Strategy\":<28} {\"IC mean\":>9} {\"ICIR\":>8} {\"IC+%\":>7} {\"p\":>8}')\n"
    "print('-' * 65)\n"
    "for name, ic_ser in ic_rows:\n"
    "    s = ic_summary(ic_ser)\n"
    "    if not s: continue\n"
    "    sig = ' *' if s['p'] < 0.05 else ''\n"
    "    print(f'{name:<28} {s[\"ic_mean\"]:>+9.4f} {s[\"icir\"]:>8.3f} {s[\"ic_pos\"]:>7.1%} {s[\"p\"]:>8.4f}{sig}')"
))

cells.append(code(
    "# ── Equity curves ──\n"
    "fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True)\n"
    "fig.suptitle('Low-TC Sector Rotation: Equity Curves vs NB13 Baseline', fontsize=12)\n\n"
    "# Top: L/S variants\n"
    "ax = axes[0]\n"
    "plot_ls = [\n"
    "    (res_base['net_ret'],  'NB13 Baseline (weekly L/S)', '#EF5350', '-',  2.0),\n"
    "    (res_b1a['net_ret'],   'B1a Monthly 4w (net TC)',    '#1976D2', '-',  2.0),\n"
    "    (res_b1a_8['net_ret'], 'B1a Bi-monthly 8w (net TC)', '#42A5F5', '--', 1.5),\n"
    "    (res_b1b['net_ret'],   'B1b Threshold (net TC)',     '#7B1FA2', '-',  2.0),\n"
    "    (bnh,                  'Equal-Weight B&H',           '#4CAF50', ':',  1.5),\n"
    "]\n"
    "for rets, lbl, col, ls, lw in plot_ls:\n"
    "    cum = (1 + rets.dropna()).cumprod()\n"
    "    m   = risk_metrics(rets)\n"
    "    ax.plot(cum, lw=lw, ls=ls, color=col, label=f'{lbl} (Sharpe={m[\"sharpe\"]:+.2f})')\n"
    "ax.axhline(1.0, color='gray', lw=0.5, ls=':')\n"
    "ax.set_yscale('log')\n"
    "ax.set_ylabel('Cumulative Return (log)')\n"
    "ax.set_title('B1: Long/Short Variants — Monthly & Threshold Rebalancing')\n"
    "ax.legend(fontsize=8, loc='lower left')\n\n"
    "# Bottom: long-only variants\n"
    "ax2 = axes[1]\n"
    "lo_rets_w = res_b2w['port_ret'] - res_b2w['tc_cost']\n"
    "lo_rets_m = res_b2m['port_ret'] - res_b2m['tc_cost']\n"
    "bench_b2  = res_b2w['bench_ret']\n"
    "for rets, lbl, col, ls, lw in [\n"
    "    (lo_rets_w,  'B2 Long-only weekly (net TC)',  '#FF6F00', '-',  2.0),\n"
    "    (lo_rets_m,  'B2 Long-only monthly (net TC)', '#FFA726', '--', 1.5),\n"
    "    (bench_b2,   'Equal-Weight B&H (benchmark)',  '#4CAF50', ':',  1.5),\n"
    "]:\n"
    "    cum = (1 + rets.dropna()).cumprod()\n"
    "    m   = risk_metrics(rets)\n"
    "    ax2.plot(cum, lw=lw, ls=ls, color=col, label=f'{lbl} (Sharpe={m[\"sharpe\"]:+.2f})')\n"
    "ax2.axhline(1.0, color='gray', lw=0.5, ls=':')\n"
    "ax2.set_yscale('log')\n"
    "ax2.set_ylabel('Cumulative Return (log)')\n"
    "ax2.set_title('B2: Long-Only Variants')\n"
    "ax2.legend(fontsize=8, loc='upper left')\n\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'low_tc_equity.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/low_tc_equity.png')"
))

cells.append(code(
    "# ── TC breakdown ──\n"
    "print('TC Analysis:')\n"
    "print(f'{\"Strategy\":<32} {\"TC/yr (approx)\":>16} {\"Rebal rate\":>12}')\n"
    "print('-' * 62)\n"
    "print(f'{\"NB13 Baseline (weekly L/S)\":<32} {(LONG_K+SHORT_K)*TC*52:>16.2%} {1.0:>12.1%}')\n"
    "print(f'{\"B1a Monthly (4w)\":<32} {(LONG_K+SHORT_K)*TC*13:>16.2%} {res_b1a[\"rebalanced\"].mean():>12.1%}')\n"
    "print(f'{\"B1a Bi-monthly (8w)\":<32} {(LONG_K+SHORT_K)*TC*6.5:>16.2%} {res_b1a_8[\"rebalanced\"].mean():>12.1%}')\n"
    "print(f'{\"B1b Threshold\":<32} {res_b1b[\"tc_cost\"].mean()*52:>16.2%} {res_b1b[\"rebalanced\"].mean():>12.1%}')\n"
    "print(f'{\"B2 Long-only weekly\":<32} {res_b2w[\"tc_cost\"].mean()*52:>16.2%} {res_b2w[\"rebalanced\"].mean():>12.1%}')\n"
    "print(f'{\"B2 Long-only monthly\":<32} {res_b2m[\"tc_cost\"].mean()*52:>16.2%} {res_b2m[\"rebalanced\"].mean():>12.1%}')"
))

# ── Section 7 — Verdict ───────────────────────────────────────────────────────
cells.append(md("---\n## Section 7 — Verdict"))

cells.append(code(
    "# ── Score each variant ──\n"
    "def score_variant(net_ret, ic_ser, label):\n"
    "    m  = risk_metrics(net_ret)\n"
    "    ic = ic_summary(ic_ser)\n"
    "    if not m or not ic:\n"
    "        return\n"
    "    ev = [\n"
    "        ('IC mean > 0.03',           ic['ic_mean'],    0.03,  ic['ic_mean'] > 0.03),\n"
    "        ('IC t-test p < 0.05',       ic['p'],          0.05,  ic['p'] < 0.05),\n"
    "        ('ICIR > 0.5',               ic['icir'],       0.5,   ic['icir'] > 0.5),\n"
    "        ('Sharpe (net TC) > 0',      m['sharpe'],      0,     m['sharpe'] > 0),\n"
    "        ('Sharpe (net TC) > 0.3',    m['sharpe'],      0.3,   m['sharpe'] > 0.3),\n"
    "        ('Annual return net > 0%',   m['ann_ret'],     0,     m['ann_ret'] > 0),\n"
    "        ('Max DD > -40%',            m['max_dd'],     -0.4,   m['max_dd'] > -0.4),\n"
    "        ('Win rate > 50%',           m['win_rate'],    0.5,   m['win_rate'] > 0.5),\n"
    "    ]\n"
    "    score = sum(1 for *_, p in ev if p)\n"
    "    print(f'\\n{label}  (Score: {score}/{len(ev)})')\n"
    "    print('-' * 55)\n"
    "    for desc, val, thr, passed in ev:\n"
    "        mark = '[+]' if passed else '[-]'\n"
    "        if isinstance(val, float) and abs(val) < 2:\n"
    "            print(f'  {mark} {desc:<34} {val:>+.4f}  > {thr}')\n"
    "        else:\n"
    "            print(f'  {mark} {desc:<34} {val:>+.1%}  > {thr:.0%}')\n"
    "    verdict = 'VIABLE' if score >= 5 else 'BORDERLINE' if score >= 3 else 'NOT VIABLE'\n"
    "    print(f'  => {verdict}')\n"
    "    return score\n\n"
    "print('=' * 60)\n"
    "print('LOW-TC SECTOR ROTATION VERDICT')\n"
    "print('=' * 60)\n"
    "scores = {}\n"
    "for name, net, ic_s in [\n"
    "    ('NB13 Baseline (weekly L/S)',  res_base['net_ret'],  res_base['ic']),\n"
    "    ('B1a Monthly (4w L/S)',        res_b1a['net_ret'],   res_b1a['ic']),\n"
    "    ('B1a Bi-monthly (8w L/S)',     res_b1a_8['net_ret'], res_b1a_8['ic']),\n"
    "    ('B1b Threshold L/S',          res_b1b['net_ret'],   res_b1b['ic']),\n"
    "    ('B2 Long-only weekly',         lo_rets_w,            res_b2w['ic']),\n"
    "    ('B2 Long-only monthly',        lo_rets_m,            res_b2m['ic']),\n"
    "]:\n"
    "    scores[name] = score_variant(net, ic_s, name)\n\n"
    "best = max(scores, key=lambda k: scores[k] or 0)\n"
    "print(f'\\nBest variant: {best} (score={scores[best]}/8)')"
))

# ── Write notebook ─────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w") as f:
    json.dump(nb, f, indent=1)
print(f"Written: {OUT}  ({len(cells)} cells)")
