"""
gen_nb10_backtest.py -- generate notebooks/eda/10_backtest.ipynb

Walk-forward backtesting on XGB-Pruned (11 features from NB09 pruning).
Questions:
  1. What is the actual PnL curve (2003-2025)?
  2. What is max drawdown?
  3. Does signal survive transaction costs?
  4. Is it investable?
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '10_backtest.ipynb'

def md(source): return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

cells = []

# ── Cell 0: Title ──────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 10 -- Walk-Forward Backtesting\n"
    "\n"
    "> *Does the signal generate real profit after costs?*\n"
    "\n"
    "**Setup:** XGB-Pruned model, 11 features (from NB09 pruning), SET Index target.\n"
    "Walk-forward expanding window, 2003–2025.\n"
    "\n"
    "| Section | Question |\n"
    "|---|---|\n"
    "| 1. PnL Curve | Cumulative return vs Buy-and-Hold |\n"
    "| 2. Risk Metrics | Sharpe, Sortino, Max Drawdown, Win Rate |\n"
    "| 3. TC Sensitivity | Does it survive 0.1% / 0.2% / 0.3% per trade? |\n"
    "| 4. Annual Breakdown | Year-by-year performance |\n"
    "| 5. Regime Analysis | Bull / Normal / Crisis PnL |\n"
    "| 6. Verdict | Is this signal investable? |\n"
))

# ── Cell 1: Setup ──────────────────────────────────────────────────────────────
cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "from scipy.stats import spearmanr\n"
    "from sklearn.base import clone\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.pipeline import Pipeline\n"
    "from xgboost import XGBRegressor\n"
    "warnings.filterwarnings('ignore')\n"
    "np.random.seed(42)\n"
    "\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.dpi': 110, 'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'font.size': 10, 'axes.titlesize': 11,\n"
    "})\n"
    "\n"
    "print('Setup complete.')"
))

# ── Cell 2: Load data + define features ────────────────────────────────────────
cells.append(md("---\n## Section 1 -- Data & Model Setup\n"))

cells.append(code(
    "clean = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "print(f'Dataset: {clean.shape[0]} rows x {clean.shape[1]} cols')\n"
    "\n"
    "TARGET = 'SET_index_ret_w_fwd1'\n"
    "df = clean.dropna(subset=[TARGET]).copy()\n"
    "\n"
    "# 11 KEEP features from NB09 pruning decision\n"
    "FEATURES = [\n"
    "    'sp500_ret_w',          # US equity return (contemporaneous)\n"
    "    'SET_index_rvol_4w',    # SET realized vol\n"
    "    'sp500_rvol_4w',        # US equity realized vol\n"
    "    'us_10yr_treasury_ret_w', # US 10yr bond return\n"
    "    'oil_ret_d_lag1',       # Oil lag-1 daily\n"
    "    'eem_ret_d_lag1',       # EM ETF lag-1 daily\n"
    "    'gold_rvol_4w',         # Gold realized vol\n"
    "    'us_2yr_treasury_ret_w', # US 2yr bond return\n"
    "    'oil_ret_w',            # Oil weekly return\n"
    "    'SET_index_ret_w',      # SET weekly return (momentum/reversal)\n"
    "    'USD_THB_ret_w',        # USD/THB weekly return\n"
    "]\n"
    "FEATURES = [f for f in FEATURES if f in df.columns]\n"
    "print(f'Features: {len(FEATURES)}')\n"
    "\n"
    "# XGB-Pruned: best config from NB09 Task 3\n"
    "MODEL = XGBRegressor(\n"
    "    n_estimators=50, max_depth=2, learning_rate=0.05,\n"
    "    subsample=0.7, colsample_bytree=0.5,\n"
    "    min_child_weight=20, reg_alpha=1.0, reg_lambda=10.0,\n"
    "    random_state=42, verbosity=0, n_jobs=1\n"
    ")\n"
    "\n"
    "MIN_TRAIN = 156  # 3 years\n"
    "FOLD_SIZE  = 52  # 1 year\n"
    "print(f'Walk-forward: min_train={MIN_TRAIN}w, fold={FOLD_SIZE}w')\n"
    "print(f'First OOS date: {df.index[MIN_TRAIN].date()}')"
))

# ── Cell 3: Walk-forward + build PnL series ────────────────────────────────────
cells.append(code(
    "# Walk-forward: collect weekly predictions + actual returns\n"
    "data = df[FEATURES + [TARGET]].dropna(subset=[TARGET])\n"
    "n = len(data)\n"
    "t = MIN_TRAIN\n"
    "\n"
    "records = []\n"
    "while t + FOLD_SIZE <= n:\n"
    "    train = data.iloc[:t]\n"
    "    test  = data.iloc[t:t+FOLD_SIZE]\n"
    "    medians = train[FEATURES].median()\n"
    "    Xtr = train[FEATURES].fillna(medians).fillna(0.).values.astype(float)\n"
    "    Xte = test[FEATURES].fillna(medians).fillna(0.).values.astype(float)\n"
    "    ytr = train[TARGET].values\n"
    "    yte = test[TARGET].values\n"
    "\n"
    "    m = clone(MODEL)\n"
    "    m.fit(Xtr, ytr)\n"
    "    pred = m.predict(Xte)\n"
    "\n"
    "    for date, y_true, y_pred in zip(test.index, yte, pred):\n"
    "        records.append({\n"
    "            'date':   date,\n"
    "            'actual': y_true,\n"
    "            'signal': np.sign(y_pred),\n"
    "            'pred':   y_pred,\n"
    "        })\n"
    "    t += FOLD_SIZE\n"
    "\n"
    "pnl = pd.DataFrame(records).set_index('date').sort_index()\n"
    "pnl['gross_ret'] = pnl['signal'] * pnl['actual']  # long-short, no TC\n"
    "\n"
    "print(f'OOS period: {pnl.index[0].date()} -> {pnl.index[-1].date()}')\n"
    "print(f'OOS weeks:  {len(pnl)}')\n"
    "print(f'Long weeks: {(pnl[\"signal\"]==1).sum()}  Short weeks: {(pnl[\"signal\"]==-1).sum()}')\n"
    "print(f'Turnover:   {(pnl[\"signal\"].diff().abs()>0).mean():.1%} of weeks flip position')"
))

# ── Cell 4: TC calculation ─────────────────────────────────────────────────────
cells.append(code(
    "# Transaction cost model: pay TC when position changes (flip long<->short)\n"
    "# TC is one-way, so a flip costs 2x TC (exit + enter)\n"
    "TC_LEVELS = [0.0, 0.001, 0.002, 0.003]  # 0%, 0.1%, 0.2%, 0.3%\n"
    "TC_LABELS = ['0% TC', '0.1% TC', '0.2% TC', '0.3% TC']\n"
    "\n"
    "flip = pnl['signal'].diff().abs() > 0  # week had a position flip\n"
    "\n"
    "for tc, lbl in zip(TC_LEVELS, TC_LABELS):\n"
    "    pnl[f'ret_{lbl}'] = pnl['gross_ret'] - flip * 2 * tc\n"
    "\n"
    "# Buy-and-hold benchmark (always long SET, no TC)\n"
    "pnl['bnh'] = pnl['actual']\n"
    "\n"
    "print('Weekly return statistics (gross, no TC):')\n"
    "print(f'  Mean weekly return: {pnl[\"gross_ret\"].mean():.4f} ({pnl[\"gross_ret\"].mean()*52:.2%} ann.)')\n"
    "print(f'  Weekly vol:         {pnl[\"gross_ret\"].std():.4f} ({pnl[\"gross_ret\"].std()*np.sqrt(52):.2%} ann.)')\n"
    "print(f'  Win rate:           {(pnl[\"gross_ret\"]>0).mean():.1%}')\n"
    "print(f'  Flips per year:     {flip.mean()*52:.1f}')"
))

# ── Cell 5: Cumulative PnL plot ────────────────────────────────────────────────
cells.append(md("---\n## Section 2 -- Cumulative PnL vs Buy-and-Hold\n"))

cells.append(code(
    "fig, axes = plt.subplots(2, 1, figsize=(13, 9), gridspec_kw={'height_ratios': [3, 1]})\n"
    "\n"
    "# Cumulative returns\n"
    "ax = axes[0]\n"
    "colors = ['#1976D2', '#42A5F5', '#90CAF9', '#BBDEFB']\n"
    "for tc, lbl, col in zip(TC_LEVELS, TC_LABELS, colors):\n"
    "    cum = (1 + pnl[f'ret_{lbl}']).cumprod()\n"
    "    ax.plot(pnl.index, cum, label=f'Signal ({lbl})', color=col,\n"
    "            lw=2.0 if tc == 0 else 1.2, alpha=0.9 if tc == 0 else 0.6)\n"
    "\n"
    "bnh_cum = (1 + pnl['bnh']).cumprod()\n"
    "ax.plot(pnl.index, bnh_cum, label='Buy-and-Hold SET', color='#E53935',\n"
    "        lw=1.5, ls='--', alpha=0.8)\n"
    "ax.axhline(1.0, color='black', lw=0.6, ls=':')\n"
    "ax.set_ylabel('Cumulative Return (1 = start)')\n"
    "ax.set_title('Cumulative PnL: XGB-Pruned Signal vs Buy-and-Hold SET (2003–2025)', fontsize=12)\n"
    "ax.legend(fontsize=9, loc='upper left')\n"
    "ax.set_yscale('log')\n"
    "\n"
    "# Drawdown (gross, no TC)\n"
    "ax2 = axes[1]\n"
    "cum_gross = (1 + pnl['gross_ret']).cumprod()\n"
    "roll_max  = cum_gross.cummax()\n"
    "drawdown  = (cum_gross - roll_max) / roll_max\n"
    "ax2.fill_between(pnl.index, drawdown, 0, color='#EF5350', alpha=0.5)\n"
    "ax2.set_ylabel('Drawdown')\n"
    "ax2.set_xlabel('Date')\n"
    "ax2.set_title('Drawdown (Gross Signal)')\n"
    "ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'backtest_pnl_curve.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/backtest_pnl_curve.png')"
))

# ── Cell 6: Risk metrics table ─────────────────────────────────────────────────
cells.append(md("---\n## Section 3 -- Risk & Performance Metrics\n"))

cells.append(code(
    "def risk_metrics(rets, freq=52, label=''):\n"
    "    ann_ret  = (1 + rets).prod() ** (freq / len(rets)) - 1\n"
    "    ann_vol  = rets.std() * np.sqrt(freq)\n"
    "    sharpe   = ann_ret / ann_vol if ann_vol > 0 else np.nan\n"
    "    neg      = rets[rets < 0]\n"
    "    sortino  = ann_ret / (neg.std() * np.sqrt(freq)) if len(neg) > 0 else np.nan\n"
    "    cum      = (1 + rets).cumprod()\n"
    "    roll_max = cum.cummax()\n"
    "    dd       = (cum - roll_max) / roll_max\n"
    "    max_dd   = dd.min()\n"
    "    calmar   = ann_ret / abs(max_dd) if max_dd < 0 else np.nan\n"
    "    win_rate = (rets > 0).mean()\n"
    "    return {\n"
    "        'label': label, 'ann_ret': ann_ret, 'ann_vol': ann_vol,\n"
    "        'sharpe': sharpe, 'sortino': sortino,\n"
    "        'max_dd': max_dd, 'calmar': calmar, 'win_rate': win_rate,\n"
    "    }\n"
    "\n"
    "rows = []\n"
    "for tc, lbl in zip(TC_LEVELS, TC_LABELS):\n"
    "    rows.append(risk_metrics(pnl[f'ret_{lbl}'], label=f'Signal ({lbl})'))\n"
    "rows.append(risk_metrics(pnl['bnh'], label='Buy-and-Hold SET'))\n"
    "\n"
    "metrics_df = pd.DataFrame(rows).set_index('label')\n"
    "\n"
    "print(f'{\"\":30} {\"AnnRet\":>8} {\"AnnVol\":>8} {\"Sharpe\":>8} {\"Sortino\":>8} {\"MaxDD\":>8} {\"WinRate\":>8}')\n"
    "print('-' * 82)\n"
    "for lbl, row in metrics_df.iterrows():\n"
    "    print(f'{lbl:<30} {row[\"ann_ret\"]:>8.2%} {row[\"ann_vol\"]:>8.2%} '\n"
    "          f'{row[\"sharpe\"]:>8.2f} {row[\"sortino\"]:>8.2f} '\n"
    "          f'{row[\"max_dd\"]:>8.1%} {row[\"win_rate\"]:>8.1%}')"
))

# ── Cell 7: TC breakeven ───────────────────────────────────────────────────────
cells.append(code(
    "# TC breakeven: find max TC at which Sharpe > 0\n"
    "flip_rate = flip.mean()  # fraction of weeks with position change\n"
    "gross_ann  = risk_metrics(pnl['gross_ret'])['ann_ret']\n"
    "tc_breakeven = gross_ann / (2 * flip_rate * 52) if flip_rate > 0 else np.nan\n"
    "\n"
    "print(f'Gross annual return:     {gross_ann:.2%}')\n"
    "print(f'Position flip rate:      {flip_rate:.1%} of weeks ({flip_rate*52:.1f} flips/year)')\n"
    "print(f'TC breakeven (one-way):  {tc_breakeven:.3%}  ({tc_breakeven*10000:.1f} bps)')\n"
    "print()\n"
    "if tc_breakeven > 0.003:\n"
    "    print('>> Signal SURVIVES 0.3% TC -- viable for institutional execution')\n"
    "elif tc_breakeven > 0.001:\n"
    "    print('>> Signal survives 0.1% TC -- viable with low-cost execution')\n"
    "else:\n"
    "    print('>> Signal does NOT survive realistic TC -- too expensive to trade')"
))

# ── Cell 8: Annual breakdown ───────────────────────────────────────────────────
cells.append(md("---\n## Section 4 -- Annual Performance Breakdown\n"))

cells.append(code(
    "pnl['year'] = pnl.index.year\n"
    "annual = pnl.groupby('year').apply(\n"
    "    lambda g: pd.Series({\n"
    "        'signal_gross': (1+g['gross_ret']).prod()-1,\n"
    "        'signal_01tc':  (1+g[f'ret_0.1% TC']).prod()-1,\n"
    "        'bnh':          (1+g['bnh']).prod()-1,\n"
    "        'n_weeks':      len(g),\n"
    "        'win_rate':     (g['gross_ret']>0).mean(),\n"
    "    })\n"
    ").reset_index()\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('Annual Returns: Signal vs Buy-and-Hold', fontsize=12)\n"
    "\n"
    "x = range(len(annual))\n"
    "w = 0.35\n"
    "ax = axes[0]\n"
    "bars1 = ax.bar([i-w/2 for i in x], annual['signal_01tc']*100,\n"
    "               width=w, label='Signal (0.1%TC)',\n"
    "               color=['#1976D2' if v>0 else '#EF5350' for v in annual['signal_01tc']])\n"
    "bars2 = ax.bar([i+w/2 for i in x], annual['bnh']*100,\n"
    "               width=w, label='Buy-and-Hold', color='#78909C', alpha=0.6)\n"
    "ax.axhline(0, color='black', lw=0.8)\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(annual['year'], rotation=45)\n"
    "ax.set_ylabel('Annual Return (%)')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_title('Annual Return by Year')\n"
    "\n"
    "ax2 = axes[1]\n"
    "ax2.bar(x, annual['win_rate']*100, color='#42A5F5', alpha=0.8)\n"
    "ax2.axhline(50, color='black', lw=0.8, ls='--')\n"
    "ax2.set_xticks(x)\n"
    "ax2.set_xticklabels(annual['year'], rotation=45)\n"
    "ax2.set_ylabel('Win Rate (%)')\n"
    "ax2.set_title('Weekly Win Rate by Year')\n"
    "ax2.set_ylim(30, 70)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'backtest_annual.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print(f'{\"Year\":>6} {\"Signal(0.1%TC)\":>16} {\"Buy-Hold\":>10} {\"WinRate\":>9}')\n"
    "print('-' * 45)\n"
    "pos_yrs = 0\n"
    "for _, row in annual.iterrows():\n"
    "    flag = '✓' if row['signal_01tc'] > 0 else '✗'\n"
    "    print(f'{int(row[\"year\"]):>6} {row[\"signal_01tc\"]:>15.1%} {flag}  {row[\"bnh\"]:>9.1%}  {row[\"win_rate\"]:>8.1%}')\n"
    "    if row['signal_01tc'] > 0: pos_yrs += 1\n"
    "print(f'\\nPositive years (0.1%TC): {pos_yrs}/{len(annual)}')"
))

# ── Cell 9: Regime PnL ─────────────────────────────────────────────────────────
cells.append(md("---\n## Section 5 -- Regime-Conditional Performance\n"))

cells.append(code(
    "regime_col = clean['regime'].reindex(pnl.index)\n"
    "pnl['regime'] = regime_col\n"
    "\n"
    "regime_labels = {-1: 'Bull (low VIX)', 0: 'Normal', 1: 'Crisis (high VIX)'}\n"
    "\n"
    "print(f'{\"Regime\":<22} {\"N\":>5} {\"AnnRet\":>8} {\"Sharpe\":>8} {\"WinRate\":>8} {\"MaxDD\":>8}')\n"
    "print('-' * 60)\n"
    "for r, lbl in sorted(regime_labels.items()):\n"
    "    sub = pnl[pnl['regime'] == r]['gross_ret'].dropna()\n"
    "    if len(sub) < 10:\n"
    "        print(f'{lbl:<22} {len(sub):>5} -- (insufficient)')\n"
    "        continue\n"
    "    m = risk_metrics(sub, label=lbl)\n"
    "    print(f'{lbl:<22} {len(sub):>5} {m[\"ann_ret\"]:>8.1%} {m[\"sharpe\"]:>8.2f} '\n"
    "          f'{m[\"win_rate\"]:>8.1%} {m[\"max_dd\"]:>8.1%}')\n"
    "\n"
    "# Plot cumulative PnL by regime\n"
    "fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n"
    "fig.suptitle('Cumulative PnL by Regime (Gross, No TC)', fontsize=12)\n"
    "colors_r = {-1: '#4CAF50', 0: '#2196F3', 1: '#F44336'}\n"
    "\n"
    "for ax, (r, lbl) in zip(axes, sorted(regime_labels.items())):\n"
    "    sub = pnl[pnl['regime'] == r]['gross_ret'].dropna()\n"
    "    if len(sub) < 10:\n"
    "        ax.set_title(f'{lbl}\\n(N={len(sub)}, skip)')\n"
    "        continue\n"
    "    cum = (1 + sub).cumprod()\n"
    "    ax.plot(cum.values, color=colors_r[r], lw=1.5)\n"
    "    ax.axhline(1.0, color='black', lw=0.6, ls=':')\n"
    "    m = risk_metrics(sub)\n"
    "    ax.set_title(f'{lbl}\\nSharpe={m[\"sharpe\"]:+.2f}, WinRate={m[\"win_rate\"]:.0%}')\n"
    "    ax.set_xlabel('Week')\n"
    "    ax.set_ylabel('Cum. Return')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'backtest_regime.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/backtest_regime.png')"
))

# ── Cell 10: Feature importance over time ─────────────────────────────────────
cells.append(code(
    "# Rolling 3-year Sharpe to check for signal decay\n"
    "ROLL_WIN = 156  # 3 years\n"
    "roll_ret  = pnl['gross_ret'].rolling(ROLL_WIN)\n"
    "roll_sharpe = roll_ret.mean() / roll_ret.std() * np.sqrt(52)\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True)\n"
    "fig.suptitle('Signal Decay Check: Rolling 3-Year Sharpe & Win Rate', fontsize=12)\n"
    "\n"
    "ax1.plot(pnl.index, roll_sharpe, color='#1976D2', lw=1.5)\n"
    "ax1.axhline(0, color='black', lw=0.8, ls='--')\n"
    "ax1.axhline(0.5, color='green', lw=0.8, ls=':', alpha=0.7, label='Sharpe=0.5')\n"
    "ax1.fill_between(pnl.index, roll_sharpe, 0,\n"
    "                 where=roll_sharpe > 0, alpha=0.15, color='green')\n"
    "ax1.fill_between(pnl.index, roll_sharpe, 0,\n"
    "                 where=roll_sharpe < 0, alpha=0.15, color='red')\n"
    "ax1.set_ylabel('Rolling Sharpe (3yr)')\n"
    "ax1.legend(fontsize=9)\n"
    "\n"
    "roll_win = (pnl['gross_ret'] > 0).rolling(ROLL_WIN).mean()\n"
    "ax2.plot(pnl.index, roll_win, color='#FF5722', lw=1.5)\n"
    "ax2.axhline(0.5, color='black', lw=0.8, ls='--')\n"
    "ax2.set_ylabel('Rolling Win Rate (3yr)')\n"
    "ax2.set_xlabel('Date')\n"
    "ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'backtest_rolling.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/backtest_rolling.png')"
))

# ── Cell 11: Final verdict ─────────────────────────────────────────────────────
cells.append(md("---\n## Section 6 -- Final Verdict: Is This Signal Investable?\n"))

cells.append(code(
    "# Collect all evidence\n"
    "m_gross   = risk_metrics(pnl['gross_ret'], label='Gross')\n"
    "m_01tc    = risk_metrics(pnl['ret_0.1% TC'], label='0.1%TC')\n"
    "m_02tc    = risk_metrics(pnl['ret_0.2% TC'], label='0.2%TC')\n"
    "m_03tc    = risk_metrics(pnl['ret_0.3% TC'], label='0.3%TC')\n"
    "m_bnh     = risk_metrics(pnl['bnh'], label='BnH')\n"
    "\n"
    "score, evidence = 0, []\n"
    "def ev(desc, val, thresh, passes, fmt='f'):\n"
    "    global score\n"
    "    if passes: score += 1\n"
    "    sign = '+' if passes else '-'\n"
    "    val_str = f'{val:.2%}' if fmt=='pct' else f'{val:.2f}'\n"
    "    evidence.append((sign, desc, val_str, thresh))\n"
    "\n"
    "ev('Annual return (gross)',          m_gross['ann_ret'],    '>5%',    m_gross['ann_ret']  > 0.05,  'pct')\n"
    "ev('Annual return (0.1% TC)',        m_01tc['ann_ret'],     '>3%',    m_01tc['ann_ret']   > 0.03,  'pct')\n"
    "ev('Annual return (0.2% TC)',        m_02tc['ann_ret'],     '>0%',    m_02tc['ann_ret']   > 0.00,  'pct')\n"
    "ev('Sharpe ratio (gross)',           m_gross['sharpe'],     '>0.5',   m_gross['sharpe']   > 0.5)\n"
    "ev('Sharpe ratio (0.1% TC)',         m_01tc['sharpe'],      '>0.3',   m_01tc['sharpe']    > 0.3)\n"
    "ev('Max Drawdown (gross)',           m_gross['max_dd'],     '>-30%',  m_gross['max_dd']   > -0.30, 'pct')\n"
    "ev('Win rate (gross)',               m_gross['win_rate'],   '>52%',   m_gross['win_rate'] > 0.52,  'pct')\n"
    "ev('Beats Buy-and-Hold (gross)',     m_gross['ann_ret'] - m_bnh['ann_ret'],\n"
    "                                     '>0%',  m_gross['ann_ret'] > m_bnh['ann_ret'], 'pct')\n"
    "ev('TC breakeven > 0.1%',           tc_breakeven,           '>0.1%',  tc_breakeven > 0.001, 'pct')\n"
    "pos_frac = (annual['signal_01tc'] > 0).mean()\n"
    "ev('Positive years > 60% (0.1%TC)', pos_frac,               '>60%',   pos_frac > 0.6,   'pct')\n"
    "\n"
    "print('=' * 65)\n"
    "print('BACKTEST VERDICT: IS THIS SIGNAL INVESTABLE?')\n"
    "print('=' * 65)\n"
    "print(f'{\"\":>2} {\"Evidence\":<38} {\"Value\":>8} {\"Threshold\":>10}')\n"
    "print('-' * 65)\n"
    "for sign, desc, val, thresh in evidence:\n"
    "    print(f'[{sign}] {desc:<38} {val:>8} {thresh:>10}')\n"
    "print(f'\\nScore: {score}/{len(evidence)}')\n"
    "print()\n"
    "\n"
    "if score >= 7:\n"
    "    verdict = 'INVESTABLE'\n"
    "    detail  = 'Signal generates real risk-adjusted return after costs. Proceed to live trading with small position size.'\n"
    "elif score >= 5:\n"
    "    verdict = 'MARGINAL -- paper trade first'\n"
    "    detail  = 'Signal shows some real PnL but not consistently after TC. Paper trade for 12+ months before committing capital.'\n"
    "else:\n"
    "    verdict = 'NOT INVESTABLE'\n"
    "    detail  = 'Signal does not generate sufficient return after realistic TC. Do not deploy capital.'\n"
    "\n"
    "print('=' * 65)\n"
    "print(f'VERDICT: {verdict}')\n"
    "print('=' * 65)\n"
    "print()\n"
    "print(detail)"
))

# ── Cell 12: Summary dashboard ────────────────────────────────────────────────
cells.append(code(
    "fig = plt.figure(figsize=(14, 6))\n"
    "gs  = gridspec.GridSpec(1, 3, figure=fig, wspace=0.35)\n"
    "fig.suptitle('Backtest Summary Dashboard -- XGB-Pruned (11 Features)', fontsize=13)\n"
    "\n"
    "# Panel 1: Performance by TC\n"
    "ax1 = fig.add_subplot(gs[0])\n"
    "tc_labels_short = ['Gross', '0.1%TC', '0.2%TC', '0.3%TC', 'BnH']\n"
    "ann_rets = [\n"
    "    m_gross['ann_ret'], m_01tc['ann_ret'], m_02tc['ann_ret'],\n"
    "    m_03tc['ann_ret'], m_bnh['ann_ret']\n"
    "]\n"
    "bar_cols = ['#1976D2','#42A5F5','#90CAF9','#BBDEFB','#E53935']\n"
    "bars = ax1.bar(tc_labels_short, [r*100 for r in ann_rets], color=bar_cols)\n"
    "ax1.axhline(0, color='black', lw=0.8)\n"
    "ax1.set_ylabel('Annual Return (%)')\n"
    "ax1.set_title('Return by TC Level')\n"
    "for bar, r in zip(bars, ann_rets):\n"
    "    ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,\n"
    "             f'{r:.1%}', ha='center', va='bottom', fontsize=8)\n"
    "\n"
    "# Panel 2: Sharpe by TC\n"
    "ax2 = fig.add_subplot(gs[1])\n"
    "sharpes = [m_gross['sharpe'], m_01tc['sharpe'], m_02tc['sharpe'],\n"
    "           m_03tc['sharpe'], m_bnh['sharpe']]\n"
    "ax2.bar(tc_labels_short, sharpes, color=bar_cols)\n"
    "ax2.axhline(0, color='black', lw=0.8)\n"
    "ax2.axhline(0.5, color='green', lw=0.8, ls='--', label='Sharpe=0.5')\n"
    "ax2.set_ylabel('Sharpe Ratio')\n"
    "ax2.set_title('Sharpe by TC Level')\n"
    "ax2.legend(fontsize=8)\n"
    "for bar, s in zip(ax2.patches, sharpes):\n"
    "    ax2.text(bar.get_x()+bar.get_width()/2, max(bar.get_height(), 0)+0.02,\n"
    "             f'{s:.2f}', ha='center', va='bottom', fontsize=8)\n"
    "\n"
    "# Panel 3: Max DD\n"
    "ax3 = fig.add_subplot(gs[2])\n"
    "max_dds = [m_gross['max_dd'], m_01tc['max_dd'], m_02tc['max_dd'],\n"
    "           m_03tc['max_dd'], m_bnh['max_dd']]\n"
    "ax3.bar(tc_labels_short, [d*100 for d in max_dds], color='#EF5350', alpha=0.8)\n"
    "ax3.axhline(-30, color='black', lw=0.8, ls='--', label='-30% threshold')\n"
    "ax3.set_ylabel('Max Drawdown (%)')\n"
    "ax3.set_title('Max Drawdown by TC Level')\n"
    "ax3.legend(fontsize=8)\n"
    "\n"
    "plt.savefig(FIGS / 'backtest_dashboard.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: figs/backtest_dashboard.png')\n"
    "print()\n"
    "print(f'Final: {verdict}')"
))

# ── Write notebook ─────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"},
    },
    "cells": cells,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Generated: {OUT}")
print(f"Cells: {len(cells)}")
