"""
gen_nb13_sector_alpha.py -- generate notebooks/eda/13_sector_alpha.ipynb

Production-grade cross-sectional sector alpha system:
  - Panel data: (date, sector) with 7 SET sectors
  - Cross-sectional target: sector_return - market_mean
  - Models: XGBoost Regressor + XGBoost Ranker (rank:pairwise)
  - Walk-forward CV: strict time-series splits
  - Signal: long top-2, short bottom-2 (market-neutral)
  - Full backtesting: TC, turnover, Sharpe, IC, drawdown
  - Benchmark: equal-weight sector portfolio
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '13_sector_alpha.ipynb'

def md(source): return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

cells = []

# ── Title ──────────────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 13 -- Cross-Sectional Sector Alpha\n"
    "\n"
    "> *Does true sector-level alpha exist beyond market beta in the Thai SET?*\n"
    "\n"
    "**Architecture:**\n"
    "- **7 SET sectors:** BANK, ENERGY, ICT, COMMERCE, HEALTH, PROPERTY, FOOD\n"
    "- **Target:** cross-sectional excess return (sector − market mean)\n"
    "- **Models:** XGBoost Regressor + XGBoost Ranker (`rank:pairwise`)\n"
    "- **Signal:** Long top-2 / Short bottom-2 → market-neutral\n"
    "- **Benchmark:** Equal-weight all-sector portfolio\n"
    "\n"
    "| Section | Description |\n"
    "|---|---|\n"
    "| 1. Data | Sector returns + macro features |\n"
    "| 2. Features | Sector momentum, vol, macro, regime |\n"
    "| 3. Target | Cross-sectional demeaning |\n"
    "| 4. Models | XGB Regressor vs Ranker (walk-forward) |\n"
    "| 5. Signal | Rank → Long/Short portfolio |\n"
    "| 6. Backtest | PnL, IC, Sharpe, drawdown, TC |\n"
    "| 7. Attribution | Feature importance, regime breakdown |\n"
    "| 8. Verdict | Is sector alpha real? |\n"
))

# ── Setup ──────────────────────────────────────────────────────────────────────
cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "from scipy.stats import spearmanr, ttest_1samp\n"
    "from sklearn.base import clone\n"
    "from sklearn.preprocessing import LabelEncoder\n"
    "from xgboost import XGBRegressor, XGBRanker\n"
    "warnings.filterwarnings('ignore')\n"
    "np.random.seed(42)\n"
    "\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.dpi': 110, 'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'font.size': 10, 'axes.titlesize': 11,\n"
    "})\n"
    "\n"
    "SECTORS = ['BANK','ENERGY','ICT','COMMERCE','HEALTH','PROPERTY','FOOD']\n"
    "TC      = 0.001   # 0.1% one-way TC\n"
    "MIN_TRAIN = 156   # 3 years\n"
    "FOLD_SIZE  = 52   # 1 year\n"
    "LONG_K  = 2       # top-k sectors to go long\n"
    "SHORT_K = 2       # bottom-k sectors to go short\n"
    "\n"
    "print('Setup complete.')"
))

# ── Section 1: Data loading ────────────────────────────────────────────────────
cells.append(md("---\n## Section 1 -- Data Loading & Merging\n"))

cells.append(code(
    "# Load sector returns\n"
    "sector_raw = pd.read_csv(PROC / 'sector_weekly.csv', index_col=0, parse_dates=True)\n"
    "sector_raw = sector_raw[SECTORS]  # keep only our 7 sectors\n"
    "print(f'Sector data: {sector_raw.shape[0]} weeks x {sector_raw.shape[1]} sectors')\n"
    "print(f'Date range: {sector_raw.index[0].date()} -> {sector_raw.index[-1].date()}')\n"
    "\n"
    "# Load macro features from clean pipeline\n"
    "macro = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "\n"
    "# Select macro features (no lookahead, available at t)\n"
    "MACRO_FEATS = [\n"
    "    'sp500_ret_w', 'sp500_rvol_4w', 'sp500_ret_d_lag1',\n"
    "    'eem_ret_d_lag1', 'oil_ret_w', 'oil_ret_d_lag1',\n"
    "    'gold_ret_w', 'gold_rvol_4w',\n"
    "    'dxy_ret_w', 'dxy_ret_d_lag1',\n"
    "    'us_10yr_treasury_ret_w', 'us_2yr_treasury_ret_w',\n"
    "    'vix_z', 'regime', 'yield_curve_slope',\n"
    "    'SET_index_ret_w', 'SET_index_rvol_4w',\n"
    "]\n"
    "MACRO_FEATS = [f for f in MACRO_FEATS if f in macro.columns]\n"
    "macro_feats = macro[MACRO_FEATS].copy()\n"
    "print(f'Macro features: {len(MACRO_FEATS)}')\n"
    "\n"
    "# Align dates: both indexed to Friday close\n"
    "sector_raw.index = sector_raw.index.normalize()\n"
    "macro_feats.index = macro_feats.index.normalize()\n"
    "common_dates = sector_raw.index.intersection(macro_feats.index)\n"
    "sector = sector_raw.loc[common_dates]\n"
    "macro_feats = macro_feats.loc[common_dates]\n"
    "print(f'Common dates: {len(common_dates)} weeks')\n"
    "print(f'  {common_dates[0].date()} -> {common_dates[-1].date()}')"
))

# ── Section 2: Feature engineering ────────────────────────────────────────────
cells.append(md("---\n## Section 2 -- Feature Engineering (Panel)\n\n"
    "For each (date, sector) pair, we compute sector-specific features:\n"
    "- **Momentum**: 1w, 4w, 12w, 26w lagged returns (each sector's own past)\n"
    "- **Reversal**: 1w return (short-term reversal effect)\n"
    "- **Realized vol**: rolling std of past 4w returns\n"
    "- **Relative momentum**: sector momentum vs. cross-sectional median\n"
    "- **Rank features**: cross-sectional rank of each feature\n"
    "Plus macro features (same for all sectors each date).\n"))

cells.append(code(
    "def build_panel(sector_df, macro_df):\n"
    "    \"\"\"Build (date × sector) panel with all features. Returns long-format DataFrame.\"\"\"\n"
    "    records = []\n"
    "\n"
    "    # Pre-compute sector-level features (wide format, then melt)\n"
    "    # Momentum lags (using shift to avoid lookahead)\n"
    "    mom1  = sector_df.shift(1)           # lag-1w return\n"
    "    mom4  = sector_df.shift(1).rolling(4).mean()   # 4w mean return (lagged)\n"
    "    mom12 = sector_df.shift(1).rolling(12).mean()  # 12w\n"
    "    mom26 = sector_df.shift(1).rolling(26).mean()  # 26w\n"
    "    rvol4 = sector_df.shift(1).rolling(4).std()    # 4w realized vol\n"
    "    rvol12= sector_df.shift(1).rolling(12).std()   # 12w vol\n"
    "\n"
    "    # Cross-sectional rank of momentum (within each date)\n"
    "    mom1_rank  = mom1.rank(axis=1, pct=True) - 0.5   # -0.5 to +0.5\n"
    "    mom4_rank  = mom4.rank(axis=1, pct=True) - 0.5\n"
    "    mom12_rank = mom12.rank(axis=1, pct=True) - 0.5\n"
    "\n"
    "    # Relative momentum: sector - cross-sectional median\n"
    "    mom1_rel  = mom1.subtract(mom1.median(axis=1), axis=0)\n"
    "    mom4_rel  = mom4.subtract(mom4.median(axis=1), axis=0)\n"
    "\n"
    "    # Forward return (target, shift -1 to get next week's return)\n"
    "    fwd_ret = sector_df.shift(-1)   # next week's return\n"
    "\n"
    "    dates = sector_df.index\n"
    "    for date in dates:\n"
    "        if date not in macro_df.index:\n"
    "            continue\n"
    "        macro_row = macro_df.loc[date]\n"
    "        # Cross-sectional market return (equal-weight average of sectors)\n"
    "        market_ret_fwd = fwd_ret.loc[date].mean(skipna=True)\n"
    "\n"
    "        for sec in sector_df.columns:\n"
    "            row = {\n"
    "                'date':   date,\n"
    "                'sector': sec,\n"
    "                # Target: next week's cross-sectional excess return\n"
    "                'fwd_ret':         fwd_ret.loc[date, sec],\n"
    "                'fwd_excess':      fwd_ret.loc[date, sec] - market_ret_fwd,\n"
    "                # Sector features\n"
    "                'mom1':            mom1.loc[date, sec],\n"
    "                'mom4':            mom4.loc[date, sec],\n"
    "                'mom12':           mom12.loc[date, sec],\n"
    "                'mom26':           mom26.loc[date, sec],\n"
    "                'rvol4':           rvol4.loc[date, sec],\n"
    "                'rvol12':          rvol12.loc[date, sec],\n"
    "                'mom1_rank':       mom1_rank.loc[date, sec],\n"
    "                'mom4_rank':       mom4_rank.loc[date, sec],\n"
    "                'mom12_rank':      mom12_rank.loc[date, sec],\n"
    "                'mom1_rel':        mom1_rel.loc[date, sec],\n"
    "                'mom4_rel':        mom4_rel.loc[date, sec],\n"
    "            }\n"
    "            # Add macro features\n"
    "            for col in macro_df.columns:\n"
    "                row[col] = macro_row[col] if col in macro_row.index else np.nan\n"
    "            records.append(row)\n"
    "\n"
    "    panel = pd.DataFrame(records)\n"
    "    panel['date'] = pd.to_datetime(panel['date'])\n"
    "    panel = panel.sort_values(['date','sector']).reset_index(drop=True)\n"
    "    return panel\n"
    "\n"
    "print('Building feature panel...')\n"
    "panel = build_panel(sector, macro_feats)\n"
    "print(f'Panel shape: {panel.shape}')\n"
    "print(f'  Rows: {len(panel)} ({len(panel)//len(SECTORS)} dates x {len(SECTORS)} sectors)')\n"
    "print(f'  Columns: {list(panel.columns[:8])} ... + {len(panel.columns)-8} more')"
))

# ── Section 3: Target & features ─────────────────────────────────────────────
cells.append(md("---\n## Section 3 -- Cross-Sectional Target & Feature List\n"))

cells.append(code(
    "TARGET = 'fwd_excess'   # cross-sectional excess return\n"
    "\n"
    "SECTOR_FEATS = [\n"
    "    'mom1', 'mom4', 'mom12', 'mom26',\n"
    "    'rvol4', 'rvol12',\n"
    "    'mom1_rank', 'mom4_rank', 'mom12_rank',\n"
    "    'mom1_rel', 'mom4_rel',\n"
    "]\n"
    "ALL_FEATS = SECTOR_FEATS + MACRO_FEATS\n"
    "ALL_FEATS = [f for f in ALL_FEATS if f in panel.columns]\n"
    "\n"
    "# Drop rows with no target\n"
    "panel_clean = panel.dropna(subset=[TARGET]).copy()\n"
    "dates_all = sorted(panel_clean['date'].unique())\n"
    "print(f'Clean panel: {len(panel_clean)} rows, {len(dates_all)} dates')\n"
    "print(f'Features: {len(ALL_FEATS)}')\n"
    "print(f'  Sector-specific: {len(SECTOR_FEATS)}')\n"
    "print(f'  Macro:           {len(MACRO_FEATS)}')\n"
    "\n"
    "# Show target distribution\n"
    "print(f'\\nTarget ({TARGET}) stats:')\n"
    "print(f'  Mean:  {panel_clean[TARGET].mean():.5f}  (should be ~0 by construction)')\n"
    "print(f'  Std:   {panel_clean[TARGET].std():.4f}')\n"
    "print(f'  Range: [{panel_clean[TARGET].min():.3f}, {panel_clean[TARGET].max():.3f}]')"
))

# ── Section 4: Walk-forward models ────────────────────────────────────────────
cells.append(md("---\n## Section 4 -- Walk-Forward Validation\n\n"
    "**Expanding window:** train on all data up to fold start, test on next 52 weeks.  \n"
    "**Two models per fold:**\n"
    "- `XGB-Reg`: standard regressor trained on cross-sectional excess return\n"
    "- `XGB-Rank`: pairwise ranker — directly optimises ranking within each date group\n\n"
    "Both models are fitted separately each fold (no parameter leakage).\n"))

cells.append(code(
    "def make_xgb_reg():\n"
    "    return XGBRegressor(\n"
    "        n_estimators=100, max_depth=3, learning_rate=0.05,\n"
    "        subsample=0.7, colsample_bytree=0.6,\n"
    "        min_child_weight=10, reg_alpha=0.5, reg_lambda=5.0,\n"
    "        random_state=42, verbosity=0, n_jobs=1\n"
    "    )\n"
    "\n"
    "def make_xgb_rank():\n"
    "    return XGBRanker(\n"
    "        objective='rank:pairwise',\n"
    "        n_estimators=100, max_depth=3, learning_rate=0.05,\n"
    "        subsample=0.7, colsample_bytree=0.6,\n"
    "        min_child_weight=5, reg_alpha=0.5, reg_lambda=5.0,\n"
    "        random_state=42, verbosity=0, n_jobs=1\n"
    "    )\n"
    "\n"
    "def walk_forward_sector(panel_df, features, target, min_train_dates,\n"
    "                         fold_dates, long_k=2, short_k=2):\n"
    "    \"\"\"\n"
    "    Walk-forward cross-sectional backtest.\n"
    "    Returns per-week portfolio returns for XGB-Reg and XGB-Rank.\n"
    "    \"\"\"\n"
    "    dates = sorted(panel_df['date'].unique())\n"
    "    n_dates = len(dates)\n"
    "    t = min_train_dates\n"
    "    records = []\n"
    "\n"
    "    while t + fold_dates <= n_dates:\n"
    "        train_dates = dates[:t]\n"
    "        test_dates  = dates[t:t+fold_dates]\n"
    "\n"
    "        train = panel_df[panel_df['date'].isin(train_dates)].copy()\n"
    "        test  = panel_df[panel_df['date'].isin(test_dates)].copy()\n"
    "\n"
    "        # Impute with training medians\n"
    "        medians = train[features].median()\n"
    "        Xtr = train[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "        ytr = train[target].values\n"
    "\n"
    "        # XGB-Reg: standard regressor\n"
    "        reg = make_xgb_reg()\n"
    "        reg.fit(Xtr, ytr)\n"
    "\n"
    "        # XGB-Rank: pairwise ranker — needs group sizes (7 per date)\n"
    "        train_groups = train.groupby('date').size().values\n"
    "        rank = make_xgb_rank()\n"
    "        rank.fit(Xtr, ytr, group=train_groups)\n"
    "\n"
    "        # Predict and generate signals per test date\n"
    "        for date in test_dates:\n"
    "            dt = test[test['date'] == date].copy()\n"
    "            if len(dt) < 3:   # need at least 3 sectors\n"
    "                continue\n"
    "            Xte = dt[features].fillna(medians).fillna(0.).values.astype(float)\n"
    "\n"
    "            dt = dt.copy()\n"
    "            dt['pred_reg']  = reg.predict(Xte)\n"
    "            dt['pred_rank'] = rank.predict(Xte)\n"
    "\n"
    "            mkt_ret = dt['fwd_ret'].mean()   # equal-weight market return\n"
    "\n"
    "            for model_name, pred_col in [('reg','pred_reg'),('rank','pred_rank')]:\n"
    "                dt_s = dt.sort_values(pred_col, ascending=False)\n"
    "                longs  = dt_s.head(long_k)['sector'].tolist()\n"
    "                shorts = dt_s.tail(short_k)['sector'].tolist()\n"
    "\n"
    "                long_ret  = dt_s.head(long_k)['fwd_ret'].mean()\n"
    "                short_ret = dt_s.tail(short_k)['fwd_ret'].mean()\n"
    "                port_ret  = (long_ret - short_ret) / 2   # L/S equal weight\n"
    "                excess    = dt_s.head(long_k)['fwd_excess'].mean() - \\\n"
    "                            dt_s.tail(short_k)['fwd_excess'].mean()\n"
    "\n"
    "                # IC for this date (rank corr prediction vs actual excess)\n"
    "                ic_date = float(spearmanr(dt[pred_col], dt['fwd_excess'])[0]) \\\n"
    "                          if len(dt) >= 4 else np.nan\n"
    "\n"
    "                records.append({\n"
    "                    'date':       date,\n"
    "                    'model':      model_name,\n"
    "                    'port_ret':   port_ret,\n"
    "                    'excess_ret': excess,\n"
    "                    'long_ret':   long_ret,\n"
    "                    'short_ret':  short_ret,\n"
    "                    'mkt_ret':    mkt_ret,\n"
    "                    'ic':         ic_date,\n"
    "                    'longs':  str(longs),\n"
    "                    'shorts': str(shorts),\n"
    "                })\n"
    "        t += fold_dates\n"
    "\n"
    "    return pd.DataFrame(records)\n"
    "\n"
    "print(f'Starting walk-forward: {MIN_TRAIN} train dates, {FOLD_SIZE}-date folds...')\n"
    "wf_results = walk_forward_sector(\n"
    "    panel_clean, ALL_FEATS, TARGET,\n"
    "    min_train_dates=MIN_TRAIN, fold_dates=FOLD_SIZE,\n"
    "    long_k=LONG_K, short_k=SHORT_K\n"
    ")\n"
    "\n"
    "# Split by model\n"
    "res_reg  = wf_results[wf_results['model']=='reg'].set_index('date').sort_index()\n"
    "res_rank = wf_results[wf_results['model']=='rank'].set_index('date').sort_index()\n"
    "\n"
    "print(f'Walk-forward complete: {len(res_reg)} OOS weeks per model')\n"
    "print(f'Date range: {res_reg.index[0].date()} -> {res_reg.index[-1].date()}')"
))

# ── Section 5: IC analysis ────────────────────────────────────────────────────
cells.append(md("---\n## Section 5 -- Information Coefficient Analysis\n\n"
    "IC = Spearman rank correlation between predicted scores and actual excess returns,  \n"
    "computed cross-sectionally within each week.  \n"
    "`ICIR = mean(IC) / std(IC) × √n_weeks` — higher = more consistent signal.\n"))

cells.append(code(
    "def ic_summary(results_df, label):\n"
    "    ics = results_df['ic'].dropna()\n"
    "    t_stat, p_val = ttest_1samp(ics, 0) if len(ics) >= 10 else (np.nan, np.nan)\n"
    "    icir = ics.mean() / ics.std() * np.sqrt(len(ics)) if ics.std() > 0 else np.nan\n"
    "    print(f'{label}:')\n"
    "    print(f'  IC mean:  {ics.mean():+.4f}')\n"
    "    print(f'  IC std:   {ics.std():.4f}')\n"
    "    print(f'  ICIR:     {icir:+.3f}')\n"
    "    print(f'  IC > 0:   {(ics>0).mean():.1%} of weeks')\n"
    "    print(f'  t-stat:   {t_stat:+.3f}  (p={p_val:.4f})')\n"
    "    return {'ic_mean':ics.mean(),'icir':icir,'ic_pos':( ics>0).mean(),'p':p_val}\n"
    "\n"
    "print('IC Analysis\\n' + '='*50)\n"
    "ic_reg  = ic_summary(res_reg,  'XGB-Regressor')\n"
    "print()\n"
    "ic_rank = ic_summary(res_rank, 'XGB-Ranker')\n"
    "\n"
    "# Rolling IC plot\n"
    "fig, axes = plt.subplots(2, 1, figsize=(13, 8), sharex=True)\n"
    "fig.suptitle('Information Coefficient Over Time', fontsize=12)\n"
    "\n"
    "for ax, (res, lbl, col) in zip(axes, [\n"
    "    (res_reg,  'XGB-Regressor', '#1976D2'),\n"
    "    (res_rank, 'XGB-Ranker',    '#FF5722'),\n"
    "]):\n"
    "    ic_ser = res['ic'].dropna()\n"
    "    roll_ic = ic_ser.rolling(52).mean()\n"
    "    ax.bar(ic_ser.index, ic_ser, color=[col if x>0 else '#EF9A9A' for x in ic_ser],\n"
    "           alpha=0.4, width=5)\n"
    "    ax.plot(roll_ic.index, roll_ic, color=col, lw=1.8,\n"
    "            label=f'1yr rolling IC (mean={ic_ser.mean():+.3f})')\n"
    "    ax.axhline(0, color='black', lw=0.7, ls='--')\n"
    "    ax.axhline(0.05, color='green', lw=0.7, ls=':', alpha=0.7)\n"
    "    ax.set_ylabel('IC')\n"
    "    ax.set_title(f'{lbl}: ICIR={ic_ser.mean()/ic_ser.std()*np.sqrt(len(ic_ser)):+.2f}')\n"
    "    ax.legend(fontsize=9)\n"
    "    ax.set_ylim(-0.8, 0.8)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'sector_ic.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/sector_ic.png')"
))

# ── Section 6: Backtest ───────────────────────────────────────────────────────
cells.append(md("---\n## Section 6 -- Backtesting: PnL, Sharpe, Drawdown\n"))

cells.append(code(
    "def apply_tc(ret_series, tc=TC):\n"
    "    \"\"\"Apply 2×TC cost on position flips (simplified: assume 50% turnover/week for L/S).\"\"\"\n"
    "    # Each rebalance: exit 2 longs + 2 shorts, enter 2 new longs + 2 new shorts\n"
    "    # Turnover ≈ fraction of positions that change each week\n"
    "    # Conservative: charge TC every week (full rebalance)\n"
    "    return ret_series - 4 * tc   # 4 positions × TC each week\n"
    "\n"
    "def risk_metrics(rets, freq=52, label=''):\n"
    "    r = pd.Series(rets).dropna()\n"
    "    if len(r) < 10: return {}\n"
    "    ann_ret = (1+r).prod()**(freq/len(r)) - 1\n"
    "    ann_vol = r.std() * np.sqrt(freq)\n"
    "    sharpe  = ann_ret / ann_vol if ann_vol > 0 else np.nan\n"
    "    cum     = (1 + r).cumprod()\n"
    "    max_dd  = ((cum - cum.cummax()) / cum.cummax()).min()\n"
    "    return {'ann_ret':ann_ret,'ann_vol':ann_vol,'sharpe':sharpe,\n"
    "            'max_dd':max_dd,'win_rate':(r>0).mean(),'n':len(r)}\n"
    "\n"
    "# Benchmark: equal-weight all sectors (market return)\n"
    "bnh = res_reg['mkt_ret']   # equal-weight market\n"
    "\n"
    "# Apply TC\n"
    "reg_gross  = res_reg['port_ret']\n"
    "reg_net    = apply_tc(reg_gross)\n"
    "rank_gross = res_rank['port_ret']\n"
    "rank_net   = apply_tc(rank_gross)\n"
    "\n"
    "# Compute metrics\n"
    "print(f'{\"Strategy\":<25} {\"AnnRet\":>8} {\"AnnVol\":>8} {\"Sharpe\":>8} {\"MaxDD\":>8} {\"WinRate\":>8}')\n"
    "print('-' * 70)\n"
    "for rets, lbl in [\n"
    "    (reg_gross,  'XGB-Reg  (gross)'),\n"
    "    (reg_net,    'XGB-Reg  (net TC)'),\n"
    "    (rank_gross, 'XGB-Rank (gross)'),\n"
    "    (rank_net,   'XGB-Rank (net TC)'),\n"
    "    (bnh,        'Equal-Weight BnH'),\n"
    "]:\n"
    "    m = risk_metrics(rets)\n"
    "    print(f'{lbl:<25} {m[\"ann_ret\"]:>8.2%} {m[\"ann_vol\"]:>8.2%} '\n"
    "          f'{m[\"sharpe\"]:>8.2f} {m[\"max_dd\"]:>8.1%} {m[\"win_rate\"]:>8.1%}')"
))

# ── Equity curve ──────────────────────────────────────────────────────────────
cells.append(code(
    "fig, axes = plt.subplots(2, 1, figsize=(13, 9), gridspec_kw={'height_ratios':[3,1]})\n"
    "fig.suptitle('Sector L/S Portfolio: Equity Curves (Long Top-2, Short Bottom-2)', fontsize=12)\n"
    "\n"
    "ax = axes[0]\n"
    "for rets, lbl, col, lw, ls in [\n"
    "    (reg_net,   'XGB-Reg (net TC)',  '#1976D2', 2.0, '-'),\n"
    "    (rank_net,  'XGB-Rank (net TC)', '#FF5722', 2.0, '-'),\n"
    "    (reg_gross, 'XGB-Reg (gross)',   '#90CAF9', 1.0, '--'),\n"
    "    (bnh,       'Equal-Weight BnH',  '#4CAF50', 1.5, ':'),\n"
    "]:\n"
    "    cum = (1 + rets.reindex(res_reg.index)).cumprod()\n"
    "    m   = risk_metrics(rets)\n"
    "    ax.plot(cum.index, cum, lw=lw, ls=ls, color=col,\n"
    "            label=f'{lbl} (Sharpe={m[\"sharpe\"]:+.2f})')\n"
    "ax.axhline(1.0, color='black', lw=0.5, ls=':')\n"
    "ax.set_yscale('log')\n"
    "ax.set_ylabel('Cumulative Return (log)')\n"
    "ax.legend(fontsize=9, loc='upper left')\n"
    "\n"
    "# Drawdown of best model\n"
    "best_ret = rank_net if risk_metrics(rank_net)['sharpe'] > risk_metrics(reg_net)['sharpe'] \\\n"
    "           else reg_net\n"
    "cum_best = (1 + best_ret.reindex(res_reg.index)).cumprod()\n"
    "dd = (cum_best - cum_best.cummax()) / cum_best.cummax()\n"
    "axes[1].fill_between(dd.index, dd, 0, color='#EF5350', alpha=0.5)\n"
    "axes[1].set_ylabel('Drawdown')\n"
    "axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f'{y:.0%}'))\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'sector_equity.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/sector_equity.png')"
))

# ── Annual breakdown ──────────────────────────────────────────────────────────
cells.append(code(
    "# Annual returns\n"
    "best_net = rank_net if risk_metrics(rank_net)['sharpe'] > risk_metrics(reg_net)['sharpe'] \\\n"
    "           else reg_net\n"
    "best_lbl = 'XGB-Rank' if risk_metrics(rank_net)['sharpe'] > risk_metrics(reg_net)['sharpe'] \\\n"
    "           else 'XGB-Reg'\n"
    "\n"
    "annual = pd.DataFrame({\n"
    "    'signal': best_net.groupby(best_net.index.year).apply(lambda r: (1+r).prod()-1),\n"
    "    'bnh':    bnh.groupby(bnh.index.year).apply(lambda r: (1+r).prod()-1),\n"
    "})\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(13, 4))\n"
    "x = range(len(annual))\n"
    "w = 0.35\n"
    "ax.bar([i-w/2 for i in x], annual['signal']*100, width=w,\n"
    "       color=['#1976D2' if v>0 else '#EF5350' for v in annual['signal']],\n"
    "       label=f'{best_lbl} L/S (net TC)')\n"
    "ax.bar([i+w/2 for i in x], annual['bnh']*100, width=w,\n"
    "       color='#78909C', alpha=0.5, label='Equal-Weight BnH')\n"
    "ax.axhline(0, color='black', lw=0.8)\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(annual.index, rotation=45)\n"
    "ax.set_ylabel('Annual Return (%)')\n"
    "ax.set_title('Annual Performance: Sector L/S vs Equal-Weight')\n"
    "ax.legend(fontsize=9)\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'sector_annual.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "pos_yrs = (annual['signal'] > 0).sum()\n"
    "print(f'{\"Year\":>6} {best_lbl[:10]:>10} {\"EW-BnH\":>8}')\n"
    "print('-' * 28)\n"
    "for yr, row in annual.iterrows():\n"
    "    flag = '✓' if row['signal'] > 0 else '✗'\n"
    "    print(f'{yr:>6} {row[\"signal\"]:>9.1%} {flag}  {row[\"bnh\"]:>7.1%}')\n"
    "print(f'\\nPositive years: {pos_yrs}/{len(annual)}')"
))

# ── Section 7: Feature importance ────────────────────────────────────────────
cells.append(md("---\n## Section 7 -- Feature Importance & Regime Attribution\n"))

cells.append(code(
    "# Fit final model on full training data (all but last 2 years)\n"
    "cutoff = sorted(panel_clean['date'].unique())[-104]  # last 2 years = test\n"
    "train_final = panel_clean[panel_clean['date'] < cutoff]\n"
    "\n"
    "medians_final = train_final[ALL_FEATS].median()\n"
    "Xtr_f = train_final[ALL_FEATS].fillna(medians_final).fillna(0.).values.astype(float)\n"
    "ytr_f = train_final[TARGET].values\n"
    "\n"
    "reg_final = make_xgb_reg()\n"
    "reg_final.fit(Xtr_f, ytr_f)\n"
    "\n"
    "# Feature importance\n"
    "imp = pd.Series(reg_final.feature_importances_, index=ALL_FEATS)\n"
    "imp = imp.sort_values(ascending=False)\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(10, 6))\n"
    "top_n = 20\n"
    "imp.head(top_n).plot(kind='barh', ax=ax, color='#1976D2', alpha=0.8)\n"
    "ax.invert_yaxis()\n"
    "ax.set_title(f'Top {top_n} Feature Importances (XGB-Regressor, full train)')\n"
    "ax.set_xlabel('Importance')\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'sector_importance.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('Top 15 features:')\n"
    "for feat, val in imp.head(15).items():\n"
    "    tag = '  [SECTOR]' if feat in SECTOR_FEATS else '  [MACRO]'\n"
    "    print(f'  {feat:<30} {val:.4f}{tag}')"
))

# ── Regime breakdown ──────────────────────────────────────────────────────────
cells.append(code(
    "# Regime performance\n"
    "if 'regime' in panel_clean.columns:\n"
    "    # Get regime per date (mode across sectors, since all same)\n"
    "    regime_map = panel_clean.groupby('date')['regime'].first()\n"
    "    regime_labels = {-1: 'Bull (low VIX)', 0: 'Normal', 1: 'Crisis (high VIX)'}\n"
    "\n"
    "    print(f'{\"Regime\":<22} {\"N\":>5} {\"AnnRet(signal)\":>16} {\"Sharpe\":>8} {\"IC mean\":>8}')\n"
    "    print('-' * 62)\n"
    "    for r, lbl in sorted(regime_labels.items()):\n"
    "        dates_r = regime_map[regime_map == r].index\n"
    "        rets_r  = best_net.reindex(dates_r).dropna()\n"
    "        ics_r   = res_rank.loc[res_rank.index.isin(dates_r), 'ic'].dropna()\n"
    "        if len(rets_r) < 5:\n"
    "            print(f'{lbl:<22} -- insufficient')\n"
    "            continue\n"
    "        m = risk_metrics(rets_r)\n"
    "        print(f'{lbl:<22} {len(rets_r):>5} {m[\"ann_ret\"]:>16.1%} '\n"
    "              f'{m[\"sharpe\"]:>8.2f} {ics_r.mean():>+8.3f}')\n"
    "else:\n"
    "    print('Regime column not available — skipping regime breakdown')"
))

# ── Sector rotation heatmap ───────────────────────────────────────────────────
cells.append(code(
    "# Sector selection frequency: which sectors were most often in top/bottom?\n"
    "from ast import literal_eval\n"
    "\n"
    "long_counts  = {s: 0 for s in SECTORS}\n"
    "short_counts = {s: 0 for s in SECTORS}\n"
    "\n"
    "for _, row in res_rank.iterrows():\n"
    "    try:\n"
    "        longs  = literal_eval(row['longs'])\n"
    "        shorts = literal_eval(row['shorts'])\n"
    "        for s in longs:  long_counts[s]  = long_counts.get(s, 0) + 1\n"
    "        for s in shorts: short_counts[s] = short_counts.get(s, 0) + 1\n"
    "    except:\n"
    "        pass\n"
    "\n"
    "n_weeks = len(res_rank)\n"
    "freq_df = pd.DataFrame({\n"
    "    'Long %':  {s: long_counts[s]/n_weeks  for s in SECTORS},\n"
    "    'Short %': {s: short_counts[s]/n_weeks for s in SECTORS},\n"
    "})\n"
    "freq_df['Net'] = freq_df['Long %'] - freq_df['Short %']\n"
    "freq_df = freq_df.sort_values('Net', ascending=False)\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(9, 4))\n"
    "x = range(len(SECTORS))\n"
    "ax.bar([i-0.2 for i in x], freq_df['Long %']*100,  width=0.4,\n"
    "       color='#2196F3', label='Long')\n"
    "ax.bar([i+0.2 for i in x], freq_df['Short %']*100, width=0.4,\n"
    "       color='#EF5350', label='Short')\n"
    "ax.axhline(LONG_K/len(SECTORS)*100, color='blue',  lw=0.8, ls='--', alpha=0.5)\n"
    "ax.axhline(SHORT_K/len(SECTORS)*100, color='red', lw=0.8, ls='--', alpha=0.5)\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(freq_df.index)\n"
    "ax.set_ylabel('Selection Frequency (%)')\n"
    "ax.set_title('Sector Long/Short Selection Frequency (XGB-Rank)')\n"
    "ax.legend(fontsize=9)\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'sector_rotation.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print(freq_df.round(3))"
))

# ── Section 8: Final Verdict ──────────────────────────────────────────────────
cells.append(md("---\n## Section 8 -- Final Verdict\n"))

cells.append(code(
    "m_reg  = risk_metrics(reg_net)\n"
    "m_rank = risk_metrics(rank_net)\n"
    "m_bnh  = risk_metrics(bnh)\n"
    "\n"
    "score = 0\n"
    "evidence = []\n"
    "def ev(desc, val, thresh, passes, fmt='f'):\n"
    "    global score\n"
    "    if passes: score += 1\n"
    "    sign = '+' if passes else '-'\n"
    "    vs = f'{val:.2%}' if fmt=='pct' else f'{val:.3f}'\n"
    "    evidence.append((sign, desc, vs, thresh))\n"
    "\n"
    "best_m = m_rank if m_rank['sharpe'] > m_reg['sharpe'] else m_reg\n"
    "best_ic = ic_rank if ic_rank['ic_mean'] > ic_reg['ic_mean'] else ic_reg\n"
    "\n"
    "ev('IC mean > 0.05',           best_ic['ic_mean'],   '>0.05', best_ic['ic_mean'] > 0.05)\n"
    "ev('IC t-test p < 0.05',       best_ic['p'],         '<0.05', best_ic['p'] < 0.05)\n"
    "ev('ICIR > 0.5',               best_ic['icir'],      '>0.5',  best_ic['icir'] > 0.5)\n"
    "ev('IC+ fraction > 55%',       best_ic['ic_pos'],    '>55%',  best_ic['ic_pos'] > 0.55, 'pct')\n"
    "ev('Sharpe (net TC) > 0.5',    best_m['sharpe'],     '>0.5',  best_m['sharpe'] > 0.5)\n"
    "ev('Sharpe > Equal-Weight',    best_m['sharpe']-m_bnh['sharpe'],\n"
    "                                '>0',   best_m['sharpe'] > m_bnh['sharpe'])\n"
    "ev('Annual return (net) > 5%', best_m['ann_ret'],    '>5%',   best_m['ann_ret'] > 0.05, 'pct')\n"
    "ev('Max DD > -30%',            best_m['max_dd'],     '>-30%', best_m['max_dd'] > -0.30, 'pct')\n"
    "pos_yr_frac = (annual['signal'] > 0).mean()\n"
    "ev('Positive years > 60%',     pos_yr_frac,          '>60%',  pos_yr_frac > 0.60, 'pct')\n"
    "\n"
    "print('=' * 65)\n"
    "print('SECTOR ALPHA VERDICT')\n"
    "print('=' * 65)\n"
    "print(f'{\"\":>2} {\"Evidence\":<38} {\"Value\":>8} {\"Threshold\":>10}')\n"
    "print('-' * 62)\n"
    "for sign, desc, val, thresh in evidence:\n"
    "    print(f'[{sign}] {desc:<38} {val:>8} {thresh:>10}')\n"
    "print(f'\\nScore: {score}/{len(evidence)}')\n"
    "print()\n"
    "\n"
    "if score >= 7:\n"
    "    verdict = 'REAL SECTOR ALPHA EXISTS'\n"
    "    detail  = 'IC > 0.05, Sharpe > 0.5 after TC, beats benchmark. '\\\n"
    "              'Sector rotation signal is exploitable.'\n"
    "elif score >= 5:\n"
    "    verdict = 'WEAK SECTOR ALPHA'\n"
    "    detail  = 'Some evidence of sector rotation predictability but '\\\n"
    "              'not strong enough for live trading. Needs more features or data.'\n"
    "else:\n"
    "    verdict = 'NO SECTOR ALPHA FOUND'\n"
    "    detail  = 'Cross-sectional prediction does not generate consistent '\\\n"
    "              'positive IC or Sharpe after TC. Sector rotation not predictable '\\\n"
    "              'with current feature set.'\n"
    "\n"
    "print('=' * 65)\n"
    "print(f'VERDICT: {verdict}')\n"
    "print('=' * 65)\n"
    "print(f'\\n{detail}')\n"
    "print(f'\\nBest model: {best_lbl}')\n"
    "print(f'  Sharpe (net TC):  {best_m[\"sharpe\"]:+.3f}')\n"
    "print(f'  Annual return:    {best_m[\"ann_ret\"]:+.2%}')\n"
    "print(f'  IC mean:          {best_ic[\"ic_mean\"]:+.4f}')"
))

# ── Write ──────────────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"},
    },
    "cells": cells,
}
OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, 'w') as f:
    json.dump(nb, f, indent=1)
print(f"Generated: {OUT}")
print(f"Cells: {len(cells)}")
