"""
gen_nb12_multitarget.py -- generate notebooks/eda/12_multitarget_backtest.ipynb

Try 3 paths to find true alpha:
  Path 1: Gold & USD/THB targets (different from SET)
  Path 2: NLP-era deep dive (2022-2025, sentiment features)
  Path 3: Cross-asset signal (predict which asset outperforms)
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '12_multitarget_backtest.ipynb'

def md(source): return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

cells = []

# ── Title ──────────────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 12 -- Multi-Target & Cross-Asset Alpha Search\n"
    "\n"
    "> *SET has no timing alpha. Do Gold or USD/THB? Can we predict which asset wins each week?*\n"
    "\n"
    "**Lesson from NB11:** SET signal = market drift, not timing.  \n"
    "**This notebook tests 3 paths:**\n"
    "\n"
    "| Path | Question |\n"
    "|---|---|\n"
    "| 1. Gold & USD/THB | Do different targets have real timing alpha? |\n"
    "| 2. NLP era (2022-2025) | Does sentiment improve signal when coverage is high? |\n"
    "| 3. Cross-asset | Can we predict which asset (SET/Gold/USD/THB) wins each week? |\n"
))

# ── Setup ──────────────────────────────────────────────────────────────────────
cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "from scipy.stats import spearmanr, ttest_1samp\n"
    "from sklearn.base import clone\n"
    "from xgboost import XGBRegressor\n"
    "warnings.filterwarnings('ignore')\n"
    "np.random.seed(42)\n"
    "\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.dpi': 110, 'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'font.size': 10, 'axes.titlesize': 11,\n"
    "})\n"
    "\n"
    "def ic(pred, true):\n"
    "    mask = np.isfinite(pred) & np.isfinite(true)\n"
    "    return float(spearmanr(pred[mask], true[mask])[0]) if mask.sum() >= 10 else np.nan\n"
    "\n"
    "def risk_metrics(rets, freq=52):\n"
    "    r = pd.Series(rets).dropna()\n"
    "    if len(r) < 10: return {k: np.nan for k in ['ann_ret','sharpe','max_dd','win_rate','n']}\n"
    "    ann_ret = (1+r).prod()**(freq/len(r))-1\n"
    "    ann_vol = r.std()*np.sqrt(freq)\n"
    "    sharpe  = ann_ret/ann_vol if ann_vol>0 else np.nan\n"
    "    cum     = (1+r).cumprod()\n"
    "    max_dd  = ((cum-cum.cummax())/cum.cummax()).min()\n"
    "    return {'ann_ret':ann_ret,'sharpe':sharpe,'max_dd':max_dd,\n"
    "            'win_rate':(r>0).mean(),'n':len(r)}\n"
    "\n"
    "def walk_forward_demeaned(df_all, features, target, model, min_train=156, fold_size=52):\n"
    "    \"\"\"Walk-forward with demeaned target + quantile signal (proper long-short).\"\"\"\n"
    "    feats = [f for f in features if f in df_all.columns]\n"
    "    data  = df_all[feats + [target]].dropna(subset=[target])\n"
    "    n, t, recs = len(data), min_train, []\n"
    "    while t + fold_size <= n:\n"
    "        tr, te   = data.iloc[:t], data.iloc[t:t+fold_size]\n"
    "        med      = tr[feats].median()\n"
    "        Xtr      = tr[feats].fillna(med).fillna(0.).values.astype(float)\n"
    "        Xte      = te[feats].fillna(med).fillna(0.).values.astype(float)\n"
    "        ytr      = tr[target].values\n"
    "        yte      = te[target].values\n"
    "        y_mean   = ytr.mean()\n"
    "        m = clone(model); m.fit(Xtr, ytr - y_mean)\n"
    "        pred_dm  = m.predict(Xte)\n"
    "        # Quantile signal: long top 50%, short bottom 50%\n"
    "        signal   = np.where(pred_dm >= np.median(pred_dm), 1., -1.)\n"
    "        for date, yt, sig, p in zip(te.index, yte, signal, pred_dm):\n"
    "            recs.append({'date':date,'actual':yt,'signal':sig,'pred':p})\n"
    "        t += fold_size\n"
    "    df_r = pd.DataFrame(recs).set_index('date').sort_index()\n"
    "    df_r['ret'] = df_r['signal'] * df_r['actual']\n"
    "    flip = df_r['signal'].diff().abs() > 0\n"
    "    df_r['ret_tc'] = df_r['ret'] - flip * 2 * 0.001  # 0.1% TC\n"
    "    return df_r\n"
    "\n"
    "print('Setup complete.')"
))

# ── Load data ──────────────────────────────────────────────────────────────────
cells.append(md("---\n## Path 1 -- Gold & USD/THB Targets\n\n"
    "Same 11 features, same XGB-Pruned model, same proper long-short (demeaned + quantile).  \n"
    "If SET has no alpha, maybe Gold or USD/THB does.\n"))

cells.append(code(
    "clean = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "\n"
    "TARGETS = {\n"
    "    'SET_index_ret_w_fwd1': 'SET Index',\n"
    "    'gold_ret_w_fwd1':      'Gold',\n"
    "    'USD_THB_ret_w_fwd1':   'USD/THB',\n"
    "}\n"
    "\n"
    "# 11 KEEP features from NB09\n"
    "BASE_FEATS = [\n"
    "    'sp500_ret_w', 'SET_index_rvol_4w', 'sp500_rvol_4w',\n"
    "    'us_10yr_treasury_ret_w', 'oil_ret_d_lag1', 'eem_ret_d_lag1',\n"
    "    'gold_rvol_4w', 'us_2yr_treasury_ret_w', 'oil_ret_w',\n"
    "    'SET_index_ret_w', 'USD_THB_ret_w',\n"
    "]\n"
    "\n"
    "MODEL = XGBRegressor(\n"
    "    n_estimators=50, max_depth=2, learning_rate=0.05,\n"
    "    subsample=0.7, colsample_bytree=0.5,\n"
    "    min_child_weight=20, reg_alpha=1.0, reg_lambda=10.0,\n"
    "    random_state=42, verbosity=0, n_jobs=1\n"
    ")\n"
    "\n"
    "print('Running walk-forward for each target...')\n"
    "target_results = {}\n"
    "for tgt, lbl in TARGETS.items():\n"
    "    df_t = clean.dropna(subset=[tgt]).copy()\n"
    "    # For Gold target: add gold lag features; for USD/THB: add fx features\n"
    "    extra = []\n"
    "    if 'gold' in tgt:\n"
    "        extra = [c for c in clean.columns if 'gold_ret' in c and 'fwd' not in c]\n"
    "    elif 'USD_THB' in tgt:\n"
    "        extra = [c for c in clean.columns if 'USD_THB_ret' in c and 'fwd' not in c] + \\\n"
    "                [c for c in clean.columns if 'dxy' in c]\n"
    "    feats = list(dict.fromkeys(BASE_FEATS + extra))\n"
    "    feats = [f for f in feats if f in clean.columns and f != tgt]\n"
    "    pnl = walk_forward_demeaned(df_t, feats, tgt, MODEL)\n"
    "    target_results[lbl] = {'pnl': pnl, 'feats': feats, 'target': tgt}\n"
    "    m = risk_metrics(pnl['ret_tc'])\n"
    "    fold_ics = []\n"
    "    t_idx = 156\n"
    "    while t_idx + 52 <= len(pnl):\n"
    "        sl = pnl.iloc[t_idx:t_idx+52]\n"
    "        fold_ics.append(ic(sl['pred'].values, sl['actual'].values))\n"
    "        t_idx += 52\n"
    "    ics_valid = [x for x in fold_ics if not np.isnan(x)]\n"
    "    t_stat, p_val = ttest_1samp(ics_valid, 0) if len(ics_valid)>=3 else (np.nan, np.nan)\n"
    "    target_results[lbl]['ic_p'] = p_val\n"
    "    target_results[lbl]['ic_mean'] = np.nanmean(fold_ics)\n"
    "    long_pct = (pnl['signal']==1).mean()\n"
    "    print(f'{lbl:<12}: AnnRet={m[\"ann_ret\"]:>7.2%} Sharpe={m[\"sharpe\"]:>6.2f} '\n"
    "          f'MaxDD={m[\"max_dd\"]:>7.1%} IC={np.nanmean(fold_ics):>+.4f} p={p_val:.3f} Long={long_pct:.0%}')"
))

# ── Plot all 3 targets ─────────────────────────────────────────────────────────
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n"
    "fig.suptitle('Path 1: Cumulative PnL per Target (Demeaned+Quantile, 0.1%TC)', fontsize=12)\n"
    "\n"
    "colors = ['#1976D2', '#FF8F00', '#388E3C']\n"
    "for ax, (lbl, res), col in zip(axes, target_results.items(), colors):\n"
    "    pnl = res['pnl']\n"
    "    cum = (1 + pnl['ret_tc']).cumprod()\n"
    "    bnh = (1 + pnl['actual']).cumprod()\n"
    "    m   = risk_metrics(pnl['ret_tc'])\n"
    "    ax.plot(pnl.index, cum, color=col, lw=2, label=f'Signal ({lbl})')\n"
    "    ax.plot(pnl.index, bnh, color='#E53935', lw=1.2, ls='--', alpha=0.7, label='Buy-and-Hold')\n"
    "    ax.axhline(1.0, color='black', lw=0.5, ls=':')\n"
    "    ax.set_yscale('log')\n"
    "    ax.set_title(f'{lbl}\\nSharpe={m[\"sharpe\"]:+.2f} | IC p={res[\"ic_p\"]:.3f}')\n"
    "    ax.legend(fontsize=8)\n"
    "    ax.set_ylabel('Cum. Return (log)')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'multitarget_pnl.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/multitarget_pnl.png')"
))

# ── Path 2: NLP era ────────────────────────────────────────────────────────────
cells.append(md("---\n## Path 2 -- NLP Era Deep Dive (2022–2025)\n\n"
    "NLP coverage is 47% overall but ~80% in 2022-2025.  \n"
    "Does adding sentiment features help when data is dense enough?\n"))

cells.append(code(
    "NLP_FEATS = [c for c in clean.columns\n"
    "             if any(x in c for x in ['sent_', 'news_vol'])]\n"
    "print(f'NLP features: {NLP_FEATS}')\n"
    "print()\n"
    "\n"
    "# Restrict to 2022-2025 (high NLP coverage period)\n"
    "nlp_era = clean[clean.index >= '2022-01-01'].copy()\n"
    "TARGET_SET = 'SET_index_ret_w_fwd1'\n"
    "nlp_era = nlp_era.dropna(subset=[TARGET_SET])\n"
    "print(f'NLP era: {nlp_era.index[0].date()} -> {nlp_era.index[-1].date()} ({len(nlp_era)} weeks)')\n"
    "\n"
    "# NLP coverage\n"
    "has_nlp = nlp_era[NLP_FEATS].notna().any(axis=1)\n"
    "print(f'Weeks with any NLP data: {has_nlp.mean():.1%}')\n"
    "print()\n"
    "\n"
    "# Compare: Base features vs Base+NLP in NLP era\n"
    "# Use shorter min_train since era is small\n"
    "MIN_TRAIN_NLP = 52  # 1 year min for NLP era\n"
    "FOLD_NLP      = 13  # quarterly folds\n"
    "\n"
    "def walk_forward_nlp_era(df_all, features, target, model, min_train=52, fold_size=13):\n"
    "    feats = [f for f in features if f in df_all.columns]\n"
    "    data  = df_all[feats + [target]].dropna(subset=[target])\n"
    "    n, t, recs = len(data), min_train, []\n"
    "    while t + fold_size <= n:\n"
    "        tr, te = data.iloc[:t], data.iloc[t:t+fold_size]\n"
    "        med    = tr[feats].median()\n"
    "        Xtr    = tr[feats].fillna(med).fillna(0.).values.astype(float)\n"
    "        Xte    = te[feats].fillna(med).fillna(0.).values.astype(float)\n"
    "        ytr, yte = tr[target].values, te[target].values\n"
    "        y_mean = ytr.mean()\n"
    "        m = clone(model); m.fit(Xtr, ytr - y_mean)\n"
    "        pred_dm = m.predict(Xte)\n"
    "        signal  = np.where(pred_dm >= np.median(pred_dm), 1., -1.)\n"
    "        fold_ic = ic(pred_dm, yte)\n"
    "        for date, yt, sig in zip(te.index, yte, signal):\n"
    "            recs.append({'date':date,'actual':yt,'signal':sig,'fold_ic':fold_ic})\n"
    "        t += fold_size\n"
    "    df_r = pd.DataFrame(recs).set_index('date').sort_index()\n"
    "    df_r['ret'] = df_r['signal'] * df_r['actual']\n"
    "    flip = df_r['signal'].diff().abs() > 0\n"
    "    df_r['ret_tc'] = df_r['ret'] - flip * 2 * 0.001\n"
    "    return df_r\n"
    "\n"
    "pnl_base = walk_forward_nlp_era(nlp_era, BASE_FEATS, TARGET_SET, MODEL,\n"
    "                                 min_train=MIN_TRAIN_NLP, fold_size=FOLD_NLP)\n"
    "pnl_nlp  = walk_forward_nlp_era(nlp_era, BASE_FEATS + NLP_FEATS, TARGET_SET, MODEL,\n"
    "                                 min_train=MIN_TRAIN_NLP, fold_size=FOLD_NLP)\n"
    "\n"
    "m_base = risk_metrics(pnl_base['ret_tc'])\n"
    "m_nlp  = risk_metrics(pnl_nlp['ret_tc'])\n"
    "\n"
    "print(f'{\"Model\":<20} {\"AnnRet\":>8} {\"Sharpe\":>8} {\"MaxDD\":>8} {\"WinRate\":>8}')\n"
    "print('-' * 55)\n"
    "print(f'{\"Base (no NLP)\":<20} {m_base[\"ann_ret\"]:>8.2%} {m_base[\"sharpe\"]:>8.2f} '\n"
    "      f'{m_base[\"max_dd\"]:>8.1%} {m_base[\"win_rate\"]:>8.1%}')\n"
    "print(f'{\"Base + NLP\":<20} {m_nlp[\"ann_ret\"]:>8.2%} {m_nlp[\"sharpe\"]:>8.2f} '\n"
    "      f'{m_nlp[\"max_dd\"]:>8.1%} {m_nlp[\"win_rate\"]:>8.1%}')\n"
    "m_bnh = risk_metrics(nlp_era[TARGET_SET].loc[pnl_base.index])\n"
    "print(f'{\"Buy-and-Hold\":<20} {m_bnh[\"ann_ret\"]:>8.2%} {m_bnh[\"sharpe\"]:>8.2f} '\n"
    "      f'{m_bnh[\"max_dd\"]:>8.1%} {m_bnh[\"win_rate\"]:>8.1%}')\n"
    "print()\n"
    "delta = m_nlp['sharpe'] - m_base['sharpe']\n"
    "print(f'NLP delta Sharpe: {delta:+.3f}')\n"
    "print(f'Verdict: NLP {\"HELPS\" if delta > 0.1 else \"does not help enough\" if delta > 0 else \"HURTS\"} in 2022-2025')"
))

# ── Path 2 plot ────────────────────────────────────────────────────────────────
cells.append(code(
    "fig, ax = plt.subplots(figsize=(12, 5))\n"
    "fig.suptitle('Path 2: NLP Era (2022-2025) -- Base vs Base+NLP (Demeaned+Quantile, 0.1%TC)')\n"
    "\n"
    "cum_base = (1 + pnl_base['ret_tc']).cumprod()\n"
    "cum_nlp  = (1 + pnl_nlp['ret_tc']).cumprod()\n"
    "cum_bnh  = (1 + nlp_era[TARGET_SET].loc[pnl_base.index]).cumprod()\n"
    "\n"
    "ax.plot(pnl_base.index, cum_base, color='#1976D2', lw=2, label=f'Base (Sharpe={m_base[\"sharpe\"]:+.2f})')\n"
    "ax.plot(pnl_nlp.index,  cum_nlp,  color='#4CAF50', lw=2, label=f'Base+NLP (Sharpe={m_nlp[\"sharpe\"]:+.2f})')\n"
    "ax.plot(pnl_base.index, cum_bnh,  color='#E53935', lw=1.2, ls='--', alpha=0.7, label='Buy-and-Hold')\n"
    "ax.axhline(1.0, color='black', lw=0.5, ls=':')\n"
    "ax.legend(fontsize=10)\n"
    "ax.set_ylabel('Cumulative Return')\n"
    "ax.set_xlabel('Date')\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'multitarget_nlp_era.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/multitarget_nlp_era.png')"
))

# ── Path 3: Cross-asset ────────────────────────────────────────────────────────
cells.append(md("---\n## Path 3 -- Cross-Asset Signal\n\n"
    "Each week: predict which asset (SET / Gold / USD/THB) has the highest return.  \n"
    "Go Long the predicted winner, Short the predicted loser.  \n"
    "This removes market beta entirely — pure relative alpha.\n"))

cells.append(code(
    "# Cross-asset: predict rank of returns among 3 assets\n"
    "# Strategy: long top-1, short bottom-1 each week\n"
    "\n"
    "ALL_TGTS = list(TARGETS.keys())\n"
    "df_cross = clean.dropna(subset=ALL_TGTS).copy()\n"
    "print(f'Cross-asset dataset: {len(df_cross)} weeks')\n"
    "\n"
    "# Features: combine all BASE_FEATS + asset-specific extras\n"
    "CROSS_FEATS = list(dict.fromkeys(\n"
    "    BASE_FEATS +\n"
    "    [c for c in clean.columns if 'gold_ret' in c and 'fwd' not in c] +\n"
    "    [c for c in clean.columns if 'dxy' in c and 'fwd' not in c]\n"
    "))\n"
    "CROSS_FEATS = [f for f in CROSS_FEATS if f in df_cross.columns]\n"
    "\n"
    "MIN_TRAIN_C, FOLD_C = 156, 52\n"
    "n_c = len(df_cross)\n"
    "t_c = MIN_TRAIN_C\n"
    "cross_recs = []\n"
    "\n"
    "while t_c + FOLD_C <= n_c:\n"
    "    tr_c = df_cross.iloc[:t_c]\n"
    "    te_c = df_cross.iloc[t_c:t_c+FOLD_C]\n"
    "    med_c = tr_c[CROSS_FEATS].median()\n"
    "    Xtr_c = tr_c[CROSS_FEATS].fillna(med_c).fillna(0.).values.astype(float)\n"
    "    Xte_c = te_c[CROSS_FEATS].fillna(med_c).fillna(0.).values.astype(float)\n"
    "\n"
    "    # Train one model per asset (demeaned)\n"
    "    preds_fold = {}\n"
    "    for tgt in ALL_TGTS:\n"
    "        y = tr_c[tgt].values\n"
    "        m = clone(MODEL); m.fit(Xtr_c, y - y.mean())\n"
    "        preds_fold[tgt] = m.predict(Xte_c)\n"
    "\n"
    "    preds_arr = np.stack([preds_fold[t] for t in ALL_TGTS], axis=1)\n"
    "    # Rank predictions each week: 2=best, 0=worst\n"
    "    ranks = preds_arr.argsort(axis=1).argsort(axis=1)  # 0,1,2\n"
    "\n"
    "    for i, (date, row) in enumerate(te_c.iterrows()):\n"
    "        actual_rets = np.array([row[t] for t in ALL_TGTS])\n"
    "        pred_ranks  = ranks[i]  # 0=predicted worst, 2=predicted best\n"
    "        winner_idx  = np.argmax(pred_ranks)\n"
    "        loser_idx   = np.argmin(pred_ranks)\n"
    "        # Long winner, short loser\n"
    "        long_ret  =  actual_rets[winner_idx]\n"
    "        short_ret = -actual_rets[loser_idx]\n"
    "        cross_ret = (long_ret + short_ret) / 2  # equal-weight\n"
    "        cross_recs.append({\n"
    "            'date': date,\n"
    "            'cross_ret': cross_ret,\n"
    "            'winner': list(TARGETS.values())[winner_idx],\n"
    "            'loser':  list(TARGETS.values())[loser_idx],\n"
    "            'long_ret': long_ret, 'short_ret': short_ret,\n"
    "        })\n"
    "    t_c += FOLD_C\n"
    "\n"
    "cross_df = pd.DataFrame(cross_recs).set_index('date')\n"
    "m_cross = risk_metrics(cross_df['cross_ret'])\n"
    "\n"
    "print(f'Cross-asset OOS: {cross_df.index[0].date()} -> {cross_df.index[-1].date()}')\n"
    "print(f'Weeks: {len(cross_df)}')\n"
    "print()\n"
    "print(f'Cross-asset strategy:')\n"
    "print(f'  Ann. Return: {m_cross[\"ann_ret\"]:>8.2%}')\n"
    "print(f'  Sharpe:      {m_cross[\"sharpe\"]:>8.2f}')\n"
    "print(f'  Max DD:      {m_cross[\"max_dd\"]:>8.1%}')\n"
    "print(f'  Win Rate:    {m_cross[\"win_rate\"]:>8.1%}')\n"
    "print()\n"
    "print('Most common winner predictions:')\n"
    "print(cross_df['winner'].value_counts())"
))

# ── Cross-asset plot ───────────────────────────────────────────────────────────
cells.append(code(
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('Path 3: Cross-Asset Long-Short Signal (Long Best, Short Worst)', fontsize=12)\n"
    "\n"
    "cum_cross = (1 + cross_df['cross_ret']).cumprod()\n"
    "ax1.plot(cross_df.index, cum_cross, color='#9C27B0', lw=2, label='Cross-asset L/S')\n"
    "ax1.axhline(1.0, color='black', lw=0.5, ls=':')\n"
    "ax1.set_yscale('log')\n"
    "ax1.set_title(f'Cumulative Return\\nSharpe={m_cross[\"sharpe\"]:+.2f} | '\n"
    "              f'AnnRet={m_cross[\"ann_ret\"]:+.2%}')\n"
    "ax1.legend(fontsize=9)\n"
    "ax1.set_ylabel('Cumulative Return (log)')\n"
    "\n"
    "# Win rate by year\n"
    "cross_df['year'] = cross_df.index.year\n"
    "annual_cross = cross_df.groupby('year').apply(\n"
    "    lambda g: pd.Series({'ret': (1+g['cross_ret']).prod()-1,\n"
    "                         'win': (g['cross_ret']>0).mean()})\n"
    ").reset_index()\n"
    "bar_cols = ['#9C27B0' if r>0 else '#EF5350' for r in annual_cross['ret']]\n"
    "ax2.bar(range(len(annual_cross)), annual_cross['ret']*100, color=bar_cols)\n"
    "ax2.axhline(0, color='black', lw=0.8)\n"
    "ax2.set_xticks(range(len(annual_cross)))\n"
    "ax2.set_xticklabels(annual_cross['year'], rotation=45)\n"
    "ax2.set_ylabel('Annual Return (%)')\n"
    "ax2.set_title('Annual Return by Year')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'multitarget_crossasset.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/multitarget_crossasset.png')"
))

# ── Final comparison ───────────────────────────────────────────────────────────
cells.append(md("---\n## Final Comparison: All Paths\n"))

cells.append(code(
    "print('=' * 70)\n"
    "print('MULTI-TARGET ALPHA SEARCH -- FINAL SUMMARY')\n"
    "print('=' * 70)\n"
    "print()\n"
    "print(f'{\"Strategy\":<30} {\"AnnRet\":>8} {\"Sharpe\":>8} {\"MaxDD\":>8} {\"IC p\":>8}')\n"
    "print('-' * 62)\n"
    "\n"
    "# Path 1: individual targets\n"
    "for lbl, res in target_results.items():\n"
    "    m = risk_metrics(res['pnl']['ret_tc'])\n"
    "    p = res['ic_p']\n"
    "    sig = ' *' if (not np.isnan(p) and p < 0.10) else ''\n"
    "    print(f'{f\"L/S {lbl}\":<30} {m[\"ann_ret\"]:>8.2%} {m[\"sharpe\"]:>8.2f} '\n"
    "          f'{m[\"max_dd\"]:>8.1%} {p:>8.3f}{sig}')\n"
    "\n"
    "# Path 2: NLP\n"
    "print(f'{\"L/S SET + NLP (2022-25)\":<30} {m_nlp[\"ann_ret\"]:>8.2%} {m_nlp[\"sharpe\"]:>8.2f} '\n"
    "      f'{m_nlp[\"max_dd\"]:>8.1%} {\"--\":>8}')\n"
    "\n"
    "# Path 3: cross-asset\n"
    "print(f'{\"Cross-asset L/S\":<30} {m_cross[\"ann_ret\"]:>8.2%} {m_cross[\"sharpe\"]:>8.2f} '\n"
    "      f'{m_cross[\"max_dd\"]:>8.1%} {\"--\":>8}')\n"
    "\n"
    "print('-' * 62)\n"
    "print('* = IC p < 0.10')\n"
    "print()\n"
    "\n"
    "# Find best\n"
    "all_sharpes = {\n"
    "    **{f'L/S {lbl}': risk_metrics(res[\"pnl\"][\"ret_tc\"])[\"sharpe\"]\n"
    "       for lbl, res in target_results.items()},\n"
    "    'L/S SET + NLP (2022-25)': m_nlp['sharpe'],\n"
    "    'Cross-asset L/S': m_cross['sharpe'],\n"
    "}\n"
    "best_strat = max(all_sharpes, key=all_sharpes.get)\n"
    "print(f'Best strategy: {best_strat} (Sharpe={all_sharpes[best_strat]:.3f})')\n"
    "print()\n"
    "\n"
    "# Verdict per path\n"
    "print('PATH VERDICTS:')\n"
    "for lbl, res in target_results.items():\n"
    "    m = risk_metrics(res['pnl']['ret_tc'])\n"
    "    p = res['ic_p']\n"
    "    if m['sharpe'] > 0.4 and (np.isnan(p) or p < 0.10):\n"
    "        v = 'ALPHA EXISTS'\n"
    "    elif m['sharpe'] > 0.2:\n"
    "        v = 'weak signal'\n"
    "    else:\n"
    "        v = 'no alpha'\n"
    "    print(f'  Path 1 {lbl:<12}: {v} (Sharpe={m[\"sharpe\"]:+.2f})')\n"
    "nlp_v = 'HELPS' if m_nlp['sharpe'] > m_base['sharpe'] + 0.05 else 'marginal'\n"
    "print(f'  Path 2 NLP era      : NLP {nlp_v} (ΔSharpe={m_nlp[\"sharpe\"]-m_base[\"sharpe\"]:+.2f})')\n"
    "cross_v = 'ALPHA EXISTS' if m_cross['sharpe'] > 0.4 else ('weak' if m_cross['sharpe'] > 0.1 else 'no alpha')\n"
    "print(f'  Path 3 Cross-asset  : {cross_v} (Sharpe={m_cross[\"sharpe\"]:+.2f})')"
))

# ── Write ──────────────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"},
    },
    "cells": cells,
}
OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, 'w') as f:
    json.dump(nb, f, indent=1)
print(f"Generated: {OUT}")
print(f"Cells: {len(cells)}")
