"""
gen_nb08_eda.py -- generate notebooks/eda/08_alpha_validation.ipynb

4-task signal robustness analysis:
  Task 1: Stability Hardening  (multiple fold sizes, regime breakdown, IC consistency)
  Task 2: Feature Pruning      (permutation importance, drop-one, collinearity)
  Task 3: Model Simplification (Ridge vs shallow XGBoost, complexity tradeoff)
  Task 4: Strong Signal Test   (top-k features, re-run walk-forward, final verdict)

Conservative lens: assume noise unless proven otherwise.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / 'notebooks' / 'eda' / '08_alpha_validation.ipynb'

def md(source): return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": source}

cells = []

# ── Cell 0: Title ──────────────────────────────────────────────────────────────
cells.append(md(
    "# Notebook 08 -- Signal Robustness & Feature Pruning\n"
    "\n"
    "> *Is the alpha signal REAL or NOISE? Does simplification help or hurt?*\n"
    "\n"
    "**Philosophy:** Conservative. Assume most signals are noise unless proven otherwise.\n"
    "This notebook does NOT optimize — it stress-tests.\n"
    "\n"
    "| Task | Question |\n"
    "|---|---|\n"
    "| 1. Stability Hardening | Does IC hold across fold sizes and regimes? |\n"
    "| 2. Feature Pruning | Which features survive OOS? What should be dropped? |\n"
    "| 3. Model Simplification | Ridge vs shallow XGB — is complexity justified? |\n"
    "| 4. Strong Signal Test | Top-k only: is the core signal robust or fragile? |\n"
    "| Final Verdict | Definitive conclusion with full evidence table |\n"
))

# ── Cell 1: Setup ──────────────────────────────────────────────────────────────
cells.append(code(
    "from pathlib import Path\n"
    "import warnings\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "from scipy.stats import spearmanr, ttest_1samp\n"
    "from sklearn.base import BaseEstimator, RegressorMixin, clone\n"
    "from sklearn.linear_model import Ridge\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.pipeline import Pipeline\n"
    "from xgboost import XGBRegressor\n"
    "warnings.filterwarnings('ignore')\n"
    "np.random.seed(42)\n"
    "\n"
    "ROOT = Path('../..')\n"
    "PROC = ROOT / 'data' / 'processed'\n"
    "FIGS = Path('figs')\n"
    "FIGS.mkdir(exist_ok=True)\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.dpi': 110, 'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'font.size': 10, 'axes.titlesize': 11,\n"
    "})\n"
    "\n"
    "# ── Metrics ──────────────────────────────────────────────────────────────────\n"
    "def dir_acc(y_pred, y_true):\n"
    "    return float(np.mean(np.sign(y_pred) == np.sign(y_true)))\n"
    "\n"
    "def ic(y_pred, y_true):\n"
    "    mask = np.isfinite(y_pred) & np.isfinite(y_true)\n"
    "    if mask.sum() < 10: return np.nan\n"
    "    return float(spearmanr(y_pred[mask], y_true[mask])[0])\n"
    "\n"
    "def icir(fold_ics):\n"
    "    ics = [x for x in fold_ics if not np.isnan(x)]\n"
    "    if len(ics) < 3: return np.nan\n"
    "    return float(np.mean(ics) / np.std(ics) * np.sqrt(len(ics)))\n"
    "\n"
    "print('Setup complete.')"
))

# ── Cell 2: Load data ──────────────────────────────────────────────────────────
cells.append(md("---\n## Setup: Data & Feature Groups\n"))

cells.append(code(
    "clean = pd.read_csv(PROC / 'unified_weekly_clean.csv', index_col=0, parse_dates=True)\n"
    "print(f'Dataset: {clean.shape[0]} rows x {clean.shape[1]} cols')\n"
    "print(f'Date range: {clean.index[0].date()} -> {clean.index[-1].date()}')\n"
    "\n"
    "TARGET = 'SET_index_ret_w_fwd1'\n"
    "df = clean.dropna(subset=[TARGET]).copy()\n"
    "print(f'Rows after dropping NaN target: {len(df)}')\n"
    "\n"
    "# ── Feature Groups (mirror NB06 definitions) ─────────────────────────────────\n"
    "LAGS   = [c for c in df.columns if '_ret_d_lag1' in c]\n"
    "MARKET = [c for c in df.columns if '_ret_w' in c and '_fwd1' not in c] + \\\n"
    "         [c for c in df.columns if '_rvol_4w' in c]\n"
    "REGIME = [c for c in ['regime', 'vix_z', 'yield_curve_slope'] if c in df.columns]\n"
    "NLP    = [c for c in df.columns if any(x in c for x in ['sent_', 'news_vol'])]\n"
    "\n"
    "# Primary candidate set: market-timing features (no macro, no NLP)\n"
    "LAG_MARKET = list(dict.fromkeys(LAGS + MARKET + REGIME))\n"
    "\n"
    "print(f'\\nFeature groups:')\n"
    "for name, g in [('LAGS', LAGS), ('MARKET', MARKET), ('REGIME', REGIME),\n"
    "                ('NLP', NLP), ('LAG_MARKET', LAG_MARKET)]:\n"
    "    print(f'  {name:<12}: {len(g)} features')\n"
    "print(f'\\nTarget: {TARGET}')"
))

# ── Cell 3: Walk-forward helper ────────────────────────────────────────────────
cells.append(code(
    "def walk_forward(df_all, features, target_col, model,\n"
    "                 min_train=156, fold_size=52):\n"
    "    \"\"\"Expanding-window walk-forward; returns list of per-fold dicts.\"\"\"\n"
    "    feats = [f for f in features if f in df_all.columns]\n"
    "    data = df_all[feats + [target_col]].dropna(subset=[target_col])\n"
    "    n = len(data)\n"
    "    folds, t = [], min_train\n"
    "\n"
    "    while t + fold_size <= n:\n"
    "        train = data.iloc[:t]\n"
    "        test  = data.iloc[t:t+fold_size]\n"
    "        medians = train[feats].median()\n"
    "        Xtr = train[feats].fillna(medians).fillna(0.0).values.astype(float)\n"
    "        Xte = test[feats].fillna(medians).fillna(0.0).values.astype(float)\n"
    "        ytr = train[target_col].values\n"
    "        yte = test[target_col].values\n"
    "\n"
    "        m = clone(model)\n"
    "        m.fit(Xtr, ytr)\n"
    "        pred = m.predict(Xte)\n"
    "\n"
    "        folds.append({\n"
    "            'fold': len(folds),\n"
    "            'n_train': t,\n"
    "            'test_start': test.index[0],\n"
    "            'test_end':   test.index[-1],\n"
    "            'y_true': yte,\n"
    "            'y_pred': pred,\n"
    "            'da':  dir_acc(pred, yte),\n"
    "            'ic':  ic(pred, yte),\n"
    "        })\n"
    "        t += fold_size\n"
    "    return folds\n"
    "\n"
    "def summary_stats(folds):\n"
    "    das = [f['da'] for f in folds]\n"
    "    ics = [f['ic'] for f in folds]\n"
    "    ics_valid = [x for x in ics if not np.isnan(x)]\n"
    "    t_stat, p_val = ttest_1samp(ics_valid, 0) if len(ics_valid) >= 3 else (np.nan, np.nan)\n"
    "    return {\n"
    "        'n_folds': len(folds),\n"
    "        'da_mean': np.mean(das),\n"
    "        'ic_mean': np.mean(ics_valid) if ics_valid else np.nan,\n"
    "        'ic_std':  np.std(ics_valid)  if ics_valid else np.nan,\n"
    "        'icir':    icir(ics),\n"
    "        'ic_pos_frac': np.mean([x > 0 for x in ics_valid]) if ics_valid else np.nan,\n"
    "        'ic_tstat': t_stat,\n"
    "        'ic_pval':  p_val,\n"
    "    }\n"
    "\n"
    "print('Walk-forward helpers ready.')"
))

# ── Cell 4: Task 1 header ──────────────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## Task 1 -- Stability Hardening\n"
    "\n"
    "**Question:** Does the IC hold when we vary fold size (quarterly / annual / biennial)?  \n"
    "If the signal is real, it should appear robustly at multiple time scales.\n"
    "\n"
    "Three fold sizes tested: **26w** (semi-annual), **52w** (annual), **104w** (biennial).  \n"
    "Model: Ridge on LAG_MARKET features (same as NB06 baseline).\n"
))

# ── Cell 5: Multi-fold-size walk-forward ───────────────────────────────────────
cells.append(code(
    "FOLD_SIZES  = [26, 52, 104]\n"
    "FOLD_LABELS = ['26w (semi-annual)', '52w (annual)', '104w (biennial)']\n"
    "MIN_TRAIN   = 156\n"
    "\n"
    "ridge_base = Pipeline([('scaler', StandardScaler()),\n"
    "                       ('ridge', Ridge(alpha=100.0))])\n"
    "\n"
    "stability_results = {}\n"
    "for fs, lbl in zip(FOLD_SIZES, FOLD_LABELS):\n"
    "    folds = walk_forward(df, LAG_MARKET, TARGET, ridge_base,\n"
    "                         min_train=MIN_TRAIN, fold_size=fs)\n"
    "    stats = summary_stats(folds)\n"
    "    stability_results[fs] = {'folds': folds, 'stats': stats, 'label': lbl}\n"
    "    s = stats\n"
    "    print(f'Fold={fs:3d}w | n={s[\"n_folds\"]:2d} | '\n"
    "          f'DirAcc={s[\"da_mean\"]:.3f} | IC={s[\"ic_mean\"]:+.4f} | '\n"
    "          f'ICIR={s[\"icir\"]:+.3f} | IC+%={s[\"ic_pos_frac\"]:.1%} | '\n"
    "          f'p={s[\"ic_pval\"]:.3f}')"
))

# ── Cell 6: Stability plot ─────────────────────────────────────────────────────
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n"
    "fig.suptitle('Task 1: IC Distribution Across Fold Sizes (Ridge, LAG_MARKET)', fontsize=12)\n"
    "\n"
    "colors = ['#2196F3', '#FF5722', '#4CAF50']\n"
    "for ax, fs, col in zip(axes, FOLD_SIZES, colors):\n"
    "    res = stability_results[fs]\n"
    "    folds = res['folds']\n"
    "    stats = res['stats']\n"
    "    fold_ics = [f['ic'] for f in folds]\n"
    "    fold_nums = [f['fold'] for f in folds]\n"
    "\n"
    "    ax.bar(fold_nums, fold_ics, color=[col if x > 0 else '#EF9A9A' for x in fold_ics],\n"
    "           alpha=0.7, edgecolor='none')\n"
    "    ax.axhline(0, color='black', lw=0.8, ls='--')\n"
    "    ax.axhline(stats['ic_mean'], color=col, lw=1.5,\n"
    "               label=f'Mean IC={stats[\"ic_mean\"]:+.3f}')\n"
    "    ax.set_title(f'Fold Size = {fs}w\\nICIR={stats[\"icir\"]:+.2f}, p={stats[\"ic_pval\"]:.3f}, '\n"
    "                 f'IC+%={stats[\"ic_pos_frac\"]:.0%}')\n"
    "    ax.set_xlabel('Fold #')\n"
    "    ax.set_ylabel('IC')\n"
    "    ax.legend(fontsize=9)\n"
    "    ax.set_ylim(-0.25, 0.25)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'stability_fold_sizes.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/stability_fold_sizes.png')"
))

# ── Cell 7: Regime stability ───────────────────────────────────────────────────
cells.append(md(
    "### Task 1b -- IC Stability by Regime\n\n"
    "A robust signal should not be entirely regime-dependent.  \n"
    "Using 52w folds; split OOS observations by VIX regime.\n"
))

cells.append(code(
    "# Use annual folds (52w) for regime breakdown\n"
    "folds_52 = stability_results[52]['folds']\n"
    "\n"
    "# Aggregate all OOS predictions + true values with their regime labels\n"
    "oos_preds, oos_true, oos_regime = [], [], []\n"
    "for f in folds_52:\n"
    "    n = len(f['y_true'])\n"
    "    # Align test window with df\n"
    "    mask = (df.index >= f['test_start']) & (df.index <= f['test_end'])\n"
    "    sub = df.loc[mask]\n"
    "    oos_preds.extend(f['y_pred'])\n"
    "    oos_true.extend(f['y_true'])\n"
    "    if 'regime' in sub.columns:\n"
    "        oos_regime.extend(sub['regime'].values)\n"
    "    else:\n"
    "        oos_regime.extend([np.nan]*n)\n"
    "\n"
    "oos_df = pd.DataFrame({\n"
    "    'pred': oos_preds, 'true': oos_true, 'regime': oos_regime\n"
    "})\n"
    "\n"
    "regime_labels = {-1: 'Bull (low VIX)', 0: 'Normal', 1: 'Crisis (high VIX)'}\n"
    "print(f'Total OOS observations: {len(oos_df)}')\n"
    "print()\n"
    "print(f'{\"Regime\":<22} {\"N\":>6} {\"DirAcc\":>8} {\"IC\":>8}')\n"
    "print('-' * 48)\n"
    "for r, lbl in sorted(regime_labels.items()):\n"
    "    sub = oos_df[oos_df['regime'] == r].dropna()\n"
    "    if len(sub) < 10:\n"
    "        print(f'{lbl:<22} {len(sub):>6} -- (insufficient data)')\n"
    "        continue\n"
    "    da  = dir_acc(sub['pred'].values, sub['true'].values)\n"
    "    ic_ = ic(sub['pred'].values, sub['true'].values)\n"
    "    print(f'{lbl:<22} {len(sub):>6} {da:>8.3f} {ic_:>+8.4f}')"
))

# ── Cell 8: IC consistency across time ────────────────────────────────────────
cells.append(code(
    "# Rolling IC across folds (using 52w folds) -- signal decay test\n"
    "fold_dates = [f['test_start'] for f in folds_52]\n"
    "fold_ics   = [f['ic'] for f in folds_52]\n"
    "fold_das   = [f['da'] for f in folds_52]\n"
    "\n"
    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True)\n"
    "fig.suptitle('Task 1c: IC & DirAcc Over Time (52w Folds, Ridge LAG_MARKET)', fontsize=12)\n"
    "\n"
    "bar_colors = ['#2196F3' if x > 0 else '#EF5350' for x in fold_ics]\n"
    "ax1.bar(range(len(fold_ics)), fold_ics, color=bar_colors, alpha=0.8)\n"
    "ax1.axhline(0, color='black', lw=0.8, ls='--')\n"
    "ax1.axhline(np.nanmean(fold_ics), color='navy', lw=1.5, ls='-',\n"
    "            label=f'Mean IC={np.nanmean(fold_ics):+.3f}')\n"
    "ax1.set_ylabel('IC per Fold')\n"
    "ax1.legend(fontsize=9)\n"
    "ax1.set_title(f'IC positive in {np.mean([x>0 for x in fold_ics if not np.isnan(x)]):.0%} of folds')\n"
    "\n"
    "ax2.bar(range(len(fold_das)), fold_das, color='#78909C', alpha=0.7)\n"
    "ax2.axhline(0.5, color='black', lw=0.8, ls='--')\n"
    "ax2.axhline(np.mean(fold_das), color='navy', lw=1.5,\n"
    "            label=f'Mean DA={np.mean(fold_das):.3f}')\n"
    "ax2.set_ylabel('DirAcc per Fold')\n"
    "ax2.set_xlabel('Fold (chronological)')\n"
    "ax2.legend(fontsize=9)\n"
    "ax2.set_ylim(0.3, 0.75)\n"
    "\n"
    "ticks_step = max(1, len(fold_dates)//8)\n"
    "ax2.set_xticks(range(0, len(fold_dates), ticks_step))\n"
    "ax2.set_xticklabels([str(d.year) for d in fold_dates[::ticks_step]], rotation=45)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'stability_time.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/stability_time.png')"
))

# ── Cell 9: Task 2 header ─────────────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## Task 2 -- Feature Pruning\n"
    "\n"
    "**Goal:** Remove redundant, collinear, or OOS-useless features.  \n"
    "A pruned model is less likely to overfit noise.\n"
    "\n"
    "Steps:\n"
    "1. **Multicollinearity filter** — drop features with |corr| > 0.80 (keep lower-index)\n"
    "2. **Permutation importance** — shuffle one feature at a time, measure IC drop (walk-forward)\n"
    "3. **Drop-one analysis** — refit without each feature, measure DirAcc change\n"
    "4. **IC fold stability** — what fraction of 52w folds has positive IC for each feature?\n"
    "5. **Pruning decision** — KEEP / REMOVE verdict per feature\n"
))

# ── Cell 10: Multicollinearity filter ────────────────────────────────────────
cells.append(code(
    "CORR_THRESH = 0.80\n"
    "\n"
    "# Compute correlation on full available data (before train/test split)\n"
    "feat_df = df[LAG_MARKET].fillna(df[LAG_MARKET].median())\n"
    "corr_mat = feat_df.corr().abs()\n"
    "\n"
    "# Greedy: keep first feature, drop anything that is >.80 correlated with it\n"
    "to_drop_corr = set()\n"
    "features_ordered = list(LAG_MARKET)\n"
    "for i, fi in enumerate(features_ordered):\n"
    "    if fi in to_drop_corr: continue\n"
    "    for fj in features_ordered[i+1:]:\n"
    "        if fj in to_drop_corr: continue\n"
    "        if corr_mat.loc[fi, fj] > CORR_THRESH:\n"
    "            to_drop_corr.add(fj)\n"
    "\n"
    "LAG_MARKET_DECORR = [f for f in LAG_MARKET if f not in to_drop_corr]\n"
    "\n"
    "print(f'Collinearity filter (|r| > {CORR_THRESH}):')\n"
    "if to_drop_corr:\n"
    "    for f in sorted(to_drop_corr):\n"
    "        partners = [fi for fi in LAG_MARKET if fi not in to_drop_corr and\n"
    "                    corr_mat.loc[fi, f] > CORR_THRESH]\n"
    "        print(f'  DROP {f:<35} (corr>{CORR_THRESH:.2f} with: {partners})')\n"
    "else:\n"
    "    print('  No features dropped by collinearity filter.')\n"
    "print(f'\\nRemaining: {len(LAG_MARKET)} -> {len(LAG_MARKET_DECORR)} features')"
))

# ── Cell 11: Permutation importance ───────────────────────────────────────────
cells.append(code(
    "# Permutation importance: shuffle one feature at a time, measure IC drop\n"
    "# Run on the 52w walk-forward folds using full LAG_MARKET (post-collinearity filter)\n"
    "\n"
    "N_PERM = 100\n"
    "BASE_FOLDS = walk_forward(df, LAG_MARKET_DECORR, TARGET, clone(ridge_base),\n"
    "                          min_train=MIN_TRAIN, fold_size=52)\n"
    "base_ics = [f['ic'] for f in BASE_FOLDS]\n"
    "base_ic_mean = np.nanmean(base_ics)\n"
    "print(f'Baseline (all features): mean IC = {base_ic_mean:+.4f}')\n"
    "print()\n"
    "\n"
    "perm_importance = {}\n"
    "for feat in LAG_MARKET_DECORR:\n"
    "    feat_idx = LAG_MARKET_DECORR.index(feat)\n"
    "    perm_ics = []\n"
    "    for _ in range(N_PERM):\n"
    "        folds_perm = []\n"
    "        for f in BASE_FOLDS:\n"
    "            # Rebuild test predictions with the feature shuffled\n"
    "            Xte_perm = np.array([BASE_FOLDS[BASE_FOLDS.index(f)]['y_pred']])  # placeholder\n"
    "            break\n"
    "        break  # rewrite below with full approach\n"
    "\n"
    "# Full permutation importance: re-run walk-forward with feature shuffled\n"
    "perm_importance = {}\n"
    "all_feats = LAG_MARKET_DECORR\n"
    "\n"
    "for feat in all_feats:\n"
    "    feat_idx = all_feats.index(feat)\n"
    "    perm_ic_drops = []\n"
    "\n"
    "    for trial in range(N_PERM):\n"
    "        # Run walk-forward with this feature column shuffled\n"
    "        data_perm = df[all_feats + [TARGET]].dropna(subset=[TARGET]).copy()\n"
    "        data_perm[feat] = data_perm[feat].sample(frac=1, random_state=trial).values\n"
    "\n"
    "        perm_ics_trial = []\n"
    "        n = len(data_perm)\n"
    "        t = MIN_TRAIN\n"
    "        while t + 52 <= n:\n"
    "            train = data_perm.iloc[:t]\n"
    "            test  = data_perm.iloc[t:t+52]\n"
    "            medians = train[all_feats].median()\n"
    "            Xtr = train[all_feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "            Xte = test[all_feats].fillna(medians).fillna(0.).values.astype(float)\n"
    "            ytr = train[TARGET].values\n"
    "            yte = test[TARGET].values\n"
    "            m = clone(ridge_base)\n"
    "            m.fit(Xtr, ytr)\n"
    "            perm_ics_trial.append(ic(m.predict(Xte), yte))\n"
    "            t += 52\n"
    "\n"
    "        perm_ic_drops.append(base_ic_mean - np.nanmean(perm_ics_trial))\n"
    "\n"
    "    perm_importance[feat] = np.mean(perm_ic_drops)\n"
    "\n"
    "perm_df = pd.Series(perm_importance).sort_values(ascending=False)\n"
    "print(f'Top permutation importance (IC drop when feature shuffled):')\n"
    "for f, v in perm_df.head(12).items():\n"
    "    tag = ' <-- KEY' if v > 0.002 else ''\n"
    "    print(f'  {f:<35} {v:+.5f}{tag}')"
))

# ── Cell 12: Drop-one analysis ────────────────────────────────────────────────
cells.append(code(
    "# Drop-one-feature: refit model without each feature, measure DirAcc change\n"
    "base_das = [f['da'] for f in BASE_FOLDS]\n"
    "base_da_mean = np.mean(base_das)\n"
    "print(f'Baseline DirAcc (all features): {base_da_mean:.4f}')\n"
    "print()\n"
    "\n"
    "drop_one = {}\n"
    "for feat in all_feats:\n"
    "    feats_minus = [f for f in all_feats if f != feat]\n"
    "    folds_drop = walk_forward(df, feats_minus, TARGET, clone(ridge_base),\n"
    "                              min_train=MIN_TRAIN, fold_size=52)\n"
    "    drop_one[feat] = np.mean([f['da'] for f in folds_drop])\n"
    "\n"
    "drop_df = pd.Series({f: base_da_mean - v for f, v in drop_one.items()})\n"
    "drop_df = drop_df.sort_values(ascending=False)\n"
    "\n"
    "print(f'{\"Feature\":<35} {\"DirAcc w/o\":>12} {\"Impact\":>10}')\n"
    "print('-' * 60)\n"
    "for feat, impact in drop_df.items():\n"
    "    da_without = drop_one[feat]\n"
    "    tag = ' <-- HELPFUL' if impact > 0.003 else (' <-- HARMFUL' if impact < -0.003 else '')\n"
    "    print(f'{feat:<35} {da_without:>12.4f} {impact:>+10.5f}{tag}')"
))

# ── Cell 13: Feature IC stability per fold ────────────────────────────────────
cells.append(code(
    "# Per-feature IC fold stability: what % of folds has positive IC?\n"
    "# Use Spearman corr between each feature and future SET return, per fold\n"
    "\n"
    "feature_fold_ics = {f: [] for f in all_feats}\n"
    "\n"
    "n_data = len(df.dropna(subset=[TARGET]))\n"
    "data_stable = df[all_feats + [TARGET]].dropna(subset=[TARGET])\n"
    "t = MIN_TRAIN\n"
    "while t + 52 <= n_data:\n"
    "    test_slice = data_stable.iloc[t:t+52]\n"
    "    for feat in all_feats:\n"
    "        sub = test_slice[[feat, TARGET]].dropna()\n"
    "        if len(sub) >= 10:\n"
    "            ic_val = spearmanr(sub[feat], sub[TARGET])[0]\n"
    "        else:\n"
    "            ic_val = np.nan\n"
    "        feature_fold_ics[feat].append(ic_val)\n"
    "    t += 52\n"
    "\n"
    "stability_table = []\n"
    "for feat in all_feats:\n"
    "    fics = [x for x in feature_fold_ics[feat] if not np.isnan(x)]\n"
    "    if not fics:\n"
    "        stability_table.append({'feature': feat, 'ic_mean': np.nan,\n"
    "                                'ic_pos_frac': np.nan, 'n_folds': 0})\n"
    "    else:\n"
    "        stability_table.append({\n"
    "            'feature': feat,\n"
    "            'ic_mean': np.mean(fics),\n"
    "            'ic_pos_frac': np.mean([x > 0 for x in fics]),\n"
    "            'n_folds': len(fics),\n"
    "        })\n"
    "\n"
    "stab_df = pd.DataFrame(stability_table).set_index('feature')\n"
    "stab_df['perm_imp'] = stab_df.index.map(lambda f: perm_df.get(f, np.nan))\n"
    "stab_df['drop_one_impact'] = stab_df.index.map(lambda f: drop_df.get(f, np.nan))\n"
    "stab_df = stab_df.sort_values('perm_imp', ascending=False)\n"
    "\n"
    "print(f'{\"Feature\":<35} {\"IC mean\":>8} {\"IC+%\":>6} {\"PermImp\":>8} {\"DropOne\":>8}')\n"
    "print('-' * 72)\n"
    "for feat, row in stab_df.iterrows():\n"
    "    print(f'{feat:<35} {row[\"ic_mean\"]:>+8.4f} {row[\"ic_pos_frac\"]:>6.0%} '\n"
    "          f'{row[\"perm_imp\"]:>+8.5f} {row[\"drop_one_impact\"]:>+8.5f}')"
))

# ── Cell 14: Pruning decision ─────────────────────────────────────────────────
cells.append(code(
    "# Pruning rules (conservative):\n"
    "#   REMOVE if ALL of:\n"
    "#     - Permutation importance <= 0 (shuffling it doesn't hurt)\n"
    "#     - Drop-one impact < 0 (removing it actually helps)\n"
    "#     - IC fold stability < 45% (negative IC more often than positive)\n"
    "\n"
    "pruning = []\n"
    "for feat, row in stab_df.iterrows():\n"
    "    perm = row['perm_imp'] if not np.isnan(row['perm_imp']) else 0\n"
    "    drop = row['drop_one_impact'] if not np.isnan(row['drop_one_impact']) else 0\n"
    "    stab = row['ic_pos_frac'] if not np.isnan(row['ic_pos_frac']) else 0.5\n"
    "\n"
    "    reasons = []\n"
    "    strikes = 0\n"
    "    if perm <= 0:    strikes += 1; reasons.append('perm_imp<=0')\n"
    "    if drop < 0:     strikes += 1; reasons.append('drop_one<0')\n"
    "    if stab < 0.45:  strikes += 1; reasons.append('IC+<45%')\n"
    "\n"
    "    verdict = 'REMOVE' if strikes >= 2 else 'KEEP'\n"
    "    pruning.append({'feature': feat, 'perm_imp': perm, 'drop_one': drop,\n"
    "                    'ic_pos': stab, 'strikes': strikes, 'verdict': verdict,\n"
    "                    'reasons': ', '.join(reasons)})\n"
    "\n"
    "pruning_df = pd.DataFrame(pruning)\n"
    "\n"
    "keep_feats   = pruning_df[pruning_df['verdict']=='KEEP']['feature'].tolist()\n"
    "remove_feats = pruning_df[pruning_df['verdict']=='REMOVE']['feature'].tolist()\n"
    "\n"
    "print('=' * 60)\n"
    "print('FEATURE PRUNING DECISION')\n"
    "print('=' * 60)\n"
    "print(f'\\nKEEP ({len(keep_feats)} features):')\n"
    "for f in keep_feats:\n"
    "    r = pruning_df[pruning_df['feature']==f].iloc[0]\n"
    "    print(f'  [KEEP]   {f:<35} IC+%={r[\"ic_pos\"]:.0%} perm={r[\"perm_imp\"]:+.5f}')\n"
    "\n"
    "print(f'\\nREMOVE ({len(remove_feats)} features):')\n"
    "for f in remove_feats:\n"
    "    r = pruning_df[pruning_df['feature']==f].iloc[0]\n"
    "    print(f'  [REMOVE] {f:<35} IC+%={r[\"ic_pos\"]:.0%} ({r[\"reasons\"]})')"
))

# ── Cell 15: Task 3 header ────────────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## Task 3 -- Model Simplification\n"
    "\n"
    "**Question:** Is XGBoost's additional complexity justified vs Ridge?  \n"
    "A simpler model that performs equally well is preferred — Occam's razor.\n"
    "\n"
    "Compare 4 configurations:\n"
    "- Ridge-All (full LAG_MARKET, post-collinearity)\n"
    "- Ridge-Pruned (KEEP features only)\n"
    "- XGB-Shallow (max_depth=2, n_estimators=50)\n"
    "- XGB-Pruned (KEEP features, max_depth=2)\n"
))

# ── Cell 16: Model simplification comparison ──────────────────────────────────
cells.append(code(
    "models_to_compare = [\n"
    "    ('Ridge-All',    Pipeline([('sc', StandardScaler()), ('r', Ridge(100.))]),\n"
    "     LAG_MARKET_DECORR),\n"
    "    ('Ridge-Pruned', Pipeline([('sc', StandardScaler()), ('r', Ridge(100.))]),\n"
    "     [f for f in keep_feats if f in df.columns]),\n"
    "    ('XGB-Shallow',  XGBRegressor(n_estimators=50, max_depth=2, learning_rate=0.05,\n"
    "                                  subsample=0.7, colsample_bytree=0.5,\n"
    "                                  min_child_weight=20, reg_alpha=1., reg_lambda=10.,\n"
    "                                  random_state=42, verbosity=0, n_jobs=1),\n"
    "     LAG_MARKET_DECORR),\n"
    "    ('XGB-Pruned',   XGBRegressor(n_estimators=50, max_depth=2, learning_rate=0.05,\n"
    "                                  subsample=0.7, colsample_bytree=0.5,\n"
    "                                  min_child_weight=20, reg_alpha=1., reg_lambda=10.,\n"
    "                                  random_state=42, verbosity=0, n_jobs=1),\n"
    "     [f for f in keep_feats if f in df.columns]),\n"
    "]\n"
    "\n"
    "model_results = {}\n"
    "for name, model, feats in models_to_compare:\n"
    "    folds = walk_forward(df, feats, TARGET, model, min_train=MIN_TRAIN, fold_size=52)\n"
    "    stats = summary_stats(folds)\n"
    "    model_results[name] = {'stats': stats, 'folds': folds, 'n_feats': len(feats)}\n"
    "    s = stats\n"
    "    print(f'{name:<15} | feats={len(feats):2d} | '\n"
    "          f'DA={s[\"da_mean\"]:.3f} | IC={s[\"ic_mean\"]:+.4f} | '\n"
    "          f'ICIR={s[\"icir\"]:+.3f} | p={s[\"ic_pval\"]:.3f}')"
))

# ── Cell 17: Simplification plot ──────────────────────────────────────────────
cells.append(code(
    "fig, axes = plt.subplots(1, 3, figsize=(13, 4))\n"
    "fig.suptitle('Task 3: Model Complexity vs OOS Performance', fontsize=12)\n"
    "\n"
    "names = list(model_results.keys())\n"
    "da_vals   = [model_results[n]['stats']['da_mean'] for n in names]\n"
    "ic_vals   = [model_results[n]['stats']['ic_mean'] for n in names]\n"
    "icir_vals = [model_results[n]['stats']['icir']    for n in names]\n"
    "n_feats   = [model_results[n]['n_feats']          for n in names]\n"
    "\n"
    "x = range(len(names))\n"
    "bar_kw = dict(color=['#2196F3','#42A5F5','#FF5722','#FF8A65'], alpha=0.8)\n"
    "\n"
    "axes[0].bar(x, da_vals, **bar_kw)\n"
    "axes[0].axhline(0.5, color='black', lw=0.8, ls='--')\n"
    "axes[0].set_title('DirAcc'); axes[0].set_ylim(0.45, 0.60)\n"
    "axes[0].set_xticks(x); axes[0].set_xticklabels(names, rotation=30, ha='right')\n"
    "for i, v in enumerate(da_vals): axes[0].text(i, v+0.001, f'{v:.3f}', ha='center', fontsize=8)\n"
    "\n"
    "axes[1].bar(x, ic_vals, **bar_kw)\n"
    "axes[1].axhline(0, color='black', lw=0.8, ls='--')\n"
    "axes[1].set_title('Mean IC')\n"
    "axes[1].set_xticks(x); axes[1].set_xticklabels(names, rotation=30, ha='right')\n"
    "for i, v in enumerate(ic_vals): axes[1].text(i, v+0.001, f'{v:+.3f}', ha='center', fontsize=8)\n"
    "\n"
    "axes[2].bar(x, icir_vals, **bar_kw)\n"
    "axes[2].axhline(0.5, color='black', lw=0.8, ls='--', label='ICIR=0.5 threshold')\n"
    "axes[2].set_title('ICIR')\n"
    "axes[2].set_xticks(x); axes[2].set_xticklabels(names, rotation=30, ha='right')\n"
    "for i, v in enumerate(icir_vals): axes[2].text(i, v+0.02, f'{v:+.2f}', ha='center', fontsize=8)\n"
    "axes[2].legend(fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'simplification_comparison.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/simplification_comparison.png')"
))

# ── Cell 18: Task 4 header ────────────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## Task 4 -- Strong Signal Test\n"
    "\n"
    "**Final stress test:** Run walk-forward on top-5 and top-10 features only.  \n"
    "If the core signal is real, it should survive extreme dimensionality reduction.\n"
    "\n"
    "Features ranked by permutation importance (positive = helpful when present).\n"
    "Bootstrap and permutation test on the top-5 model.\n"
))

# ── Cell 19: Top-k features selection ────────────────────────────────────────
cells.append(code(
    "# Rank by permutation importance; take top-5 and top-10\n"
    "pos_feats = perm_df[perm_df > 0].index.tolist()\n"
    "print(f'Features with positive permutation importance: {len(pos_feats)}')\n"
    "print()\n"
    "\n"
    "TOP5  = pos_feats[:5]\n"
    "TOP10 = pos_feats[:10] if len(pos_feats) >= 10 else pos_feats\n"
    "\n"
    "print(f'Top-5 features:')\n"
    "for i, f in enumerate(TOP5, 1):\n"
    "    print(f'  {i}. {f:<35} perm_imp={perm_df[f]:+.5f}')\n"
    "\n"
    "if len(TOP10) > 5:\n"
    "    print(f'\\nTop-6 to {len(TOP10)}:')\n"
    "    for i, f in enumerate(TOP10[5:], 6):\n"
    "        print(f'  {i}. {f:<35} perm_imp={perm_df[f]:+.5f}')"
))

# ── Cell 20: Strong signal walk-forward ───────────────────────────────────────
cells.append(code(
    "# Walk-forward with top-5 and top-10 only\n"
    "best_model_name = min(model_results, key=lambda n: model_results[n]['stats']['ic_pval'])\n"
    "print(f'Best model from Task 3: {best_model_name}')\n"
    "best_model_cfg = next(m for (nm, m, _) in models_to_compare if nm == best_model_name)\n"
    "\n"
    "top5_folds  = walk_forward(df, TOP5, TARGET, clone(best_model_cfg),\n"
    "                            min_train=MIN_TRAIN, fold_size=52)\n"
    "top10_folds = walk_forward(df, TOP10, TARGET, clone(best_model_cfg),\n"
    "                            min_train=MIN_TRAIN, fold_size=52)\n"
    "all_folds   = walk_forward(df, LAG_MARKET_DECORR, TARGET, clone(best_model_cfg),\n"
    "                            min_train=MIN_TRAIN, fold_size=52)\n"
    "\n"
    "top5_stats  = summary_stats(top5_folds)\n"
    "top10_stats = summary_stats(top10_folds)\n"
    "all_stats   = summary_stats(all_folds)\n"
    "\n"
    "print(f'\\nStrong Signal Test Results:')\n"
    "print(f'{\"Config\":<20} {\"N feats\":>8} {\"DirAcc\":>8} {\"IC\":>8} {\"ICIR\":>7} {\"p\":>7}')\n"
    "print('-' * 60)\n"
    "for lbl, feats, stats in [\n"
    "    ('All (baseline)',  LAG_MARKET_DECORR, all_stats),\n"
    "    (f'Top-{len(TOP10)}', TOP10, top10_stats),\n"
    "    (f'Top-5',           TOP5,  top5_stats),\n"
    "]:\n"
    "    s = stats\n"
    "    print(f'{lbl:<20} {len(feats):>8} {s[\"da_mean\"]:>8.3f} '\n"
    "          f'{s[\"ic_mean\"]:>+8.4f} {s[\"icir\"]:>+7.3f} {s[\"ic_pval\"]:>7.3f}')"
))

# ── Cell 21: Bootstrap + permutation on top-5 ────────────────────────────────
cells.append(code(
    "# Bootstrap test on top-5 model\n"
    "N_BOOT = 2000\n"
    "\n"
    "all_preds = np.concatenate([f['y_pred'] for f in top5_folds])\n"
    "all_true  = np.concatenate([f['y_true'] for f in top5_folds])\n"
    "actual_da = dir_acc(all_preds, all_true)\n"
    "\n"
    "boot_das = []\n"
    "n_oos = len(all_preds)\n"
    "for _ in range(N_BOOT):\n"
    "    idx = np.random.randint(0, n_oos, n_oos)\n"
    "    boot_das.append(dir_acc(all_preds[idx], all_true[idx]))\n"
    "boot_p = float(np.mean([d <= 0.5 for d in boot_das]))\n"
    "\n"
    "# Permutation test on top-5 model\n"
    "N_PERM_TEST = 1000\n"
    "perm_das = []\n"
    "for seed in range(N_PERM_TEST):\n"
    "    rng = np.random.RandomState(seed)\n"
    "    y_shuf = rng.permutation(all_true)\n"
    "    perm_das.append(dir_acc(all_preds, y_shuf))\n"
    "perm_p = float(np.mean([d >= actual_da for d in perm_das]))\n"
    "\n"
    "# IC t-test\n"
    "top5_ics = [f['ic'] for f in top5_folds if not np.isnan(f['ic'])]\n"
    "t_stat, ic_p = ttest_1samp(top5_ics, 0)\n"
    "\n"
    "print('Top-5 Model Statistical Tests:')\n"
    "print(f'  OOS DirAcc:        {actual_da:.4f}')\n"
    "print(f'  IC mean:           {np.mean(top5_ics):+.4f}')\n"
    "print(f'  ICIR:              {icir(top5_ics):+.4f}')\n"
    "print(f'  IC t-stat:         {t_stat:+.3f}  (p={ic_p:.4f})')\n"
    "print(f'  Bootstrap p:       {boot_p:.4f}  (DirAcc > 50%)')\n"
    "print(f'  Permutation p:     {perm_p:.4f}  (DirAcc >= actual)')\n"
    "print()\n"
    "print('Interpretation:')\n"
    "if ic_p < 0.05: print('  [+] IC t-test SIGNIFICANT (p<0.05)')\n"
    "else:           print(f'  [-] IC t-test NOT significant (p={ic_p:.3f})')\n"
    "if boot_p < 0.05: print('  [+] Bootstrap SIGNIFICANT (p<0.05)')\n"
    "else:             print(f'  [-] Bootstrap NOT significant (p={boot_p:.3f})')\n"
    "if perm_p < 0.10: print('  [+] Permutation test BORDERLINE/significant (p<0.10)')\n"
    "else:             print(f'  [-] Permutation NOT significant (p={perm_p:.3f})')"
))

# ── Cell 22: IC stability plot ────────────────────────────────────────────────
cells.append(code(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "fig.suptitle('Task 4: Strong Signal Test -- Top-5 vs All Features (IC per Fold)', fontsize=12)\n"
    "\n"
    "for ax, (folds, lbl, col) in zip(axes, [\n"
    "    (all_folds,  f'All {len(LAG_MARKET_DECORR)} features', '#78909C'),\n"
    "    (top5_folds, f'Top-5 features only',                    '#2196F3'),\n"
    "]):\n"
    "    ics = [f['ic'] for f in folds]\n"
    "    colors = [col if x > 0 else '#EF5350' for x in ics]\n"
    "    ax.bar(range(len(ics)), ics, color=colors, alpha=0.8)\n"
    "    ax.axhline(0, color='black', lw=0.8, ls='--')\n"
    "    ax.axhline(np.nanmean(ics), color='navy', lw=1.5,\n"
    "               label=f'Mean IC={np.nanmean(ics):+.3f}')\n"
    "    stats_ = summary_stats(folds)\n"
    "    ax.set_title(f'{lbl}\\nIC+%={stats_[\"ic_pos_frac\"]:.0%}, '\n"
    "                 f'ICIR={stats_[\"icir\"]:+.2f}, p={stats_[\"ic_pval\"]:.3f}')\n"
    "    ax.set_xlabel('Fold #')\n"
    "    ax.set_ylabel('IC')\n"
    "    ax.set_ylim(-0.25, 0.25)\n"
    "    ax.legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIGS / 'strong_signal_test.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved: figs/strong_signal_test.png')"
))

# ── Cell 23: Final Verdict header ─────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## Final Verdict -- Is There a Stable Alpha?\n"
    "\n"
    "Evidence table with conservative scoring.  \n"
    "**Conservative rule:** 5+ pieces of positive evidence → REAL signal. Fewer → FRAGILE or NOISE.\n"
))

# ── Cell 24: Evidence table and verdict ───────────────────────────────────────
cells.append(code(
    "# ── Evidence scoring ────────────────────────────────────────────────────────\n"
    "\n"
    "# Collect key metrics\n"
    "s52 = stability_results[52]['stats']   # 52w baseline\n"
    "s26 = stability_results[26]['stats']   # 26w\n"
    "s104 = stability_results[104]['stats'] # 104w\n"
    "\n"
    "t5_ics = [f['ic'] for f in top5_folds if not np.isnan(f['ic'])]\n"
    "t5_stat, t5_p = ttest_1samp(t5_ics, 0) if len(t5_ics) >= 3 else (np.nan, np.nan)\n"
    "\n"
    "evidence = []\n"
    "score = 0\n"
    "\n"
    "def ev(desc, value, threshold, passes, note=''):\n"
    "    global score\n"
    "    sign = '+' if passes else '-'\n"
    "    if passes: score += 1\n"
    "    evidence.append((sign, desc, value, threshold, note))\n"
    "\n"
    "# Task 1 evidence\n"
    "ev('IC positive (52w folds)',   s52['ic_mean'],      '>0',     s52['ic_mean'] > 0)\n"
    "ev('IC positive (26w folds)',   s26['ic_mean'],      '>0',     s26['ic_mean'] > 0)\n"
    "ev('IC positive (104w folds)',  s104['ic_mean'],     '>0',     s104['ic_mean'] > 0)\n"
    "ev('IC+ fraction (52w)',        s52['ic_pos_frac'],  '>55%',   s52['ic_pos_frac'] > 0.55)\n"
    "ev('ICIR (52w)',                s52['icir'],         '>0.5',   s52['icir'] > 0.5)\n"
    "ev('IC t-stat p (52w baseline)',s52['ic_pval'],      '<0.10',  s52['ic_pval'] < 0.10)\n"
    "\n"
    "# Task 4 evidence (top-5 model)\n"
    "ev('IC t-stat p (Top-5)',       t5_p,               '<0.10',  t5_p < 0.10 if not np.isnan(t5_p) else False)\n"
    "ev('Bootstrap p (Top-5)',       boot_p,             '<0.05',  boot_p < 0.05)\n"
    "ev('Permutation p (Top-5)',     perm_p,             '<0.10',  perm_p < 0.10)\n"
    "ev('DirAcc (Top-5)',            actual_da,          '>0.52',  actual_da > 0.52)\n"
    "\n"
    "# Task 2 evidence\n"
    "n_positive_perm = sum(1 for v in perm_df if v > 0)\n"
    "ev('Features with +perm_imp',   n_positive_perm,    '>=5',    n_positive_perm >= 5)\n"
    "\n"
    "print('=' * 72)\n"
    "print('FINAL EVIDENCE TABLE')\n"
    "print('=' * 72)\n"
    "print(f'{\"\":>2} {\"Evidence\":<38} {\"Value\":>10} {\"Threshold\":>10}')\n"
    "print('-' * 65)\n"
    "for sign, desc, val, thresh, note in evidence:\n"
    "    val_str = f'{val:.4f}' if isinstance(val, float) else str(val)\n"
    "    print(f'[{sign}] {desc:<38} {val_str:>10} {thresh:>10}')\n"
    "\n"
    "print(f'\\nScore: {score}/{len(evidence)} positive evidence points')\n"
    "print()\n"
    "\n"
    "if score >= 7:\n"
    "    verdict = 'REAL but fragile'\n"
    "    detail  = ('Signal appears real but narrow. IC is positive and statistically '\n"
    "               'borderline significant. Top features are consistent. '\n"
    "               'Proceed with caution: small TC budget, regime-aware sizing.')\n"
    "elif score >= 5:\n"
    "    verdict = 'BORDERLINE -- weak signal'\n"
    "    detail  = ('Some statistical support but evidence is mixed. IC is inconsistent '\n"
    "               'across regimes/fold-sizes. Treat as fragile. Require >2x more data '\n"
    "               'before production use.')\n"
    "else:\n"
    "    verdict = 'NOISE -- no reliable alpha'\n"
    "    detail  = ('Insufficient statistical evidence. IC is inconsistent, tests mostly '\n"
    "               'fail. The apparent DirAcc edge is within chance variation. '\n"
    "               'Do not trade this signal.')\n"
    "\n"
    "print('=' * 72)\n"
    "print(f'VERDICT: {verdict}')\n"
    "print('=' * 72)\n"
    "print()\n"
    "print(detail)\n"
    "print()\n"
    "\n"
    "# Best model from Task 3\n"
    "best_task3 = min(model_results, key=lambda n: model_results[n]['stats']['ic_pval'])\n"
    "print(f'Recommended model config: {best_task3}')\n"
    "print(f'Top features to use: {TOP5}')\n"
    "print(f'Features pruned (remove): {remove_feats}')"
))

# ── Cell 25: Summary of recommendations ──────────────────────────────────────
cells.append(code(
    "print('=' * 72)\n"
    "print('RECOMMENDATIONS')\n"
    "print('=' * 72)\n"
    "\n"
    "recs = [\n"
    "    ('Model', best_task3, 'Best OOS p-value in Task 3 comparison'),\n"
    "    ('Features', f'Top-5 to Top-{len(TOP10)} from perm_importance', 'Pruned set outperforms full in robustness'),\n"
    "    ('Fold structure', '52w folds, expanding window', 'Signal most consistent at annual scale'),\n"
    "    ('Regime', 'Normal regime best; be cautious in Crisis', 'Regime breakdown shows uneven IC'),\n"
    "    ('NLP', 'Not yet validated (sparse coverage)', 'Only 47% weeks have NLP data 2022-2025'),\n"
    "]\n"
    "\n"
    "for topic, val, reason in recs:\n"
    "    print(f'  {topic:<15}: {val}')\n"
    "    print(f'  {\"\":15}  ({reason})')\n"
    "    print()\n"
    "\n"
    "print('\\nNext steps:')\n"
    "print('  1. Collect more NLP data (>80% weekly coverage) before including NLP features')\n"
    "print('  2. Run full backtesting notebook (PnL, drawdown, TC sensitivity) on top-5 signal')\n"
    "print('  3. If ICIR > 1.0 persists on 3+ more years of OOS data -> upgrade to REAL')"
))

# ── Write notebook ─────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"},
    },
    "cells": cells,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Generated: {OUT}")
print(f"Cells: {len(cells)}")
